// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'empty' GraphQL query.
/// </summary>
public sealed partial class GetEmptyRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetEmptyRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'empty'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetEmptyData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetEmpty { empty}";
        return _graphQlClient.Execute<GetEmptyData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'empty' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<string?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetEmptyData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.Empty;
    }
}
