// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'versions' GraphQL query.
/// </summary>
public sealed partial class GetVersionsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetVersionsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'versions'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetVersionsData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetVersions { versions { kind value display_name } }";
        return _graphQlClient.Execute<GetVersionsData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'versions' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<Version>?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetVersionsData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.Versions;
    }
}
