// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_view_table' GraphQL mutation.
/// </summary>
public sealed partial class CreateViewTableRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateViewTableRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_view_table' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateViewTableData>> Execute(CreateViewTableVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateViewTable($board_id: ID!, $name: String, $filter_user_id: ID, $filter_team_id: ID, $filter: ItemsQueryGroup, $sort: [ItemsQueryOrderBy!], $tags: [String!], $settings: TableViewSettingsInput) { create_view_table(board_id: $board_id, name: $name, filter_user_id: $filter_user_id, filter_team_id: $filter_team_id, filter: $filter, sort: $sort, tags: $tags, settings: $settings) { access_level id name settings_str source_view_id type view_specific_data_str settings sort filter_user_id filter_team_id tags filter } }";
        return _graphQlClient.Execute<CreateViewTableData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_view_table' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<BoardView?> GetValue(CreateViewTableVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateViewTableData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateViewTable;
    }
}
