// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of activating users.
/// </summary>
public sealed partial class ActivateUsersResult
{
    /// <summary>
    /// The users that were activated.
    /// </summary>
    [JsonPropertyName("activated_users")]
    public List<User>? ActivatedUsers { get; init; }

    /// <summary>
    /// Errors that occurred during activation.
    /// </summary>
    [JsonPropertyName("errors")]
    public List<ActivateUsersError>? Errors { get; init; }

}
