// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An action item from a meeting.
/// </summary>
public sealed partial class ActionItem
{
    /// <summary>
    /// The unique identifier of the action item.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The text content of the action item.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; init; } = null!;

    /// <summary>
    /// Whether the action item has been completed.
    /// </summary>
    [JsonPropertyName("is_completed")]
    public bool IsCompleted { get; init; }

    /// <summary>
    /// The owner assigned to the action item.
    /// </summary>
    [JsonPropertyName("owner")]
    public string? Owner { get; init; }

    /// <summary>
    /// The due date of the action item.
    /// </summary>
    [JsonPropertyName("due_date")]
    public DateOnly? DueDate { get; init; }

}
