// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A monday.com agent.
/// </summary>
public sealed partial class Agent
{
    /// <summary>
    /// The ID of the agent.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

}
