// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class AggregateQueryResult
{
    [JsonPropertyName("results")]
    public List<AggregateResultSet>? Results { get; init; }

}
