// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The result of configuring AI on a column.
/// </summary>
public sealed partial class AiColumnResult
{
    /// <summary>
    /// The ID of the column that was configured.
    /// </summary>
    [JsonPropertyName("column_id")]
    public string ColumnId { get; init; } = null!;

}
