// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Maps an API app to an API-app-backed user within an account.
/// </summary>
public sealed partial class ApiAppUserMapping
{
    /// <summary>
    /// The mapped user.
    /// </summary>
    [JsonPropertyName("user")]
    public User User { get; init; } = null!;

}
