// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An audit record for app actions
/// </summary>
public sealed partial class AppAudit
{
    /// <summary>
    /// Unique identifier for the audit record
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The account ID associated with the audit
    /// </summary>
    [JsonPropertyName("account_id")]
    public string AccountId { get; init; } = null!;

    /// <summary>
    /// The user ID who performed the action
    /// </summary>
    [JsonPropertyName("user_id")]
    public string UserId { get; init; } = null!;

    /// <summary>
    /// Whether the user who performed the action is an admin
    /// </summary>
    [JsonPropertyName("is_admin")]
    public bool IsAdmin { get; init; }

    /// <summary>
    /// The type of audit action
    /// </summary>
    [JsonPropertyName("type")]
    public AppAuditKind? Type { get; init; }

    /// <summary>
    /// The app ID that was audited
    /// </summary>
    [JsonPropertyName("app_id")]
    public string AppId { get; init; } = null!;

    /// <summary>
    /// The date and time the audit record was created
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly? CreatedAt { get; init; }

}
