// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response from querying the apps documentation AI.
/// </summary>
public sealed partial class AppDocumentationAiResponse
{
    /// <summary>
    /// Unique identifier for this query response.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The original question that was asked.
    /// </summary>
    [JsonPropertyName("question")]
    public string? Question { get; init; }

    /// <summary>
    /// The AI-generated answer based on the documentation.
    /// </summary>
    [JsonPropertyName("answer")]
    public string Answer { get; init; } = null!;

    /// <summary>
    /// The conversation ID for follow-up queries.
    /// </summary>
    [JsonPropertyName("conversation_id")]
    public string? ConversationId { get; init; }

}
