// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The Operations counter response for the app action.
/// </summary>
public sealed partial class AppSubscriptionOperationsCounter
{
    /// <summary>
    /// The account subscription details for the app.
    /// </summary>
    [JsonPropertyName("app_subscription")]
    public AppSubscription? AppSubscription { get; init; }

    /// <summary>
    /// The new counter value.
    /// </summary>
    [JsonPropertyName("counter_value")]
    public int? CounterValue { get; init; }

    /// <summary>
    /// Operations name.
    /// </summary>
    [JsonPropertyName("kind")]
    public string Kind { get; init; } = null!;

    /// <summary>
    /// Window key.
    /// </summary>
    [JsonPropertyName("period_key")]
    public string? PeriodKey { get; init; }

}
