// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Per-resource outcomes of a time off assignment, split by resource kind
/// </summary>
public sealed partial class AssignTimeOffResult
{
    /// <summary>
    /// One result per user id passed to the mutation
    /// </summary>
    [JsonPropertyName("users")]
    public List<AssignTimeOffUserResult> Users { get; init; } = [];

    /// <summary>
    /// One result per team id passed to the mutation
    /// </summary>
    [JsonPropertyName("teams")]
    public List<AssignTimeOffTeamResult> Teams { get; init; } = [];

}
