// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of a time off assignment for a single team. Batch mutations return one of these per requested team, allowing partial success.
/// </summary>
public sealed partial class AssignTimeOffTeamResult
{
    /// <summary>
    /// ID of the team this result applies to
    /// </summary>
    [JsonPropertyName("team_id")]
    public string TeamId { get; init; } = null!;

    /// <summary>
    /// Whether the operation succeeded
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; init; }

    /// <summary>
    /// Structured error details, null if the operation succeeded
    /// </summary>
    [JsonPropertyName("error")]
    public Error? Error { get; init; }

}
