// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The outcome of attaching one board within a bulk attach request. Boards are independent, so a request can return a mix of successes and failures and the successes are not undone.
/// </summary>
public sealed partial class AttachBoardToObjectSchemaResult
{
    /// <summary>
    /// The board this result describes.
    /// </summary>
    [JsonPropertyName("board_id")]
    public string? BoardId { get; init; }

    /// <summary>
    /// Whether this board (and its classic subitems board, if any) now follows the object schema.
    /// </summary>
    [JsonPropertyName("success")]
    public bool? Success { get; init; }

    /// <summary>
    /// Human readable reason the board was not attached. For display fallback and logs, not branching.
    /// </summary>
    [JsonPropertyName("error")]
    public string? Error { get; init; }

    /// <summary>
    /// Stable code for the refusal, for example templateTopologyMismatch or templateBoardAlreadyAttached. This is what clients should classify on to pick a message.
    /// </summary>
    [JsonPropertyName("error_code")]
    public string? ErrorCode { get; init; }

}
