// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Text formatting attributes (bold, italic, links, colors, etc.)
/// </summary>
public sealed partial class Attributes
{
    /// <summary>
    /// Apply bold formatting to the text
    /// </summary>
    [JsonPropertyName("bold")]
    public bool? Bold { get; init; }

    /// <summary>
    /// Apply italic formatting to the text
    /// </summary>
    [JsonPropertyName("italic")]
    public bool? Italic { get; init; }

    /// <summary>
    /// Apply underline formatting to the text
    /// </summary>
    [JsonPropertyName("underline")]
    public bool? Underline { get; init; }

    /// <summary>
    /// Apply strikethrough formatting to the text
    /// </summary>
    [JsonPropertyName("strike")]
    public bool? Strike { get; init; }

    /// <summary>
    /// Apply inline code formatting to the text
    /// </summary>
    [JsonPropertyName("code")]
    public bool? Code { get; init; }

    /// <summary>
    /// URL to create a hyperlink
    /// </summary>
    [JsonPropertyName("link")]
    public string? Link { get; init; }

    /// <summary>
    /// Text color (hex, rgb, or named color)
    /// </summary>
    [JsonPropertyName("color")]
    public string? Color { get; init; }

    /// <summary>
    /// Background color for text highlighting (hex, rgb, or named color)
    /// </summary>
    [JsonPropertyName("background")]
    public string? Background { get; init; }

}
