// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A page of automations with cursor for pagination
/// </summary>
public sealed partial class AutomationsPage
{
    /// <summary>
    /// Opaque cursor for fetching the next page. Null if no more results.
    /// </summary>
    [JsonPropertyName("cursor")]
    public string? Cursor { get; init; }

    /// <summary>
    /// The automations in this page
    /// </summary>
    [JsonPropertyName("items")]
    public List<BoardAutomation>? Items { get; init; }

    /// <summary>
    /// Read-only automations on this board that were set up in an older way. These ARE automations on the user's board — always list and describe them together with `items`, never omit them. They cannot be activated, deactivated, edited, or deleted. Resolved only for board-scoped queries (null otherwise); best-effort, so it may carry an error marker instead of data.
    /// </summary>
    [JsonPropertyName("legacy_automations")]
    public string? LegacyAutomations { get; init; }

}
