// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Describes what type of change occurred to a block between two versions.
/// </summary>
public sealed partial class BlockChanges
{
    /// <summary>
    /// True if this block was added in the newer version.
    /// </summary>
    [JsonPropertyName("added")]
    public bool? Added { get; init; }

    /// <summary>
    /// True if this block was deleted in the newer version. The content reflects the state before deletion.
    /// </summary>
    [JsonPropertyName("deleted")]
    public bool? Deleted { get; init; }

    /// <summary>
    /// True if this block content was modified between the two versions.
    /// </summary>
    [JsonPropertyName("changed")]
    public bool? Changed { get; init; }

}
