// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Context-specific data for a block, organized by context name
/// </summary>
public sealed partial class BlockContextData
{
    /// <summary>
    /// Context data for the workflow builder
    /// </summary>
    [JsonPropertyName("workflow_builder")]
    public WorkflowBuilderContextData? WorkflowBuilder { get; init; }

    /// <summary>
    /// Context data for the lite builder
    /// </summary>
    [JsonPropertyName("lite_builder")]
    public LiteBuilderContextData? LiteBuilder { get; init; }

    /// <summary>
    /// Context data for Monday agents
    /// </summary>
    [JsonPropertyName("monday_agents")]
    public MondayAgentsContextData? MondayAgents { get; init; }

}
