// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of a blocks query
/// </summary>
public sealed partial class BlocksResult
{
    /// <summary>
    /// List of blocks
    /// </summary>
    [JsonPropertyName("blocks")]
    public List<Block>? Blocks { get; init; }

}
