// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of enhancing a board with AI columns.
/// </summary>
public sealed partial class BoardEnhancementResult
{
    /// <summary>
    /// The ID of the board that was enhanced.
    /// </summary>
    [JsonPropertyName("board_id")]
    public string? BoardId { get; init; }

    /// <summary>
    /// The result of the AI column enhancement.
    /// </summary>
    [JsonPropertyName("result")]
    public ConvertColumnsToAiResult? Result { get; init; }

}
