// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Manually set metadata associated with a board.
/// </summary>
public sealed partial class BoardManualMetadata
{
    /// <summary>
    /// Markdown content describing the board
    /// </summary>
    [JsonPropertyName("board_md")]
    public string? BoardMd { get; init; }

}
