// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of creating a board automation
/// </summary>
public sealed partial class BoardAutomationCreateResult
{
    /// <summary>
    /// The ID of the created automation
    /// </summary>
    [JsonPropertyName("workflow_id")]
    public string? WorkflowId { get; init; }

}
