// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Represents a board and its connection to an object schema.
/// </summary>
public sealed partial class BoardConnection
{
    /// <summary>
    /// The unique identifier of the board.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The object schema ID that this board is connected to.
    /// </summary>
    [JsonPropertyName("object_schema_id")]
    public string? ObjectSchemaId { get; init; }

}
