// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Paginated list of items with their dependency predecessor edges for a board
/// </summary>
public sealed partial class BoardDependencies
{
    /// <summary>
    /// List of items with their predecessor edges for the current page
    /// </summary>
    [JsonPropertyName("items")]
    public List<ItemDependency>? Items { get; init; }

    /// <summary>
    /// Total number of items across all pages
    /// </summary>
    [JsonPropertyName("total_count")]
    public int? TotalCount { get; init; }

}
