// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Unsubscribe footer configuration
/// </summary>
public sealed partial class CampaignsUnsubscribeFooter
{
    /// <summary>
    /// Whether removal is allowed
    /// </summary>
    [JsonPropertyName("allow_removal")]
    public bool? AllowRemoval { get; init; }

}
