// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Marketing channels settings for the current account
/// </summary>
public sealed partial class CampaignsSettings
{
    /// <summary>
    /// Company information settings
    /// </summary>
    [JsonPropertyName("company_information")]
    public CampaignsCompanyInformation? CompanyInformation { get; init; }

    /// <summary>
    /// Unsubscribe page configuration
    /// </summary>
    [JsonPropertyName("unsubscribe_page")]
    public CampaignsUnsubscribePage? UnsubscribePage { get; init; }

    /// <summary>
    /// Unsubscribe footer configuration
    /// </summary>
    [JsonPropertyName("unsubscribe_footer")]
    public CampaignsUnsubscribeFooter? UnsubscribeFooter { get; init; }

    /// <summary>
    /// Marketing contacts board configuration
    /// </summary>
    [JsonPropertyName("contacts_board")]
    public CampaignsContactsBoard? ContactsBoard { get; init; }

}
