// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Paginated analytics events response
/// </summary>
public sealed partial class CampaignsAnalyticsEventsResponse
{
    /// <summary>
    /// List of analytics events
    /// </summary>
    [JsonPropertyName("data")]
    public List<CampaignsAnalyticsEvent>? Data { get; init; }

    /// <summary>
    /// Token for pagination to retrieve next batch
    /// </summary>
    [JsonPropertyName("next_token")]
    public string? NextToken { get; init; }

}
