// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An audience segment
/// </summary>
public sealed partial class CampaignsSegment
{
    /// <summary>
    /// Unique segment identifier
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Name of the segment
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Type of the segment
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// Timestamp when the segment was created
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// Timestamp when the segment was last updated
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

    /// <summary>
    /// User who created the segment
    /// </summary>
    [JsonPropertyName("created_by")]
    public User? CreatedBy { get; init; }

    /// <summary>
    /// ID of the data source
    /// </summary>
    [JsonPropertyName("data_source_id")]
    public string? DataSourceId { get; init; }

    /// <summary>
    /// Entity ID from the data source
    /// </summary>
    [JsonPropertyName("data_source_entity_id")]
    public string? DataSourceEntityId { get; init; }

    /// <summary>
    /// Entity type from the data source
    /// </summary>
    [JsonPropertyName("data_source_entity_type")]
    public string? DataSourceEntityType { get; init; }

}
