// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A board-type data view source that is a child of a schema source.
/// </summary>
public sealed partial class ChildBoardDataViewSource
{
    /// <summary>
    /// The source identifier.
    /// </summary>
    [JsonPropertyName("source_id")]
    public DataViewSourceId? SourceId { get; init; }

    /// <summary>
    /// The parent schema source identifier.
    /// </summary>
    [JsonPropertyName("parent_source_id")]
    public DataViewSourceId? ParentSourceId { get; init; }

}
