// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A generated code file
/// </summary>
public sealed partial class CodeFile
{
    /// <summary>
    /// File path (e.g. src/generated/App.jsx)
    /// </summary>
    [JsonPropertyName("path")]
    public string? Path { get; init; }

    /// <summary>
    /// File content
    /// </summary>
    [JsonPropertyName("content")]
    public string? Content { get; init; }

}
