// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// One value the user chose for a field
/// </summary>
public sealed partial class ConfigureIntegrationFieldValue
{
    /// <summary>
    /// The chosen value, JSON-encoded
    /// </summary>
    [JsonPropertyName("value_json")]
    public string? ValueJson { get; init; }

    /// <summary>
    /// What the value is called, when it has a name
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }

}
