// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Target column metadata from the data view (mirror target column).
/// </summary>
public sealed partial class ConnectedTargetColumn
{
    /// <summary>
    /// The column identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The column title.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The column type.
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

}
