// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of a synchronous external-agent connect. agent_id is always present; signing_secret, api_token, and instructions are populated only for custom agents.
/// </summary>
public sealed partial class ConnectExternalAgentResult
{
    /// <summary>
    /// The internal monday-agents agent ID
    /// </summary>
    [JsonPropertyName("agent_id")]
    public string? AgentId { get; init; }

    /// <summary>
    /// Custom-agent only — secret used to sign callback requests. Never logged.
    /// </summary>
    [JsonPropertyName("signing_secret")]
    public string? SigningSecret { get; init; }

    /// <summary>
    /// Custom-agent only — API token for the agent to call back into monday. Never logged.
    /// </summary>
    [JsonPropertyName("api_token")]
    public string? ApiToken { get; init; }

    /// <summary>
    /// Custom-agent only — setup instructions for the integrator. Never logged.
    /// </summary>
    [JsonPropertyName("instructions")]
    public string? Instructions { get; init; }

}
