// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of creating multiple users.
/// </summary>
public sealed partial class CreateMultipleUsersResult
{
    /// <summary>
    /// Successfully created users.
    /// </summary>
    [JsonPropertyName("created_users")]
    public List<User>? CreatedUsers { get; init; }

    /// <summary>
    /// Users that could not be created.
    /// </summary>
    [JsonPropertyName("uncreated_users")]
    public List<UncreatedUser>? UncreatedUsers { get; init; }

}
