// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The result of creating a service user.
/// </summary>
public sealed partial class CreateServiceUserResult
{
    /// <summary>
    /// The created service user.
    /// </summary>
    [JsonPropertyName("user")]
    public User? User { get; init; }

}
