// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The current public-template-link share token if one exists for the app's live code version
/// </summary>
public sealed partial class CurrentPublicTemplateLinkResult
{
    /// <summary>
    /// The share token for the public template link
    /// </summary>
    [JsonPropertyName("share_token")]
    public string? ShareToken { get; init; }

}
