// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// API usage data.
/// </summary>
public sealed partial class DailyAnalytics
{
    /// <summary>
    /// Last time the API usage data was updated.
    /// </summary>
    [JsonPropertyName("last_updated")]
    public string? LastUpdated { get; init; }

    /// <summary>
    /// API usage per day.
    /// </summary>
    [JsonPropertyName("by_day")]
    public List<PlatformApiDailyAnalyticsByDay>? ByDay { get; init; }

    /// <summary>
    /// API usage per app.
    /// </summary>
    [JsonPropertyName("by_app")]
    public List<PlatformApiDailyAnalyticsByApp>? ByApp { get; init; }

    /// <summary>
    /// API usage per user.
    /// </summary>
    [JsonPropertyName("by_user")]
    public List<PlatformApiDailyAnalyticsByUser>? ByUser { get; init; }

}
