// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Aggregated result of synchronously loading all widget data for a dashboard.
/// </summary>
public sealed partial class DashboardDataResult
{
    /// <summary>
    /// Identifier of the dashboard whose widgets were loaded.
    /// </summary>
    [JsonPropertyName("dashboard_id")]
    public string? DashboardId { get; init; }

    /// <summary>
    /// Per-widget results for the dashboard, one entry per supported widget.
    /// </summary>
    [JsonPropertyName("widgets")]
    public List<WidgetResult>? Widgets { get; init; }

}
