// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Preview of a dashboard that will be created in the Magic solution.
/// </summary>
public sealed partial class DashboardPreview
{
    /// <summary>
    /// The unique identifier of the dashboard.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The name of the dashboard.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

}
