// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A column definition within a data view target.
/// </summary>
public sealed partial class DataViewColumn
{
    /// <summary>
    /// The unique identifier of the column.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The display title of the column.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The column type.
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// For mirror/lookup columns, the type of the column being displayed.
    /// </summary>
    [JsonPropertyName("sub_type")]
    public string? SubType { get; init; }

    /// <summary>
    /// The column settings.
    /// </summary>
    [JsonPropertyName("settings")]
    public string? Settings { get; init; }

    /// <summary>
    /// The column labels.
    /// </summary>
    [JsonPropertyName("labels")]
    public string? Labels { get; init; }

    /// <summary>
    /// The column label positions.
    /// </summary>
    [JsonPropertyName("labels_positions_v2")]
    public string? LabelsPositionsV2 { get; init; }

    /// <summary>
    /// Whether the column is archived.
    /// </summary>
    [JsonPropertyName("archived")]
    public bool? Archived { get; init; }

    /// <summary>
    /// The column description.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// The column model identifier.
    /// </summary>
    [JsonPropertyName("column_model_id")]
    public string? ColumnModelId { get; init; }

    /// <summary>
    /// The column model strategy.
    /// </summary>
    [JsonPropertyName("column_model_strategy")]
    public string? ColumnModelStrategy { get; init; }

    /// <summary>
    /// The global column identifier.
    /// </summary>
    [JsonPropertyName("global_column_id")]
    public string? GlobalColumnId { get; init; }

    /// <summary>
    /// The numeric column unit settings.
    /// </summary>
    [JsonPropertyName("unit")]
    public string? Unit { get; init; }

}
