// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A source that was on the deleted data view but was not restored with it.
/// </summary>
public sealed partial class DataViewRestoreDroppedSource
{
    /// <summary>
    /// The identifier of the source that was dropped.
    /// </summary>
    [JsonPropertyName("source_id")]
    public DataViewSourceId? SourceId { get; init; }

    /// <summary>
    /// Why the source was dropped.
    /// </summary>
    [JsonPropertyName("reason")]
    public DataViewRestoreDroppedReason? Reason { get; init; }

}
