// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The authorization object associated with a data view.
/// </summary>
public sealed partial class DataViewAuthorizationObject
{
    /// <summary>
    /// The identifier of the authorization object.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The type of the authorization object.
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

}
