// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A mapping between a source column and a target column.
/// </summary>
public sealed partial class DataViewColumnMapping
{
    /// <summary>
    /// The source column identifier.
    /// </summary>
    [JsonPropertyName("source_column_id")]
    public string? SourceColumnId { get; init; }

    /// <summary>
    /// The target column identifier.
    /// </summary>
    [JsonPropertyName("target_column_id")]
    public string? TargetColumnId { get; init; }

}
