// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The counts behind a sources limit failure.
/// </summary>
public sealed partial class DataViewValidationLimitDetails
{
    /// <summary>
    /// The maximum number of sources allowed for this account.
    /// </summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    /// <summary>
    /// The number of sources already on the data view.
    /// </summary>
    [JsonPropertyName("current")]
    public int? Current { get; init; }

    /// <summary>
    /// The number of sources the caller asked to add.
    /// </summary>
    [JsonPropertyName("requested")]
    public int? Requested { get; init; }

}
