// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The outcome of a data view validation check.
/// </summary>
public sealed partial class DataViewValidationResult
{
    /// <summary>
    /// Whether the validation passed.
    /// </summary>
    [JsonPropertyName("valid")]
    public bool? Valid { get; init; }

    /// <summary>
    /// Present only when `valid` is false.
    /// </summary>
    [JsonPropertyName("invalid_result")]
    public DataViewValidationFailure? InvalidResult { get; init; }

}
