// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The resolved structure of a single data view source.
/// </summary>
public sealed partial class DataViewStructureSource
{
    /// <summary>
    /// The source identifier.
    /// </summary>
    [JsonPropertyName("source_id")]
    public DataViewSourceId? SourceId { get; init; }

    /// <summary>
    /// How this source is grouped.
    /// </summary>
    [JsonPropertyName("source_kind")]
    public DataViewStructureSourceKind? SourceKind { get; init; }

    /// <summary>
    /// The boards implementing this entity. Present only when source_kind is ENTITY.
    /// </summary>
    [JsonPropertyName("managed_board_ids")]
    public List<string>? ManagedBoardIds { get; init; }

    /// <summary>
    /// Only the source columns that are mapped into the target. Fields the structure lookup does not resolve — such as archived, description and the column model fields — are always null here.
    /// </summary>
    [JsonPropertyName("columns")]
    public List<DataViewColumn>? Columns { get; init; }

    /// <summary>
    /// The column mappings for this source.
    /// </summary>
    [JsonPropertyName("mappings")]
    public List<DataViewColumnMapping>? Mappings { get; init; }

}
