// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Represents a document block that was successfully deleted.
/// </summary>
public sealed partial class DeletedDocBlock
{
    /// <summary>
    /// The deleted block's unique identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

}
