// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response indicating whether the planner resource deletion succeeded
/// </summary>
public sealed partial class DeletePlannerResourceResponse
{
    /// <summary>
    /// Indicates whether the resource was successfully deleted.
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; init; }

    /// <summary>
    /// The ID of the resource that was targeted for deletion.
    /// </summary>
    [JsonPropertyName("resource_id")]
    public string ResourceId { get; init; } = null!;

    /// <summary>
    /// Number of allocation items that were deleted.
    /// </summary>
    [JsonPropertyName("deleted_allocation_count")]
    public int DeletedAllocationCount { get; init; }

}
