// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result containing dependency column configurations for a board
/// </summary>
public sealed partial class DependencyColumnConfigResult
{
    /// <summary>
    /// The ID of the board
    /// </summary>
    [JsonPropertyName("board_id")]
    public string? BoardId { get; init; }

    /// <summary>
    /// Array of dependency column configurations
    /// </summary>
    [JsonPropertyName("dependency_columns")]
    public List<DependencyColumnConfig>? DependencyColumns { get; init; }

}
