// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Configuration record for a dependency column
/// </summary>
public sealed partial class DependencyColumnConfig
{
    /// <summary>
    /// The ID of the configuration record
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The account ID
    /// </summary>
    [JsonPropertyName("account_id")]
    public string? AccountId { get; init; }

    /// <summary>
    /// The board ID
    /// </summary>
    [JsonPropertyName("board_id")]
    public string? BoardId { get; init; }

    /// <summary>
    /// Configuration data containing mode and is_new_dependency
    /// </summary>
    [JsonPropertyName("data")]
    public string? Data { get; init; }

    /// <summary>
    /// Creation timestamp
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; init; }

    /// <summary>
    /// Last update timestamp
    /// </summary>
    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; init; }

    /// <summary>
    /// The type of configuration (always "dependency")
    /// </summary>
    [JsonPropertyName("config_type")]
    public string? ConfigType { get; init; }

}
