// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Effort hours per kind (allocated, planned, spent, available).
/// </summary>
public sealed partial class Effort
{
    /// <summary>
    /// Allocated effort hours.
    /// </summary>
    [JsonPropertyName("allocated")]
    public double? Allocated { get; init; }

    /// <summary>
    /// Planned effort hours.
    /// </summary>
    [JsonPropertyName("planned")]
    public double? Planned { get; init; }

    /// <summary>
    /// Spent effort hours.
    /// </summary>
    [JsonPropertyName("spent")]
    public double? Spent { get; init; }

    /// <summary>
    /// Available capacity hours.
    /// </summary>
    [JsonPropertyName("available")]
    public double? Available { get; init; }

}
