// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Email metadata for email-type timeline items.
/// </summary>
public sealed partial class EmailTimelineItemMetadata
{
    /// <summary>
    /// The email sender address.
    /// </summary>
    [JsonPropertyName("from")]
    public string? From { get; init; }

    /// <summary>
    /// List of recipient email addresses.
    /// </summary>
    [JsonPropertyName("to")]
    public List<string>? To { get; init; }

    /// <summary>
    /// List of CC email addresses.
    /// </summary>
    [JsonPropertyName("cc")]
    public List<string>? Cc { get; init; }

    /// <summary>
    /// List of BCC email addresses.
    /// </summary>
    [JsonPropertyName("bcc")]
    public List<string>? Bcc { get; init; }

}
