// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Status of an async board export job, including download URL when completed.
/// </summary>
public sealed partial class ExportJobStatusInfo
{
    /// <summary>
    /// Current job status. Terminal values: COMPLETED, FAILED, CANCELLED.
    /// </summary>
    [JsonPropertyName("status")]
    public ExportJobStatus? Status { get; init; }

    /// <summary>
    /// Presigned S3 download URL, available only when the job completed successfully and the URL has not yet expired. Returns null once expired — re-trigger the export to get a new one.
    /// </summary>
    [JsonPropertyName("download_url")]
    public string? DownloadUrl { get; init; }

    /// <summary>
    /// Structured reason for failure. Populated only when the job failed.
    /// </summary>
    [JsonPropertyName("failure_reason")]
    public ExportFailureReason? FailureReason { get; init; }

    /// <summary>
    /// Human-readable error detail. Populated only when the job failed and the reason exposes safe text.
    /// </summary>
    [JsonPropertyName("failure_message")]
    public string? FailureMessage { get; init; }

}
