// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Reference to a started async board export. Use the job_id with fetch_export_job_status to poll until COMPLETED or FAILED.
/// </summary>
public sealed partial class ExportAsyncJob
{
    /// <summary>
    /// Opaque identifier for this export job. Pass to fetch_export_job_status.
    /// </summary>
    [JsonPropertyName("job_id")]
    public string? JobId { get; init; }

}
