// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of a single operation
/// </summary>
public sealed partial class ExtendTrialPeriod
{
    /// <summary>
    /// Account slug
    /// </summary>
    [JsonPropertyName("account_slug")]
    public string AccountSlug { get; init; } = null!;

    /// <summary>
    /// Reason of an error
    /// </summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }

    /// <summary>
    /// Result of a single operation
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; init; }

}
