// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Information about a failed team board role update, including the team ID and the error encountered.
/// </summary>
public sealed partial class FailedTeamBoardRoleUpdate
{
    /// <summary>
    /// The error message describing why the role update failed.
    /// </summary>
    [JsonPropertyName("error")]
    public string Error { get; init; } = null!;

    /// <summary>
    /// The ID of the team whose board role update failed.
    /// </summary>
    [JsonPropertyName("team_id")]
    public string TeamId { get; init; } = null!;

}
