// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A workspace folder containing boards, docs, sub folders, etc.
/// </summary>
public sealed partial class Folder
{
    /// <summary>
    /// The folder's app feature slug (folders 2.0)
    /// </summary>
    [JsonPropertyName("app_feature_slug")]
    public string? AppFeatureSlug { get; init; }

    /// <summary>
    /// The various items in the folder, not including sub-folders and dashboards.
    /// </summary>
    [JsonPropertyName("children")]
    public List<Board> Children { get; init; } = [];

    /// <summary>
    /// The folder's color.
    /// </summary>
    [JsonPropertyName("color")]
    public FolderColor? Color { get; init; }

    /// <summary>
    /// The folder's creation date.
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly CreatedAt { get; init; }

    /// <summary>
    /// The folder's custom icon.
    /// </summary>
    [JsonPropertyName("custom_icon")]
    public FolderCustomIcon? CustomIcon { get; init; }

    /// <summary>
    /// The folder's font weight.
    /// </summary>
    [JsonPropertyName("font_weight")]
    public FolderFontWeight? FontWeight { get; init; }

    /// <summary>
    /// The folder's unique identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The folder's name.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The folder's user owner unique identifier.
    /// </summary>
    [JsonPropertyName("owner_id")]
    public string? OwnerId { get; init; }

    /// <summary>
    /// The folder's parent folder.
    /// </summary>
    [JsonPropertyName("parent")]
    public Folder? Parent { get; init; }

    /// <summary>
    /// Sub-folders inside this folder.
    /// </summary>
    [JsonPropertyName("sub_folders")]
    public List<Folder> SubFolders { get; init; } = [];

    /// <summary>
    /// The workspace that contains this folder (null id for main workspace).
    /// </summary>
    [JsonPropertyName("workspace")]
    public Workspace Workspace { get; init; } = null!;

}
