// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Object containing typography and text styling configuration.
/// </summary>
public sealed partial class FormText
{
    /// <summary>
    /// String specifying the font family used throughout the form.
    /// </summary>
    [JsonPropertyName("font")]
    public string? Font { get; init; }

    /// <summary>
    /// Hex color code for the text color in the form.
    /// </summary>
    [JsonPropertyName("color")]
    public string? Color { get; init; }

    /// <summary>
    /// String or number specifying the base font size for form text.
    /// </summary>
    [JsonPropertyName("size")]
    public FormFontSize? Size { get; init; }

}
