// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class FormRequireLogin
{
    /// <summary>
    /// Boolean requiring users to be logged in before submitting responses.
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

    /// <summary>
    /// Boolean automatically redirecting unauthenticated users to the login page.
    /// </summary>
    [JsonPropertyName("redirectToLogin")]
    public bool RedirectToLogin { get; init; }

}
