// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class FormQuestionOption
{
    /// <summary>
    /// The display text for individual option choices in select-type questions.
    /// </summary>
    [JsonPropertyName("label")]
    public string Label { get; init; } = null!;

    /// <summary>
    /// The internal unique identifier for a select option. Used as the option ID in CRUD operations.
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// Integer specifying the display order of this option within the question (zero-based).
    /// </summary>
    [JsonPropertyName("position")]
    public int? Position { get; init; }

    /// <summary>
    /// Boolean controlling whether this option is visible to respondents.
    /// </summary>
    [JsonPropertyName("visible")]
    public bool? Visible { get; init; }

    /// <summary>
    /// Boolean indicating whether this option is active and available for selection.
    /// </summary>
    [JsonPropertyName("active")]
    public bool? Active { get; init; }

}
