// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Object containing logo display configuration for form branding.
/// </summary>
public sealed partial class FormLogo
{
    /// <summary>
    /// String specifying logo placement ("top", "bottom", "header").
    /// </summary>
    [JsonPropertyName("position")]
    public FormLogoPosition? Position { get; init; }

    /// <summary>
    /// URL pointing to the logo image file for display on the form.
    /// </summary>
    [JsonPropertyName("url")]
    public string? Url { get; init; }

    /// <summary>
    /// String specifying logo size ("small", "medium", "large") for the logo that appears on the header of the form.
    /// </summary>
    [JsonPropertyName("size")]
    public FormLogoSize? Size { get; init; }

}
