// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The result of a successful form submission.
/// </summary>
public sealed partial class FormSubmissionResult
{
    /// <summary>
    /// The unique identifier of the created submission.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

}
