// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Represents an item in favorites
/// </summary>
public sealed partial class GraphqlHierarchyObjectItem
{
    /// <summary>
    /// The unique identifier of the hierarchy item
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The account identifier this item belongs to
    /// </summary>
    [JsonPropertyName("accountId")]
    public string? AccountId { get; init; }

    /// <summary>
    /// The object identifier and type
    /// </summary>
    [JsonPropertyName("object")]
    public HierarchyObjectID? @Object { get; init; }

    /// <summary>
    /// The folder identifier if the item is contained within a folder
    /// </summary>
    [JsonPropertyName("folderId")]
    public string? FolderId { get; init; }

    /// <summary>
    /// The position of the item within its list or folder
    /// </summary>
    [JsonPropertyName("position")]
    public double? Position { get; init; }

    /// <summary>
    /// The timestamp when this item was created
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// The timestamp when this item was last updated
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateOnly? UpdatedAt { get; init; }

}
