// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A grouped entity and its event count
/// </summary>
public sealed partial class GroupCountBucket
{
    /// <summary>
    /// The grouped entity ID (board ID or user ID, depending on group_by)
    /// </summary>
    [JsonPropertyName("key")]
    public string? Key { get; init; }

    /// <summary>
    /// Number of events for this entity within the filtered range
    /// </summary>
    [JsonPropertyName("count")]
    public int? Count { get; init; }

}
