// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Content for an image block
/// </summary>
public sealed partial class ImageContent : DocBaseBlockContent
{
    /// <summary>
    /// The alignment of the block content
    /// </summary>
    [JsonPropertyName("alignment")]
    public BlockAlignment? Alignment { get; init; }

    /// <summary>
    /// The text direction of the block content
    /// </summary>
    [JsonPropertyName("direction")]
    public BlockDirection? Direction { get; init; }

    /// <summary>
    /// The public URL of the image
    /// </summary>
    [JsonPropertyName("public_url")]
    public string PublicUrl { get; init; } = null!;

    /// <summary>
    /// The width of the image
    /// </summary>
    [JsonPropertyName("width")]
    public int? Width { get; init; }

}
