// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of installing an app from a public template link
/// </summary>
public sealed partial class InstallFromPublicTemplateLinkResult
{
    /// <summary>
    /// The ID of the newly created app
    /// </summary>
    [JsonPropertyName("ai_app_id")]
    public string? AiAppId { get; init; }

    /// <summary>
    /// The number of boards included in the installed template
    /// </summary>
    [JsonPropertyName("boards_count")]
    public int? BoardsCount { get; init; }

}
