// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Intelligence data.
/// </summary>
public sealed partial class Intelligence
{
    /// <summary>
    /// Top visited boards ranked by relevance (frequency + recency).
    /// </summary>
    [JsonPropertyName("relevant_boards")]
    public List<RelevantBoard>? RelevantBoards { get; init; }

    /// <summary>
    /// Top related users ranked by relevance (multi-signal frequency + recency).
    /// </summary>
    [JsonPropertyName("relevant_people")]
    public List<RelevantPerson>? RelevantPeople { get; init; }

    /// <summary>
    /// User and account context information.
    /// </summary>
    [JsonPropertyName("context")]
    public UserContextResponse? Context { get; init; }

    /// <summary>
    /// Boards where the user has item assignments.
    /// </summary>
    [JsonPropertyName("assigned_boards")]
    public List<AssignedBoard>? AssignedBoards { get; init; }

}
