// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Paginated result set returned by the items_page query
/// </summary>
public sealed partial class ItemsPageResult
{
    /// <summary>
    /// Opaque pagination token, null if no more pages
    /// </summary>
    [JsonPropertyName("cursor")]
    public string? Cursor { get; init; }

    /// <summary>
    /// The items in this page of results
    /// </summary>
    [JsonPropertyName("items")]
    public List<ItemResult>? Items { get; init; }

    /// <summary>
    /// Linked items (relations, dependencies, subitems from other boards)
    /// </summary>
    [JsonPropertyName("linked_items")]
    public List<ItemResult>? LinkedItems { get; init; }

}
