// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The value of a dropdown column.
/// </summary>
public sealed partial class ItemsPageDropdownValue : ItemsPageColumnValue
{
    /// <summary>
    /// Column ID
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Column type
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// Stringified text representation
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; }

    /// <summary>
    /// JSON string value matching old API format
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// Selected dropdown options with resolved labels
    /// </summary>
    [JsonPropertyName("values")]
    public List<ItemsPageDropdownValueOption> Values { get; init; } = [];

}
