// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A single item returned by the items_page query
/// </summary>
public sealed partial class ItemResult
{
    /// <summary>
    /// The unique identifier of the item
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The name of the item
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// The state of the item (active, deleted, etc.)
    /// </summary>
    [JsonPropertyName("state")]
    public string? State { get; init; }

    /// <summary>
    /// The ID of the group this item belongs to
    /// </summary>
    [JsonPropertyName("group_id")]
    public string? GroupId { get; init; }

    /// <summary>
    /// ISO 8601 timestamp of when the item was created
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; init; }

    /// <summary>
    /// ISO 8601 timestamp of when the item was last updated
    /// </summary>
    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; init; }

    /// <summary>
    /// Structured column values
    /// </summary>
    [JsonPropertyName("column_values")]
    public List<ItemsPageColumnValue>? ColumnValues { get; init; }

    /// <summary>
    /// Subitems of this item
    /// </summary>
    [JsonPropertyName("subitems")]
    public List<ItemResult>? Subitems { get; init; }

}
