// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The rollup value of a status column on a multi-level board: a distribution of status counts.
/// </summary>
public sealed partial class ItemsPageBatteryValue : ItemsPageColumnValue
{
    /// <summary>
    /// Column ID
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Column type
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// Stringified text representation
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; }

    /// <summary>
    /// JSON string value matching old API format
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// Multi-level boards: whether this item is a leaf (has no subitems).
    /// </summary>
    [JsonPropertyName("is_leaf")]
    public bool IsLeaf { get; init; }

    /// <summary>
    /// Column capabilities (calculated/rollup metadata on multi-level boards).
    /// </summary>
    [JsonPropertyName("capabilities")]
    public ItemsPageColumnCapabilities? Capabilities { get; init; }

    /// <summary>
    /// Per-status counts aggregated across the item and its subitems.
    /// </summary>
    [JsonPropertyName("battery_value")]
    public List<ItemsPageBatteryValueItem> BatteryValue { get; init; } = [];

}
