// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The value of a last updated column.
/// </summary>
public sealed partial class ItemsPageLastUpdatedValue : ItemsPageColumnValue
{
    /// <summary>
    /// Column ID
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Column type
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// Stringified text representation
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; }

    /// <summary>
    /// JSON string value matching old API format
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// ISO timestamp of last update
    /// </summary>
    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; init; }

    /// <summary>
    /// ID of the user who last updated the item
    /// </summary>
    [JsonPropertyName("updater_id")]
    public string? UpdaterId { get; init; }

}
