// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The value of a rating column.
/// </summary>
public sealed partial class ItemsPageRatingValue : ItemsPageColumnValue
{
    /// <summary>
    /// Column ID
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Column type
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// Stringified text representation
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; }

    /// <summary>
    /// JSON string value matching old API format
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// Rating value
    /// </summary>
    [JsonPropertyName("rating")]
    public int? Rating { get; init; }

}
