// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class ManagedColumn
{
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    [JsonPropertyName("title")]
    public string? Title { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("settings_json")]
    public string? SettingsJson { get; init; }

    [JsonPropertyName("created_by")]
    public string? CreatedBy { get; init; }

    [JsonPropertyName("updated_by")]
    public string? UpdatedBy { get; init; }

    [JsonPropertyName("revision")]
    public int? Revision { get; init; }

    [JsonPropertyName("state")]
    public ManagedColumnState? State { get; init; }

    /// <summary>
    /// The date and time of creation.
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// The date and time of the last update.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

    [JsonPropertyName("settings")]
    public ColumnSettings? Settings { get; init; }

}
