// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class MarketplaceAppDiscount
{
    /// <summary>
    /// Slug of an account
    /// </summary>
    [JsonPropertyName("account_slug")]
    public string AccountSlug { get; init; } = null!;

    /// <summary>
    /// The ID of an account
    /// </summary>
    [JsonPropertyName("account_id")]
    public string AccountId { get; init; } = null!;

    /// <summary>
    /// Percentage value of a discount
    /// </summary>
    [JsonPropertyName("discount")]
    public int Discount { get; init; }

    /// <summary>
    /// Is discount recurring
    /// </summary>
    [JsonPropertyName("is_recurring")]
    public bool IsRecurring { get; init; }

    /// <summary>
    /// List of app plan ids
    /// </summary>
    [JsonPropertyName("app_plan_ids")]
    public List<string> AppPlanIds { get; init; } = [];

    [JsonPropertyName("period")]
    public DiscountPeriod? Period { get; init; }

    /// <summary>
    /// Date until a discount is valid
    /// </summary>
    [JsonPropertyName("valid_until")]
    public string ValidUntil { get; init; } = null!;

    /// <summary>
    /// Date when a discount was created
    /// </summary>
    [JsonPropertyName("created_at")]
    public string CreatedAt { get; init; } = null!;

}
