// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A cursor-paginated page of messages, ordered newest-first.
/// </summary>
public sealed partial class MessagesPage
{
    /// <summary>
    /// Messages in this page, ordered newest-first.
    /// </summary>
    [JsonPropertyName("messages")]
    public List<Message>? Messages { get; init; }

    /// <summary>
    /// Pass as the cursor argument in a subsequent request to fetch the next (older) page. Null when there are no more messages.
    /// </summary>
    [JsonPropertyName("cursor")]
    public string? Cursor { get; init; }

}
