// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Context data for Monday agents
/// </summary>
public sealed partial class MondayAgentsContextData
{
    /// <summary>
    /// Display name of the block in the agents context
    /// </summary>
    [JsonPropertyName("block_name")]
    public string? BlockName { get; init; }

    /// <summary>
    /// Keys of fields that should be hidden in the agents context
    /// </summary>
    [JsonPropertyName("hidden_field_keys")]
    public List<string>? HiddenFieldKeys { get; init; }

}
