// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Root mutation type for the Dependencies service
/// </summary>
public sealed partial class Mutation
{
    /// <summary>
    /// Update attributes (Job Role, Skills, or Location) for multiple resources in the directory
    /// </summary>
    [JsonPropertyName("update_directory_resources_attributes")]
    public UpdateDirectoryResourceAttributesResponse? UpdateDirectoryResourcesAttributes { get; init; }

    /// <summary>
    /// Create managed column of type dropdown mutation.
    /// </summary>
    [JsonPropertyName("create_dropdown_managed_column")]
    public DropdownManagedColumn? CreateDropdownManagedColumn { get; init; }

    /// <summary>
    /// Create managed column of type status mutation.
    /// </summary>
    [JsonPropertyName("create_status_managed_column")]
    public StatusManagedColumn? CreateStatusManagedColumn { get; init; }

    /// <summary>
    /// Update managed column of type dropdown mutation.
    /// </summary>
    [JsonPropertyName("update_dropdown_managed_column")]
    public DropdownManagedColumn? UpdateDropdownManagedColumn { get; init; }

    /// <summary>
    /// Update managed column of type status mutation.
    /// </summary>
    [JsonPropertyName("update_status_managed_column")]
    public StatusManagedColumn? UpdateStatusManagedColumn { get; init; }

    /// <summary>
    /// Activate managed column mutation.
    /// </summary>
    [JsonPropertyName("activate_managed_column")]
    public ManagedColumn? ActivateManagedColumn { get; init; }

    /// <summary>
    /// Deactivate managed column mutation.
    /// </summary>
    [JsonPropertyName("deactivate_managed_column")]
    public ManagedColumn? DeactivateManagedColumn { get; init; }

    /// <summary>
    /// Delete managed column mutation.
    /// </summary>
    [JsonPropertyName("delete_managed_column")]
    public ManagedColumn? DeleteManagedColumn { get; init; }

    /// <summary>
    /// Updates a status column's properties including title, description, and status label settings. Status columns allow users to track item progress through customizable labels (e.g., "Working on it", "Done", "Stuck"). This mutation is specifically for status/color columns and provides type-safe updates.
    /// </summary>
    [JsonPropertyName("update_status_column")]
    public Column? UpdateStatusColumn { get; init; }

    /// <summary>
    /// Updates a dropdown column's properties including title, description, and dropdown label settings. Dropdown columns allow users to select from a predefined list of options. This mutation is specifically for dropdown columns and provides type-safe updates.
    /// </summary>
    [JsonPropertyName("update_dropdown_column")]
    public Column? UpdateDropdownColumn { get; init; }

    /// <summary>
    /// Generic mutation for updating any column type with validation. Supports updating column properties like title, description, and type-specific defaults/settings. The mutation validates input against the column type's schema before applying changes. Use get_column_type_schema query to understand available properties for each column type.
    /// </summary>
    [JsonPropertyName("update_column")]
    public Column? UpdateColumn { get; init; }

    /// <summary>
    /// Creates a new status column with strongly typed settings. Status columns allow users to track item progress through customizable labels (e.g., "Working on it", "Done", "Stuck"). This mutation is specifically for status/color columns and provides type-safe creation with label configuration.
    /// </summary>
    [JsonPropertyName("create_status_column")]
    public Column? CreateStatusColumn { get; init; }

    /// <summary>
    /// Creates a new dropdown column with strongly typed settings. Dropdown columns allow users to select from a predefined list of options. This mutation is specifically for dropdown columns and provides type-safe creation with dropdown options configuration.
    /// </summary>
    [JsonPropertyName("create_dropdown_column")]
    public Column? CreateDropdownColumn { get; init; }

    /// <summary>
    /// Generic mutation for creating any column type with validation. Supports creating column with properties like title, description, and type-specific defaults/settings. The mutation validates input against the column type's schema before applying changes. Use get_column_type_schema query to understand available properties for each column type.
    /// </summary>
    [JsonPropertyName("create_column")]
    public Column? CreateColumn { get; init; }

    /// <summary>
    /// Creates a new status column in a board that is linked to a managed column. The column data and settings are controlled by the managed column. Only title and description can be overridden locally.
    /// </summary>
    [JsonPropertyName("attach_status_managed_column")]
    public Column? AttachStatusManagedColumn { get; init; }

    /// <summary>
    /// Creates a new dropdown column in a board that is linked to a managed column. The column data and settings are controlled by the managed column. Title, description, and dropdown-specific settings (limit_select, label_limit_count) can be overridden locally.
    /// </summary>
    [JsonPropertyName("attach_dropdown_managed_column")]
    public Column? AttachDropdownManagedColumn { get; init; }

    /// <summary>
    /// Create a new account object schema.
    /// </summary>
    [JsonPropertyName("create_object_schema")]
    public ObjectSchema? CreateObjectSchema { get; init; }

    /// <summary>
    /// Update an account object schema.
    /// </summary>
    [JsonPropertyName("update_object_schema")]
    public ObjectSchema? UpdateObjectSchema { get; init; }

    /// <summary>
    /// Delete an account object schema. Can only delete if there are no boards attached to the object schema. Object schemas define the structure and columns of boards.
    /// </summary>
    [JsonPropertyName("delete_object_schema")]
    public ObjectSchema? DeleteObjectSchema { get; init; }

    /// <summary>
    /// Connect a board to an object schema.
    /// </summary>
    [JsonPropertyName("connect_board_to_object_schema")]
    public BoardConnection? ConnectBoardToObjectSchema { get; init; }

    /// <summary>
    /// Create columns on an account object schema.
    /// </summary>
    [JsonPropertyName("create_object_schema_columns")]
    public ObjectSchema? CreateObjectSchemaColumns { get; init; }

    /// <summary>
    /// Deactivate or reactivate a column on an account object schema.
    /// </summary>
    [JsonPropertyName("set_object_schema_column_active_state")]
    public ObjectSchema? SetObjectSchemaColumnActiveState { get; init; }

    /// <summary>
    /// Detach boards from their object schemas.
    /// </summary>
    [JsonPropertyName("detach_boards_from_object_schema")]
    public List<BulkDetachBoardResult>? DetachBoardsFromObjectSchema { get; init; }

    /// <summary>
    /// Update columns on an account object schema.
    /// </summary>
    [JsonPropertyName("update_object_schema_columns")]
    public ObjectSchema? UpdateObjectSchemaColumns { get; init; }

    /// <summary>
    /// Execute multiple object schema column actions in a single request. Actions are executed sequentially in the order provided. If any action fails, execution stops and an error is returned.
    /// </summary>
    [JsonPropertyName("bulk_object_schema_column_actions")]
    public List<ObjectSchemaActionResult>? BulkObjectSchemaColumnActions { get; init; }

    /// <summary>
    /// Add workspace object to favorites
    /// </summary>
    [JsonPropertyName("create_favorite")]
    public CreateFavoriteResultType? CreateFavorite { get; init; }

    /// <summary>
    /// Remove an object from favorites
    /// </summary>
    [JsonPropertyName("delete_favorite")]
    public DeleteFavoriteInputResultType? DeleteFavorite { get; init; }

    /// <summary>
    /// Update the position of an object in favorites
    /// </summary>
    [JsonPropertyName("update_favorite_position")]
    public UpdateFavoriteResultType? UpdateFavoritePosition { get; init; }

    /// <summary>
    /// Creates a new object in the Monday.com Objects Platform. The type of object created is determined by the object_type_unique_key parameter. This mutation can create boards, docs, dashboards, workflows, or specialized objects like CRM, capacity manager, etc. Under the hood, this creates a board with the corresponding app_feature_id.
    /// </summary>
    [JsonPropertyName("create_object")]
    public Object? CreateObject { get; init; }

    /// <summary>
    /// Permanently deletes an object from the Monday.com Objects Platform. Unlike archiving, deletion is only reversible for 30 days and removes all associated data. This operation works for any object type including boards, docs, dashboards, workflows, and specialized objects (CRM, capacity manager, etc.). WARNING: This operation cannot be undone after 30 days.
    /// </summary>
    [JsonPropertyName("delete_object")]
    public Object? DeleteObject { get; init; }

    /// <summary>
    /// Archives an object in the Monday.com Objects Platform, changing its state to "archived" while preserving all data. Archived objects remain in the system but are hidden from regular views. This operation works for any object type including boards, docs, dashboards, workflows, and specialized objects (CRM, capacity manager, etc.). Under the hood, this archives the board that represents this object.
    /// </summary>
    [JsonPropertyName("archive_object")]
    public Object? ArchiveObject { get; init; }

    /// <summary>
    /// Adds users to an existing object as either subscribers or owners. Subscribers receive notifications about object changes, while owners have full control permissions. Works with any object type including boards, docs, dashboards, workflows, and specialized objects (CRM, capacity manager, etc.). Equivalent to the add_users_to_board mutation in the boards API.
    /// </summary>
    [JsonPropertyName("add_subscribers_to_object")]
    public Object? AddSubscribersToObject { get; init; }

    /// <summary>
    /// Updates an object.
    /// </summary>
    [JsonPropertyName("update_object")]
    public Object? UpdateObject { get; init; }

    /// <summary>
    /// Publishes object out of draft state. Returns {success: true} on success, {success: false} on failure.
    /// </summary>
    [JsonPropertyName("publish_object")]
    public ObjectOperationResponse? PublishObject { get; init; }

    /// <summary>
    /// Unpublishes object from public state back to draft state. Returns {success: true} on success, {success: false} on failure.
    /// </summary>
    [JsonPropertyName("unpublish_object")]
    public ObjectOperationResponse? UnpublishObject { get; init; }

    /// <summary>
    /// Create relations for an object
    /// </summary>
    [JsonPropertyName("create_object_relations")]
    public List<ObjectRelation>? CreateObjectRelations { get; init; }

    /// <summary>
    /// Delete a specific object relation or all relations for an object. Returns the number of relations deleted.
    /// </summary>
    [JsonPropertyName("delete_object_relation")]
    public int? DeleteObjectRelation { get; init; }

    /// <summary>
    /// Create a marketplace app discount
    /// </summary>
    [JsonPropertyName("create_marketplace_app_discount")]
    public CreateMarketplaceAppDiscountResult CreateMarketplaceAppDiscount { get; init; } = null!;

    [JsonPropertyName("delete_marketplace_app_discount")]
    public DeleteMarketplaceAppDiscountResult DeleteMarketplaceAppDiscount { get; init; } = null!;

    [JsonPropertyName("grant_marketplace_app_discount")]
    public GrantMarketplaceAppDiscountResult GrantMarketplaceAppDiscount { get; init; } = null!;

    /// <summary>
    /// Execute an integration block with the provided field values
    /// </summary>
    [JsonPropertyName("execute_integration_block")]
    public IntegrationExecutionResult? ExecuteIntegrationBlock { get; init; }

    /// <summary>
    /// Enroll multiple items to a single sequence. Maximum 50 items per request.
    /// </summary>
    [JsonPropertyName("enroll_items_to_sequence")]
    public EnrollToSequenceResult? EnrollItemsToSequence { get; init; }

    /// <summary>
    /// Convert an existing monday.com board into a project with enhanced project management capabilities. This mutation transforms a regular board by applying project-specific features and configurations through column mappings that define how existing board columns should be interpreted in the project context. The conversion process is asynchronous and returns a process_id for tracking completion. Optionally accepts a callback URL for notification when the conversion completes. Use this when you have an existing board with data that needs to be upgraded to a full project with advanced project management features like Resource Planner integration.
    /// </summary>
    [JsonPropertyName("convert_board_to_project")]
    public ConvertBoardToProjectResult? ConvertBoardToProject { get; init; }

    /// <summary>
    /// Create a new project in monday.com from scratch. This mutation initiates asynchronous project creation with comprehensive customization options including: privacy settings (private/public - share is currently not supported), optional companions like Resource Planner for enhanced project management capabilities, workspace assignment for organizational structure, folder placement for better organization, and template selection for predefined project structures. Since project creation is asynchronous, you can optionally provide a callback_url where the project ID will be sent via POST request once creation completes. The callback will receive: { is_success: boolean, process_id: string, project_id?: number }. Returns a process_id for tracking the creation request.
    /// </summary>
    [JsonPropertyName("create_project")]
    public CreateProjectResult? CreateProject { get; init; }

    /// <summary>
    /// Creates a new team.
    /// </summary>
    [JsonPropertyName("create_team")]
    public Team? CreateTeam { get; init; }

    /// <summary>
    /// Activates the specified users.
    /// </summary>
    [JsonPropertyName("activate_users")]
    public ActivateUsersResult? ActivateUsers { get; init; }

    /// <summary>
    /// Deactivates the specified users.
    /// </summary>
    [JsonPropertyName("deactivate_users")]
    public DeactivateUsersResult? DeactivateUsers { get; init; }

    /// <summary>
    /// Deletes the specified team.
    /// </summary>
    [JsonPropertyName("delete_team")]
    public Team? DeleteTeam { get; init; }

    /// <summary>
    /// Updates the role of the specified users.
    /// </summary>
    [JsonPropertyName("update_users_role")]
    public UpdateUsersRoleResult? UpdateUsersRole { get; init; }

    /// <summary>
    /// Assigns the specified users as owners of the specified team.
    /// </summary>
    [JsonPropertyName("assign_team_owners")]
    public AssignTeamOwnersResult? AssignTeamOwners { get; init; }

    /// <summary>
    /// Removes the specified users as owners of the specified team.
    /// </summary>
    [JsonPropertyName("remove_team_owners")]
    public RemoveTeamOwnersResult? RemoveTeamOwners { get; init; }

    /// <summary>
    /// Updates the email domain for the specified users.
    /// </summary>
    [JsonPropertyName("update_email_domain")]
    public UpdateEmailDomainResult? UpdateEmailDomain { get; init; }

    /// <summary>
    /// Updates attributes for users.
    /// </summary>
    [JsonPropertyName("update_multiple_users")]
    public UpdateUserAttributesResult? UpdateMultipleUsers { get; init; }

    /// <summary>
    /// Invite users to the account.
    /// </summary>
    [JsonPropertyName("invite_users")]
    public InviteUsersResult? InviteUsers { get; init; }

    /// <summary>
    /// Revokes all API tokens for a service user.
    /// </summary>
    [JsonPropertyName("revoke_service_user_tokens")]
    public bool? RevokeServiceUserTokens { get; init; }

    /// <summary>
    /// Revokes all existing tokens and generates a new API token for a service user.
    /// </summary>
    [JsonPropertyName("regenerate_service_user_token")]
    public string? RegenerateServiceUserToken { get; init; }

    /// <summary>
    /// Creates a new service user.
    /// </summary>
    [JsonPropertyName("create_service_user")]
    public CreateServiceUserResult? CreateServiceUser { get; init; }

    /// <summary>
    /// Update form properties including title, description, or question order.
    /// </summary>
    [JsonPropertyName("update_form")]
    public ResponseForm? UpdateForm { get; init; }

    /// <summary>
    /// Update form configuration including features, appearance, and accessibility options.
    /// </summary>
    [JsonPropertyName("update_form_settings")]
    public ResponseForm? UpdateFormSettings { get; init; }

    /// <summary>
    /// Create a new question within a form. Returns the created question with auto-generated ID.
    /// </summary>
    [JsonPropertyName("create_form_question")]
    public FormQuestion? CreateFormQuestion { get; init; }

    /// <summary>
    /// Update an existing question properties including title, type, or settings. Requires question ID.
    /// </summary>
    [JsonPropertyName("update_form_question")]
    public FormQuestion? UpdateFormQuestion { get; init; }

    /// <summary>
    /// Permanently remove a question from a form. This action cannot be undone.
    /// </summary>
    [JsonPropertyName("delete_question")]
    public bool? DeleteQuestion { get; init; }

    /// <summary>
    /// Activate a form to make it visible to users and accept new submissions.
    /// </summary>
    [JsonPropertyName("activate_form")]
    public bool? ActivateForm { get; init; }

    /// <summary>
    /// Deactivate a form to hide it from users and stop accepting submissions. Form data is preserved.
    /// </summary>
    [JsonPropertyName("deactivate_form")]
    public bool? DeactivateForm { get; init; }

    /// <summary>
    /// Shorten a URL for a form and store it in the form settings. Returns the shortened link object.
    /// </summary>
    [JsonPropertyName("shorten_form_url")]
    public FormShortenedLink? ShortenFormUrl { get; init; }

    /// <summary>
    /// Create a new tag for a form. Tags are used to categorize and track responses. (e.g. UTM tags)
    /// </summary>
    [JsonPropertyName("create_form_tag")]
    public FormTag? CreateFormTag { get; init; }

    /// <summary>
    /// Update an existing tag in a form
    /// </summary>
    [JsonPropertyName("update_form_tag")]
    public bool? UpdateFormTag { get; init; }

    /// <summary>
    /// Delete a tag from a form
    /// </summary>
    [JsonPropertyName("delete_form_tag")]
    public bool? DeleteFormTag { get; init; }

    /// <summary>
    /// Create a new form with specified configuration. Returns the created form with its unique token.
    /// </summary>
    [JsonPropertyName("create_form")]
    public DehydratedFormResponse? CreateForm { get; init; }

    /// <summary>
    /// Set a password on a form to restrict access. This will enable password protection for the form.
    /// </summary>
    [JsonPropertyName("set_form_password")]
    public ResponseForm? SetFormPassword { get; init; }

    /// <summary>
    /// Creates a new app with the specified configuration.
    /// </summary>
    [JsonPropertyName("create_app")]
    public CreateAppResponse? CreateApp { get; init; }

    /// <summary>
    /// Updates an existing app. If the app latest version is live, a new draft version is automatically created and updated.
    /// </summary>
    [JsonPropertyName("update_app")]
    public AppType? UpdateApp { get; init; }

    /// <summary>
    /// Update an app feature.
    /// </summary>
    [JsonPropertyName("update_app_feature")]
    public AppFeatureType? UpdateAppFeature { get; init; }

    /// <summary>
    /// Create a new app feature.
    /// </summary>
    [JsonPropertyName("create_app_feature")]
    public AppFeatureType? CreateAppFeature { get; init; }

    /// <summary>
    /// Update (or create) lifecycle subscriptions for an entity. This will soft delete all existing subscriptions for this entity_identifier and create new ones.
    /// </summary>
    [JsonPropertyName("update_app_lifecycle_subscription")]
    public List<LifecycleSubscriptionKind>? UpdateAppLifecycleSubscription { get; init; }

    /// <summary>
    /// Delete all lifecycle subscriptions for an entity. Returns true if deleted successfully or if no subscriptions exist.
    /// </summary>
    [JsonPropertyName("delete_app_lifecycle_subscription")]
    public bool? DeleteAppLifecycleSubscription { get; init; }

    /// <summary>
    /// Installs an app on the current account. Requires account admin permission.
    /// </summary>
    [JsonPropertyName("install_app")]
    public InstallAppResponse? InstallApp { get; init; }

    /// <summary>
    /// Uninstalls an app from the current account. Requires account admin permission.
    /// </summary>
    [JsonPropertyName("uninstall_app")]
    public AppDeletionResponse? UninstallApp { get; init; }

    /// <summary>
    /// Updates a notification setting's enabled status.
    /// </summary>
    [JsonPropertyName("update_notification_setting")]
    public List<NotificationSetting>? UpdateNotificationSetting { get; init; }

    /// <summary>
    /// Update mute notification settings for a board. Allows muting all notifications for all users, only for the current user, or setting mentions/assigns-only. Returns the updated mute state for the board. Requires appropriate permissions for muting all users.
    /// </summary>
    [JsonPropertyName("update_mute_board_settings")]
    public List<BoardMuteSettings>? UpdateMuteBoardSettings { get; init; }

    /// <summary>
    /// Add a file to a column value.
    /// </summary>
    [JsonPropertyName("add_file_to_column")]
    public Asset? AddFileToColumn { get; init; }

    /// <summary>
    /// Add a file to an update.
    /// </summary>
    [JsonPropertyName("add_file_to_update")]
    public Asset? AddFileToUpdate { get; init; }

    /// <summary>
    /// Add subscribers to a board.
    /// </summary>
    [JsonPropertyName("add_subscribers_to_board")]
    public List<User>? AddSubscribersToBoard { get; init; }

    /// <summary>
    /// Add teams subscribers to a board.
    /// </summary>
    [JsonPropertyName("add_teams_to_board")]
    public List<Team>? AddTeamsToBoard { get; init; }

    /// <summary>
    /// Add teams to a workspace.
    /// </summary>
    [JsonPropertyName("add_teams_to_workspace")]
    public List<Team>? AddTeamsToWorkspace { get; init; }

    /// <summary>
    /// Add subscribers to a board.
    /// </summary>
    [JsonPropertyName("add_users_to_board")]
    public List<User>? AddUsersToBoard { get; init; }

    /// <summary>
    /// Add users to team.
    /// </summary>
    [JsonPropertyName("add_users_to_team")]
    public ChangeTeamMembershipsResult? AddUsersToTeam { get; init; }

    /// <summary>
    /// Add users to a workspace.
    /// </summary>
    [JsonPropertyName("add_users_to_workspace")]
    public List<User>? AddUsersToWorkspace { get; init; }

    /// <summary>
    /// Archive a board.
    /// </summary>
    [JsonPropertyName("archive_board")]
    public Board? ArchiveBoard { get; init; }

    /// <summary>
    /// Archives a group in a specific board.
    /// </summary>
    [JsonPropertyName("archive_group")]
    public Group? ArchiveGroup { get; init; }

    /// <summary>
    /// Archive an item.
    /// </summary>
    [JsonPropertyName("archive_item")]
    public Item? ArchiveItem { get; init; }

    /// <summary>
    /// Extends trial period of an application to selected accounts
    /// </summary>
    [JsonPropertyName("batch_extend_trial_period")]
    public BatchExtendTrialPeriod? BatchExtendTrialPeriod { get; init; }

    /// <summary>
    /// Change a column's properties
    /// </summary>
    [JsonPropertyName("change_column_metadata")]
    public Column? ChangeColumnMetadata { get; init; }

    /// <summary>
    /// Change a column's title
    /// </summary>
    [JsonPropertyName("change_column_title")]
    public Column? ChangeColumnTitle { get; init; }

    /// <summary>
    /// Change an item's column value.
    /// </summary>
    [JsonPropertyName("change_column_value")]
    public Item? ChangeColumnValue { get; init; }

    /// <summary>
    /// Change an item's position.
    /// </summary>
    [JsonPropertyName("change_item_position")]
    public Item? ChangeItemPosition { get; init; }

    /// <summary>
    /// Changes the column values of a specific item.
    /// </summary>
    [JsonPropertyName("change_multiple_column_values")]
    public Item? ChangeMultipleColumnValues { get; init; }

    /// <summary>
    /// Change an item's column with simple value.
    /// </summary>
    [JsonPropertyName("change_simple_column_value")]
    public Item? ChangeSimpleColumnValue { get; init; }

    /// <summary>
    /// Clear an item's updates.
    /// </summary>
    [JsonPropertyName("clear_item_updates")]
    public Item? ClearItemUpdates { get; init; }

    /// <summary>
    /// Get the complexity data of your mutations.
    /// </summary>
    [JsonPropertyName("complexity")]
    public Complexity? Complexity { get; init; }

    /// <summary>
    /// Create a new board.
    /// </summary>
    [JsonPropertyName("create_board")]
    public Board? CreateBoard { get; init; }

    /// <summary>
    /// Create a new doc.
    /// </summary>
    [JsonPropertyName("create_doc")]
    public Document? CreateDoc { get; init; }

    /// <summary>
    /// Create new document block
    /// </summary>
    [JsonPropertyName("create_doc_block")]
    public DocumentBlock? CreateDocBlock { get; init; }

    /// <summary>
    /// Creates a folder in a specific workspace.
    /// </summary>
    [JsonPropertyName("create_folder")]
    public Folder? CreateFolder { get; init; }

    /// <summary>
    /// Creates a new group in a specific board.
    /// </summary>
    [JsonPropertyName("create_group")]
    public Group? CreateGroup { get; init; }

    /// <summary>
    /// Create a new item.
    /// </summary>
    [JsonPropertyName("create_item")]
    public Item? CreateItem { get; init; }

    /// <summary>
    /// Create a new notification.
    /// </summary>
    [JsonPropertyName("create_notification")]
    public Notification? CreateNotification { get; init; }

    /// <summary>
    /// Create a new tag or get it if it already exists.
    /// </summary>
    [JsonPropertyName("create_or_get_tag")]
    public Tag? CreateOrGetTag { get; init; }

    /// <summary>
    /// Create subitem.
    /// </summary>
    [JsonPropertyName("create_subitem")]
    public Item? CreateSubitem { get; init; }

    /// <summary>
    /// Create a new webhook.
    /// </summary>
    [JsonPropertyName("create_webhook")]
    public Webhook? CreateWebhook { get; init; }

    /// <summary>
    /// Create a new workspace.
    /// </summary>
    [JsonPropertyName("create_workspace")]
    public Workspace? CreateWorkspace { get; init; }

    /// <summary>
    /// Delete a board.
    /// </summary>
    [JsonPropertyName("delete_board")]
    public Board? DeleteBoard { get; init; }

    /// <summary>
    /// Delete a column.
    /// </summary>
    [JsonPropertyName("delete_column")]
    public Column? DeleteColumn { get; init; }

    /// <summary>
    /// Delete a document block
    /// </summary>
    [JsonPropertyName("delete_doc_block")]
    public DocumentBlockIdOnly? DeleteDocBlock { get; init; }

    /// <summary>
    /// Deletes a folder in a specific workspace.
    /// </summary>
    [JsonPropertyName("delete_folder")]
    public Folder? DeleteFolder { get; init; }

    /// <summary>
    /// Deletes a group in a specific board.
    /// </summary>
    [JsonPropertyName("delete_group")]
    public Group? DeleteGroup { get; init; }

    /// <summary>
    /// Delete an item.
    /// </summary>
    [JsonPropertyName("delete_item")]
    public Item? DeleteItem { get; init; }

    /// <summary>
    /// Remove subscribers from the board.
    /// </summary>
    [JsonPropertyName("delete_subscribers_from_board")]
    public List<User>? DeleteSubscribersFromBoard { get; init; }

    /// <summary>
    /// Remove team subscribers from the board.
    /// </summary>
    [JsonPropertyName("delete_teams_from_board")]
    public List<Team>? DeleteTeamsFromBoard { get; init; }

    /// <summary>
    /// Delete teams from a workspace.
    /// </summary>
    [JsonPropertyName("delete_teams_from_workspace")]
    public List<Team>? DeleteTeamsFromWorkspace { get; init; }

    /// <summary>
    /// Delete users from a workspace.
    /// </summary>
    [JsonPropertyName("delete_users_from_workspace")]
    public List<User>? DeleteUsersFromWorkspace { get; init; }

    /// <summary>
    /// Delete a new webhook.
    /// </summary>
    [JsonPropertyName("delete_webhook")]
    public Webhook? DeleteWebhook { get; init; }

    /// <summary>
    /// Delete workspace.
    /// </summary>
    [JsonPropertyName("delete_workspace")]
    public Workspace? DeleteWorkspace { get; init; }

    /// <summary>
    /// Duplicate a board.
    /// </summary>
    [JsonPropertyName("duplicate_board")]
    public BoardDuplication? DuplicateBoard { get; init; }

    /// <summary>
    /// Duplicate a group.
    /// </summary>
    [JsonPropertyName("duplicate_group")]
    public Group? DuplicateGroup { get; init; }

    /// <summary>
    /// Duplicate an item.
    /// </summary>
    [JsonPropertyName("duplicate_item")]
    public Item? DuplicateItem { get; init; }

    /// <summary>
    /// Increase operations counter
    /// </summary>
    [JsonPropertyName("increase_app_subscription_operations")]
    public AppSubscriptionOperationsCounter? IncreaseAppSubscriptionOperations { get; init; }

    /// <summary>
    /// Move an item to a different board.
    /// </summary>
    [JsonPropertyName("move_item_to_board")]
    public Item? MoveItemToBoard { get; init; }

    /// <summary>
    /// Move an item to a different group.
    /// </summary>
    [JsonPropertyName("move_item_to_group")]
    public Item? MoveItemToGroup { get; init; }

    /// <summary>
    /// Remove mock app subscription for the current account
    /// </summary>
    [JsonPropertyName("remove_mock_app_subscription")]
    public AppSubscription? RemoveMockAppSubscription { get; init; }

    /// <summary>
    /// Remove users from team.
    /// </summary>
    [JsonPropertyName("remove_users_from_team")]
    public ChangeTeamMembershipsResult? RemoveUsersFromTeam { get; init; }

    /// <summary>
    /// Set or update the board's permission to specified role. This concept is also
    ///   known as default board role, general access or board permission set.
    /// </summary>
    [JsonPropertyName("set_board_permission")]
    public SetBoardPermissionResponse? SetBoardPermission { get; init; }

    /// <summary>
    /// Set mock app subscription for the current account
    /// </summary>
    [JsonPropertyName("set_mock_app_subscription")]
    public AppSubscription? SetMockAppSubscription { get; init; }

    /// <summary>
    /// Update item column value by existing assets
    /// </summary>
    [JsonPropertyName("update_assets_on_item")]
    public Item? UpdateAssetsOnItem { get; init; }

    /// <summary>
    /// Update Board attribute.
    /// </summary>
    [JsonPropertyName("update_board")]
    public string? UpdateBoard { get; init; }

    /// <summary>
    /// Update a board's position, workspace, or account product.
    /// </summary>
    [JsonPropertyName("update_board_hierarchy")]
    public UpdateBoardHierarchyResult? UpdateBoardHierarchy { get; init; }

    /// <summary>
    /// Update a document block
    /// </summary>
    [JsonPropertyName("update_doc_block")]
    public DocumentBlock? UpdateDocBlock { get; init; }

    /// <summary>
    /// Updates a folder.
    /// </summary>
    [JsonPropertyName("update_folder")]
    public Folder? UpdateFolder { get; init; }

    /// <summary>
    /// Update an existing group.
    /// </summary>
    [JsonPropertyName("update_group")]
    public Group? UpdateGroup { get; init; }

    /// <summary>
    /// Update the position of a dashboard.
    /// </summary>
    [JsonPropertyName("update_overview_hierarchy")]
    public UpdateOverviewHierarchy? UpdateOverviewHierarchy { get; init; }

    /// <summary>
    /// Update an existing workspace.
    /// </summary>
    [JsonPropertyName("update_workspace")]
    public Workspace? UpdateWorkspace { get; init; }

    /// <summary>
    /// Use a template
    /// </summary>
    [JsonPropertyName("use_template")]
    public Template? UseTemplate { get; init; }

    /// <summary>
    /// Assigns members to a department.
    /// </summary>
    [JsonPropertyName("assign_department_members")]
    public AssignDepartmentMembersResult? AssignDepartmentMembers { get; init; }

    /// <summary>
    /// Clear users department
    /// </summary>
    [JsonPropertyName("clear_users_department")]
    public ClearUsersDepartmentResult? ClearUsersDepartment { get; init; }

    /// <summary>
    /// Assigns an owner to a department.
    /// </summary>
    [JsonPropertyName("assign_department_owner")]
    public AssignDepartmentOwnerResult? AssignDepartmentOwner { get; init; }

    /// <summary>
    /// Unassigns owners from a department.
    /// </summary>
    [JsonPropertyName("unassign_department_owners")]
    public UnassignDepartmentOwnerResult? UnassignDepartmentOwners { get; init; }

    /// <summary>
    /// Creates a new department.
    /// </summary>
    [JsonPropertyName("create_department")]
    public Department? CreateDepartment { get; init; }

    /// <summary>
    /// Updates a department.
    /// </summary>
    [JsonPropertyName("update_department")]
    public Department? UpdateDepartment { get; init; }

    /// <summary>
    /// Deletes a department.
    /// </summary>
    [JsonPropertyName("delete_department")]
    public Department? DeleteDepartment { get; init; }

    [JsonPropertyName("like_update")]
    public Update? LikeUpdate { get; init; }

    [JsonPropertyName("unlike_update")]
    public Update UnlikeUpdate { get; init; } = null!;

    [JsonPropertyName("delete_update")]
    public Update? DeleteUpdate { get; init; }

    [JsonPropertyName("edit_update")]
    public Update EditUpdate { get; init; } = null!;

    [JsonPropertyName("pin_to_top")]
    public Update PinToTop { get; init; } = null!;

    [JsonPropertyName("unpin_from_top")]
    public Update UnpinFromTop { get; init; } = null!;

    [JsonPropertyName("create_update")]
    public Update? CreateUpdate { get; init; }

    /// <summary>
    /// Asynchronously delete items on a board
    /// </summary>
    [JsonPropertyName("bulk_delete_items")]
    public BulkDeleteInit? BulkDeleteItems { get; init; }

    /// <summary>
    /// Asynchronously archive items on a board
    /// </summary>
    [JsonPropertyName("bulk_archive_items")]
    public BulkDeleteInit? BulkArchiveItems { get; init; }

    /// <summary>
    /// Initialize a backfill job for a board and group. Designed for data migrations with no side effects and a 20k row limit. Returns job ID and upload URL to begin the process.
    /// </summary>
    [JsonPropertyName("backfill_items")]
    public UploadJobInit? BackfillItems { get; init; }

    /// <summary>
    /// Initialize an ingest job for a board and group. Designed for ongoing integrations with full side effects and a 10k row limit. Returns job ID and upload URL to begin the process.
    /// </summary>
    [JsonPropertyName("ingest_items")]
    public UploadJobInit? IngestItems { get; init; }

    /// <summary>
    /// Undo a previously completed action, or cancel one still in flight
    /// </summary>
    [JsonPropertyName("undo_action")]
    public UndoResult? UndoAction { get; init; }

    /// <summary>
    /// Connect an existing project to a portfolio. When a callback_url is provided the mutation returns immediately with a process_id, and the result is POSTed to that URL once the operation completes. The callback payload is: { is_success: boolean, process_id: string, portfolio_item_id?: string }.
    /// </summary>
    [JsonPropertyName("connect_project_to_portfolio")]
    public ConnectProjectResult? ConnectProjectToPortfolio { get; init; }

    /// <summary>
    /// Create a new portfolio. When a callback_url is provided the mutation returns immediately with a process_id, and the portfolio_id is POSTed to that URL once the portfolio is actually created. The callback payload is: { is_success: boolean, process_id: string, portfolio_id?: number }.
    /// </summary>
    [JsonPropertyName("create_portfolio")]
    public CreatePortfolioResult? CreatePortfolio { get; init; }

    /// <summary>
    /// Create a new widget.
    /// </summary>
    [JsonPropertyName("create_widget")]
    public Widget? CreateWidget { get; init; }

    /// <summary>
    /// Delete an existing widget.
    /// </summary>
    [JsonPropertyName("delete_widget")]
    public bool? DeleteWidget { get; init; }

    /// <summary>
    /// Create a new dashboard.
    /// </summary>
    [JsonPropertyName("create_dashboard")]
    public Dashboard? CreateDashboard { get; init; }

    /// <summary>
    /// Update an existing dashboard.
    /// </summary>
    [JsonPropertyName("update_dashboard")]
    public Dashboard? UpdateDashboard { get; init; }

    /// <summary>
    /// Delete an existing dashboard.
    /// </summary>
    [JsonPropertyName("delete_dashboard")]
    public bool? DeleteDashboard { get; init; }

    /// <summary>
    /// Add a required column to a board
    /// </summary>
    [JsonPropertyName("add_required_column")]
    public RequiredColumns? AddRequiredColumn { get; init; }

    /// <summary>
    /// Remove a required column from a board
    /// </summary>
    [JsonPropertyName("remove_required_column")]
    public RequiredColumns? RemoveRequiredColumn { get; init; }

    /// <summary>
    /// Create a validation rule
    /// </summary>
    [JsonPropertyName("create_validation_rule")]
    public ValidationRule? CreateValidationRule { get; init; }

    /// <summary>
    /// Update a validation rule
    /// </summary>
    [JsonPropertyName("update_validation_rule")]
    public ValidationRule? UpdateValidationRule { get; init; }

    /// <summary>
    /// Delete a validation rule
    /// </summary>
    [JsonPropertyName("delete_validation_rule")]
    public ValidationRule? DeleteValidationRule { get; init; }

    /// <summary>
    /// Create a new table view
    /// </summary>
    [JsonPropertyName("create_view_table")]
    public BoardView? CreateViewTable { get; init; }

    /// <summary>
    /// Create a view
    /// </summary>
    [JsonPropertyName("create_view")]
    public BoardView? CreateView { get; init; }

    /// <summary>
    /// Update an existing board table view
    /// </summary>
    [JsonPropertyName("update_view_table")]
    public BoardView? UpdateViewTable { get; init; }

    /// <summary>
    /// Update an existing view
    /// </summary>
    [JsonPropertyName("update_view")]
    public BoardView? UpdateView { get; init; }

    /// <summary>
    /// Delete an existing board subset/view
    /// </summary>
    [JsonPropertyName("delete_view")]
    public BoardView? DeleteView { get; init; }

    [JsonPropertyName("create_timeline_item")]
    public TimelineItem? CreateTimelineItem { get; init; }

    [JsonPropertyName("delete_timeline_item")]
    public TimelineItem? DeleteTimelineItem { get; init; }

    [JsonPropertyName("create_custom_activity")]
    public CustomActivity? CreateCustomActivity { get; init; }

    [JsonPropertyName("delete_custom_activity")]
    public CustomActivity? DeleteCustomActivity { get; init; }

    /// <summary>
    /// Adds markdown content to an existing document by converting it into document blocks. Use this to append content to the end of a document or insert content after a specific block. The markdown will be parsed and converted into the appropriate document block types (text, headers, lists, etc.). Returns the IDs of the newly created blocks on success.
    /// </summary>
    [JsonPropertyName("add_content_to_doc_from_markdown")]
    public DocBlocksFromMarkdownResult? AddContentToDocFromMarkdown { get; init; }

    /// <summary>
    /// Creates a new article in the specified workspace. Optionally accepts a name and folder ID. Returns the created article metadata.
    /// </summary>
    [JsonPropertyName("create_article")]
    public ArticleMetadata? CreateArticle { get; init; }

    /// <summary>
    /// Creates multiple document blocks in a single operation for efficient content creation. Use this when adding substantial content like importing documents, creating structured content (articles, reports, guides), or building complex document sections. Supports all block types including text paragraphs, headers, bullet/numbered lists, images, tables, code blocks, and more. Much faster than creating blocks individually. Perfect for content migration, template creation, or generating documents from external data. Maximum 25 blocks per request.
    /// </summary>
    [JsonPropertyName("create_doc_blocks")]
    public List<DocumentBlockV2>? CreateDocBlocks { get; init; }

    /// <summary>
    /// Deletes an article with the specified object ID
    /// </summary>
    [JsonPropertyName("delete_article")]
    public ArticleMetadata? DeleteArticle { get; init; }

    /// <summary>
    /// Permanently deletes a document and all its content from the system. This action cannot be undone. The document will be removed from all user views and workspaces. Use with caution - ensure the document is no longer needed before deletion. Returns success status and the deleted document ID.
    /// </summary>
    [JsonPropertyName("delete_doc")]
    public string? DeleteDoc { get; init; }

    /// <summary>
    /// Deletes multiple document blocks in a single operation. Maximum 100 blocks per request.
    /// </summary>
    [JsonPropertyName("delete_doc_blocks")]
    public List<DeletedDocBlock>? DeleteDocBlocks { get; init; }

    /// <summary>
    /// Creates an exact copy of an existing document, including all content, structure, and formatting. Use this to create templates, backup documents before major changes, or create variations of existing documents. The duplicated document will have a new unique ID and can be modified independently. Returns the new document's ID on success.
    /// </summary>
    [JsonPropertyName("duplicate_doc")]
    public string? DuplicateDoc { get; init; }

    /// <summary>
    /// Imports HTML content as a new document by converting it into document blocks. The HTML will be parsed and converted into the appropriate document block types (text, headers, lists, etc.). Returns the ID of the newly created document on success.
    /// </summary>
    [JsonPropertyName("import_doc_from_html")]
    public ImportDocFromHtmlResult? ImportDocFromHtml { get; init; }

    /// <summary>
    /// Publishes an article with the specified object ID. Allows setting privacy level, target folder, and managing subscribers (users and teams). Returns the updated article metadata.
    /// </summary>
    [JsonPropertyName("publish_article")]
    public ArticleMetadata? PublishArticle { get; init; }

    /// <summary>
    /// Updates the content of a specific article block. The block must belong to a draft article that the user has permission to edit. Cannot update blocks of published articles.
    /// </summary>
    [JsonPropertyName("update_article_block")]
    public ArticleBlock? UpdateArticleBlock { get; init; }

    /// <summary>
    /// Update a document's name/title. Changes are applied immediately and visible to all users with access to the document.
    /// </summary>
    [JsonPropertyName("update_doc_name")]
    public string? UpdateDocName { get; init; }

    /// <summary>
    /// Sets an item description document's content with new markdown data. This mutation converts the provided markdown into document blocks and replaces the existing content of the item's description. Returns the IDs of the newly created blocks on success. Note: Markdown does not support text colors or background highlights. Any existing colored or highlighted text will be lost after replacement.
    /// </summary>
    [JsonPropertyName("set_item_description_content")]
    public DocBlocksFromMarkdownResult? SetItemDescriptionContent { get; init; }

    /// <summary>
    /// Update the dependency column for a specific pulse
    /// </summary>
    [JsonPropertyName("update_dependency_column")]
    public string UpdateDependencyColumn { get; init; } = null!;

    /// <summary>
    /// Batch update the dependency column values in a board. Limited to 50 items per batch.
    /// </summary>
    [JsonPropertyName("batch_update_dependency_column")]
    public string BatchUpdateDependencyColumn { get; init; } = null!;

}
