// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Serialized note resource payload.
/// </summary>
public sealed partial class NoteData
{
    /// <summary>
    /// The note id.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The note content.
    /// </summary>
    [JsonPropertyName("content")]
    public string? Content { get; init; }

    /// <summary>
    /// A shortened preview of the note content.
    /// </summary>
    [JsonPropertyName("content_preview")]
    public string? ContentPreview { get; init; }

    /// <summary>
    /// The user who created the note.
    /// </summary>
    [JsonPropertyName("user")]
    public User? User { get; init; }

    /// <summary>
    /// The account id where the note exists.
    /// </summary>
    [JsonPropertyName("account_id")]
    public string AccountId { get; init; } = null!;

    /// <summary>
    /// The note creation timestamp.
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// The note last update timestamp.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

    /// <summary>
    /// The note name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Whether the note is public.
    /// </summary>
    [JsonPropertyName("public")]
    public bool? @Public { get; init; }

}
