// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Serialized note timeline item.
/// </summary>
public sealed partial class Note
{
    /// <summary>
    /// The timeline item id of the note.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The timeline item type.
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// The item the note is associated with.
    /// </summary>
    [JsonPropertyName("item")]
    public Item? Item { get; init; }

    /// <summary>
    /// The board the note is associated with.
    /// </summary>
    [JsonPropertyName("board")]
    public Board? Board { get; init; }

    /// <summary>
    /// The user who created the note timeline item.
    /// </summary>
    [JsonPropertyName("user")]
    public User? User { get; init; }

    /// <summary>
    /// The note due date.
    /// </summary>
    [JsonPropertyName("due_date")]
    public DateOnly? DueDate { get; init; }

    /// <summary>
    /// The timeline item creation timestamp.
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// The timeline item last update timestamp.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

    /// <summary>
    /// Whether this note is a sample timeline item.
    /// </summary>
    [JsonPropertyName("is_sample")]
    public bool? IsSample { get; init; }

    /// <summary>
    /// The origin item id when relevant.
    /// </summary>
    [JsonPropertyName("origin_item_id")]
    public string? OriginItemId { get; init; }

    /// <summary>
    /// The note resource payload.
    /// </summary>
    [JsonPropertyName("data")]
    public NoteData? Data { get; init; }

}
