// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Content for a notice box block
/// </summary>
public sealed partial class NoticeBoxContent : DocBaseBlockContent
{
    /// <summary>
    /// The alignment of the block content
    /// </summary>
    [JsonPropertyName("alignment")]
    public BlockAlignment? Alignment { get; init; }

    /// <summary>
    /// The text direction of the block content
    /// </summary>
    [JsonPropertyName("direction")]
    public BlockDirection? Direction { get; init; }

    /// <summary>
    /// The theme of the notice box
    /// </summary>
    [JsonPropertyName("theme")]
    public NoticeBoxTheme Theme { get; init; }

}
