// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Represents notification settings configuration
/// </summary>
public sealed partial class NotificationSetting
{
    /// <summary>
    /// Notification setting kind
    /// </summary>
    [JsonPropertyName("kind")]
    public string? Kind { get; init; }

    /// <summary>
    /// Description of the notification setting
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Whether this setting is only configurable by admins
    /// </summary>
    [JsonPropertyName("is_for_admins_only")]
    public bool? IsForAdminsOnly { get; init; }

    /// <summary>
    /// Whether this setting is not applicable for guest users
    /// </summary>
    [JsonPropertyName("is_for_non_guests_only")]
    public bool? IsForNonGuestsOnly { get; init; }

    /// <summary>
    /// Available notification channels for this setting
    /// </summary>
    [JsonPropertyName("channels")]
    public List<NotificationSettingChannel> Channels { get; init; } = [];

}
