// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Tags applied to an object schema column indicating its status or behavior.
/// </summary>
public sealed partial class ObjectSchemaColumnTags
{
    /// <summary>
    /// Deprecation info with a start timestamp, if the column is deprecated.
    /// </summary>
    [JsonPropertyName("deprecated")]
    public string? Deprecated { get; init; }

    /// <summary>
    /// Opt-in by default info with an optional end timestamp.
    /// </summary>
    [JsonPropertyName("opt_in_by_default")]
    public string? OptInByDefault { get; init; }

    /// <summary>
    /// Whether this column is inherited from a parent object schema.
    /// </summary>
    [JsonPropertyName("inherited")]
    public bool? Inherited { get; init; }

}
