// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A delta operation with insert content and optional formatting attributes
/// </summary>
public sealed partial class Operation
{
    /// <summary>
    /// Content to insert - either text or blot object
    /// </summary>
    [JsonPropertyName("insert")]
    public InsertOps? Insert { get; init; }

    /// <summary>
    /// Optional formatting attributes (bold, italic, underline, strike, code, link, color, background)
    /// </summary>
    [JsonPropertyName("attributes")]
    public Attributes? Attributes { get; init; }

}
