// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A single option in a remote options list
/// </summary>
public sealed partial class Option
{
    /// <summary>
    /// The value of the option
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// The display title of the option
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// Optional icon to display alongside the option (e.g. { vibe, tooltip })
    /// </summary>
    [JsonPropertyName("icon")]
    public string? Icon { get; init; }

}
