// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Cursor-paginated result for connected boards query.
/// </summary>
public sealed partial class PaginatedConnectedBoards
{
    /// <summary>
    /// Total number of connected boards across all requested columns.
    /// </summary>
    [JsonPropertyName("total")]
    public int? Total { get; init; }

    /// <summary>
    /// Cursor for the next page. Null if no more results.
    /// </summary>
    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; init; }

    /// <summary>
    /// The current page of connected board entries.
    /// </summary>
    [JsonPropertyName("page")]
    public List<BoardRelationConnectedBoardsResult>? Page { get; init; }

    /// <summary>
    /// Target schema per group of columns that share the same data view.
    /// </summary>
    [JsonPropertyName("target_schema_groups")]
    public List<TargetSchemaGroup>? TargetSchemaGroups { get; init; }

}
