// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// API usage per app.
/// </summary>
public sealed partial class PlatformApiDailyAnalyticsByApp
{
    /// <summary>
    /// Application.
    /// </summary>
    [JsonPropertyName("app")]
    public AppType? App { get; init; }

    /// <summary>
    /// API usage for the app.
    /// </summary>
    [JsonPropertyName("usage")]
    public int Usage { get; init; }

    /// <summary>
    /// API app id
    /// </summary>
    [JsonPropertyName("api_app_id")]
    public string ApiAppId { get; init; } = null!;

}
