// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// API usage per day.
/// </summary>
public sealed partial class PlatformApiDailyAnalyticsByDay
{
    /// <summary>
    /// Day.
    /// </summary>
    [JsonPropertyName("day")]
    public string Day { get; init; } = null!;

    /// <summary>
    /// API usage for the day.
    /// </summary>
    [JsonPropertyName("usage")]
    public int Usage { get; init; }

}
