// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response containing the current user's priority prompt
/// </summary>
public sealed partial class PriorityPromptResponse
{
    /// <summary>
    /// The user's priority prompt for task prioritization
    /// </summary>
    [JsonPropertyName("priority_prompt")]
    public string? PriorityPrompt { get; init; }

}
