// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class ProgressValue : ColumnValue
{
    /// <summary>
    /// The column that this value belongs to.
    /// </summary>
    [JsonPropertyName("column")]
    public Column Column { get; init; } = null!;

    /// <summary>
    /// The column's unique identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Whether this item is a leaf (has no subitems).
    /// </summary>
    [JsonPropertyName("is_leaf")]
    public bool IsLeaf { get; init; }

    /// <summary>
    /// Text representation of the column value. Note: Not all columns support textual value
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; }

    /// <summary>
    /// The column's type.
    /// </summary>
    [JsonPropertyName("type")]
    public ColumnType Type { get; init; }

    /// <summary>
    /// The column's raw value in JSON format.
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

}
