// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// All schedule conflicts detected on a project.
/// </summary>
public sealed partial class ProjectScheduleConflicts
{
    /// <summary>
    /// Conflicts found. Empty array when no conflicts exist.
    /// </summary>
    [JsonPropertyName("conflicts")]
    public List<ScheduleConflict> Conflicts { get; init; } = [];

}
