// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A message waiting in the queue while the agent is busy
/// </summary>
public sealed partial class QueuedMessage
{
    /// <summary>
    /// The id assigned to the queued message
    /// </summary>
    [JsonPropertyName("message_id")]
    public string? MessageId { get; init; }

    /// <summary>
    /// The message content
    /// </summary>
    [JsonPropertyName("message")]
    public string? Message { get; init; }

    /// <summary>
    /// Whether this is a chat-mode (discuss) message
    /// </summary>
    [JsonPropertyName("is_chat_mode")]
    public bool? IsChatMode { get; init; }

    /// <summary>
    /// LLM model selected for code generation
    /// </summary>
    [JsonPropertyName("model")]
    public string? Model { get; init; }

    /// <summary>
    /// When the message was queued (epoch milliseconds)
    /// </summary>
    [JsonPropertyName("created_at")]
    public double? CreatedAt { get; init; }

    /// <summary>
    /// Files attached to the queued message
    /// </summary>
    [JsonPropertyName("files")]
    public List<QueuedMessageFile> Files { get; init; } = [];

}
