// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A doc ranked by relevance based on load frequency and recency.
/// </summary>
public sealed partial class RelevantDoc
{
    /// <summary>
    /// Document ID
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Document object ID — the identifier that appears in the doc's URL.
    /// </summary>
    [JsonPropertyName("object_id")]
    public string? ObjectId { get; init; }

    /// <summary>
    /// Document details resolved via federation from the docs subgraph.
    /// </summary>
    [JsonPropertyName("document")]
    public Document? Document { get; init; }

}
