// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Error that occurred while removing team owners.
/// </summary>
public sealed partial class RemoveTeamOwnersError
{
    /// <summary>
    /// The error message.
    /// </summary>
    [JsonPropertyName("message")]
    public string? Message { get; init; }

    /// <summary>
    /// The error code.
    /// </summary>
    [JsonPropertyName("code")]
    public RemoveTeamOwnersErrorCode? Code { get; init; }

    /// <summary>
    /// The id of the user that caused the error.
    /// </summary>
    [JsonPropertyName("user_id")]
    public string? UserId { get; init; }

}
