// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Resources availability with per-resource references and top-level schedule/time-off data
/// </summary>
public sealed partial class ResourcesAvailability
{
    /// <summary>
    /// Per-user availability references
    /// </summary>
    [JsonPropertyName("users_assigned_schedules")]
    public List<UserAssignment> UsersAssignedSchedules { get; init; } = [];

    /// <summary>
    /// Per-team availability references
    /// </summary>
    [JsonPropertyName("teams_assigned_schedules")]
    public List<TeamAssignment> TeamsAssignedSchedules { get; init; } = [];

    /// <summary>
    /// All work schedules referenced by users_assigned_schedules or teams_assigned_schedules entries
    /// </summary>
    [JsonPropertyName("work_schedules")]
    public List<WorkSchedule> WorkSchedules { get; init; } = [];

    /// <summary>
    /// All time off schedules referenced by users_assigned_schedules or teams_assigned_schedules entries
    /// </summary>
    [JsonPropertyName("company_time_offs")]
    public List<TimeOff> CompanyTimeOffs { get; init; } = [];

    /// <summary>
    /// ID of the account-level default work schedule
    /// </summary>
    [JsonPropertyName("default_work_schedule_id")]
    public string DefaultWorkScheduleId { get; init; } = null!;

    /// <summary>
    /// ID of the account-level default time off schedule
    /// </summary>
    [JsonPropertyName("default_company_time_off_id")]
    public string DefaultCompanyTimeOffId { get; init; } = null!;

}
