// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Recurring weekly work-schedule mask for a resource. Does not account for time-offs or specific dates.
/// </summary>
public sealed partial class ResourceWorkWeekday
{
    /// <summary>
    /// Resource ID
    /// </summary>
    [JsonPropertyName("resource_id")]
    public string ResourceId { get; init; } = null!;

    /// <summary>
    /// Sunday-first length-7 mask of active work days for the resource work schedule
    /// </summary>
    [JsonPropertyName("active_weekdays")]
    public List<bool> ActiveWeekdays { get; init; } = [];

}
