// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An AI agent that contributed changes in this restoring point time window.
/// </summary>
public sealed partial class RestoringPointAgentAttribution
{
    /// <summary>
    /// The ID of the agent that made changes.
    /// </summary>
    [JsonPropertyName("agent_id")]
    public string? AgentId { get; init; }

    /// <summary>
    /// The type of entity (e.g. "agent", "workflow").
    /// </summary>
    [JsonPropertyName("entity_type")]
    public string? EntityType { get; init; }

    /// <summary>
    /// The display name of the agent, if available.
    /// </summary>
    [JsonPropertyName("agent_name")]
    public string? AgentName { get; init; }

}
