// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A point-in-time record of a restore status change.
/// </summary>
public sealed partial class RestoreHistoryEntry
{
    /// <summary>
    /// The restore ID at the time this history entry was recorded.
    /// </summary>
    [JsonPropertyName("restore_id")]
    public string RestoreId { get; init; } = null!;

    /// <summary>
    /// The entity id (package id) of the restore.
    /// </summary>
    [JsonPropertyName("entity_id")]
    public string EntityId { get; init; } = null!;

    /// <summary>
    /// The status of the restore at the time this history entry was recorded.
    /// </summary>
    [JsonPropertyName("status")]
    public RestoreStatus Status { get; init; }

    /// <summary>
    /// The date and time this history entry was recorded.
    /// </summary>
    [JsonPropertyName("recorded_at")]
    public string RecordedAt { get; init; } = null!;

}
