// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of a snapshot rollback operation.
/// </summary>
public sealed partial class RollbackSnapshotMutationResult
{
    /// <summary>
    /// The unique identifier of the snapshot.
    /// </summary>
    [JsonPropertyName("snapshot_id")]
    public string SnapshotId { get; init; } = null!;

    /// <summary>
    /// The new status of the snapshot (rollback).
    /// </summary>
    [JsonPropertyName("status")]
    public SnapshotStatus Status { get; init; }

}
