// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A detected conflict where resource availability cannot meet the task duration within its timeline.
/// </summary>
public sealed partial class ScheduleConflict
{
    /// <summary>
    /// The task with the conflict.
    /// </summary>
    [JsonPropertyName("pulse_id")]
    public string PulseId { get; init; } = null!;

    /// <summary>
    /// The resource whose schedule conflicts with the task timeline.
    /// </summary>
    [JsonPropertyName("resource_id")]
    public string ResourceId { get; init; } = null!;

    /// <summary>
    /// Whether the resource has no working days or too few working days to meet the task duration within the timeline.
    /// </summary>
    [JsonPropertyName("severity")]
    public ConflictSeverity? Severity { get; init; }

}
