// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Wrapper for a list of item search results.
/// </summary>
public sealed partial class SearchItemResults
{
    /// <summary>
    /// List of item search results.
    /// </summary>
    [JsonPropertyName("results")]
    public List<SearchItemResult> Results { get; init; } = [];

}
