// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Wrapper for a list of meeting search results.
/// </summary>
public sealed partial class SearchMeetingResults
{
    /// <summary>
    /// List of meeting search results.
    /// </summary>
    [JsonPropertyName("results")]
    public List<SearchMeetingResult> Results { get; init; } = [];

    /// <summary>
    /// Total number of matching meetings in the index (before limit is applied).
    /// </summary>
    [JsonPropertyName("total_count")]
    public int? TotalCount { get; init; }

}
