// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A single item search result with indexed and live data.
/// </summary>
public sealed partial class SearchItemResult
{
    /// <summary>
    /// Unique identifier of the item.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Item data from the search index.
    /// </summary>
    [JsonPropertyName("indexed_data")]
    public SearchIndexedItem IndexedData { get; init; } = null!;

    /// <summary>
    /// Live item data via federation. Null when the referenced item cannot be resolved by the owning subgraph (e.g. deleted, not accessible to the caller, or indexing lag).
    /// </summary>
    [JsonPropertyName("live_data")]
    public Item? LiveData { get; init; }

}
