// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A single user search result with indexed and live data.
/// </summary>
public sealed partial class SearchUserResult
{
    /// <summary>
    /// Unique identifier of the user.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// User data from the search index.
    /// </summary>
    [JsonPropertyName("indexed_data")]
    public SearchIndexedUser IndexedData { get; init; } = null!;

    /// <summary>
    /// Live user data via federation. Null when the referenced user cannot be resolved by the owning subgraph (e.g. deleted, not accessible to the caller, or indexing lag).
    /// </summary>
    [JsonPropertyName("live_data")]
    public User? LiveData { get; init; }

}
