// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Meeting data stored in the search index.
/// </summary>
public sealed partial class SearchIndexedMeeting
{
    /// <summary>
    /// Meeting ID (UUID).
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Meeting title.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// Calendar provider (e.g. google_calendar, outlook_calendar).
    /// </summary>
    [JsonPropertyName("meeting_provider")]
    public string? MeetingProvider { get; init; }

    /// <summary>
    /// ISO timestamp when the meeting started.
    /// </summary>
    [JsonPropertyName("start_time")]
    public string? StartTime { get; init; }

    /// <summary>
    /// ISO timestamp when the meeting ended.
    /// </summary>
    [JsonPropertyName("end_time")]
    public string? EndTime { get; init; }

    /// <summary>
    /// Email addresses of meeting participants.
    /// </summary>
    [JsonPropertyName("attendee_emails")]
    public List<string>? AttendeeEmails { get; init; }

    /// <summary>
    /// Names of meeting participants.
    /// </summary>
    [JsonPropertyName("attendee_names")]
    public List<string>? AttendeeNames { get; init; }

    /// <summary>
    /// AI-generated meeting gist.
    /// </summary>
    [JsonPropertyName("gist")]
    public string? Gist { get; init; }

    /// <summary>
    /// AI-generated meeting summary.
    /// </summary>
    [JsonPropertyName("summary")]
    public string? Summary { get; init; }

    /// <summary>
    /// Meeting talking points and topics.
    /// </summary>
    [JsonPropertyName("talking_points")]
    public string? TalkingPoints { get; init; }

    /// <summary>
    /// Action items from the meeting.
    /// </summary>
    [JsonPropertyName("action_points")]
    public string? ActionPoints { get; init; }

    /// <summary>
    /// Matched text snippets per field. Keys are field names, values are arrays of highlighted text fragments with &lt;em&gt; tags around matched terms.
    /// </summary>
    [JsonPropertyName("highlights")]
    public string? Highlights { get; init; }

}
