// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A sequence that can be used to automate email outreach
/// </summary>
public sealed partial class Sequence
{
    /// <summary>
    /// The unique identifier of the sequence
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The title of the sequence
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The current status of the sequence
    /// </summary>
    [JsonPropertyName("status")]
    public SequenceStatus? Status { get; init; }

    /// <summary>
    /// The type of context the sequence is associated with
    /// </summary>
    [JsonPropertyName("context_type")]
    public SequenceContext? ContextType { get; init; }

    /// <summary>
    /// The ID of the context (e.g., board ID) the sequence is associated with
    /// </summary>
    [JsonPropertyName("context_id")]
    public string? ContextId { get; init; }

    /// <summary>
    /// The ID of the user who owns the sequence
    /// </summary>
    [JsonPropertyName("user_id")]
    public string? UserId { get; init; }

    /// <summary>
    /// The number of steps in the sequence
    /// </summary>
    [JsonPropertyName("step_count")]
    public int? StepCount { get; init; }

    /// <summary>
    /// The total duration of the sequence in seconds
    /// </summary>
    [JsonPropertyName("duration")]
    public int? Duration { get; init; }

    /// <summary>
    /// The timestamp when the sequence was created or last updated
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// The timestamp when the sequence was created or last updated
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

}
