// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A service user in the account.
/// </summary>
public sealed partial class ServiceUser
{
    /// <summary>
    /// The ID of the service user.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The display name of the service user.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// The title/description of the service user.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// Whether the service user is active.
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }

    /// <summary>
    /// The ID of the user who created this service user.
    /// </summary>
    [JsonPropertyName("invited_by_id")]
    public string? InvitedById { get; init; }

    /// <summary>
    /// When the service user was created.
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; init; }

    /// <summary>
    /// The last time the service user token was used for an API request.
    /// </summary>
    [JsonPropertyName("last_token_activity")]
    public string? LastTokenActivity { get; init; }

    /// <summary>
    /// Whether the service user currently has an active API token.
    /// </summary>
    [JsonPropertyName("has_token")]
    public bool? HasToken { get; init; }

}
