// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A paginated connection of snapshottable overviews.
/// </summary>
public sealed partial class SnapshottableOverviewConnection
{
    /// <summary>
    /// The list of overviews in this page.
    /// </summary>
    [JsonPropertyName("items")]
    public List<SnapshottableOverview>? Items { get; init; }

    /// <summary>
    /// The cursor for the next page.
    /// </summary>
    [JsonPropertyName("cursor")]
    public string? Cursor { get; init; }

    /// <summary>
    /// Whether there are more pages.
    /// </summary>
    [JsonPropertyName("has_next_page")]
    public bool? HasNextPage { get; init; }

}
