// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A board that can be snapshotted, with metadata and relations.
/// </summary>
public sealed partial class SnapshottableBoard
{
    /// <summary>
    /// The board ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The board name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// The board owner user ID.
    /// </summary>
    [JsonPropertyName("owner")]
    public string? Owner { get; init; }

    /// <summary>
    /// The workspace ID this board belongs to.
    /// </summary>
    [JsonPropertyName("workspace_id")]
    public string? WorkspaceId { get; init; }

    /// <summary>
    /// Whether this board is a document.
    /// </summary>
    [JsonPropertyName("is_doc")]
    public bool? IsDoc { get; init; }

    /// <summary>
    /// Whether this board is a managed template instance.
    /// </summary>
    [JsonPropertyName("is_managed_template_instance")]
    public bool? IsManagedTemplateInstance { get; init; }

    /// <summary>
    /// Related boards by relation type. Limited to 1 level of depth.
    /// </summary>
    [JsonPropertyName("board_relations")]
    public List<SnapshottableBoard>? BoardRelations { get; init; }

}
