// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A monday dev sprint snapshot item column value.
/// </summary>
public sealed partial class SprintSnapshotItemColumnValue
{
    /// <summary>
    /// monday dev sprint snapshot item column id
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// monday dev sprint snapshot item column type
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; init; } = null!;

    /// <summary>
    /// monday dev sprint snapshot item column value
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

}
