// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A monday dev sprint snapshot column metadata.
/// </summary>
public sealed partial class SprintSnapshotColumnMetadata
{
    /// <summary>
    /// monday dev sprint snapshot column id
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// monday dev sprint snapshot status column done status indexes
    /// </summary>
    [JsonPropertyName("done_status_indexes")]
    public List<int> DoneStatusIndexes { get; init; } = [];

}
