// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A status label style.
/// </summary>
public sealed partial class StatusLabelStyle
{
    /// <summary>
    /// The label's border color in hex format.
    /// </summary>
    [JsonPropertyName("border")]
    public string Border { get; init; } = null!;

    /// <summary>
    /// The label's color in hex format.
    /// </summary>
    [JsonPropertyName("color")]
    public string Color { get; init; } = null!;

}
