// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class StatusValue : ColumnValue
{
    /// <summary>
    /// The column that this value belongs to.
    /// </summary>
    [JsonPropertyName("column")]
    public Column Column { get; init; } = null!;

    /// <summary>
    /// The column's unique identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The index of the status in the board
    /// </summary>
    [JsonPropertyName("index")]
    public int? Index { get; init; }

    /// <summary>
    /// Whether the status is done
    /// </summary>
    [JsonPropertyName("is_done")]
    public bool? IsDone { get; init; }

    /// <summary>
    /// Whether this item is a leaf (has no subitems).
    /// </summary>
    [JsonPropertyName("is_leaf")]
    public bool IsLeaf { get; init; }

    /// <summary>
    /// The label of the status
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }

    /// <summary>
    /// The style of the status label
    /// </summary>
    [JsonPropertyName("label_style")]
    public StatusLabelStyle? LabelStyle { get; init; }

    [JsonPropertyName("text")]
    public string? Text { get; init; }

    /// <summary>
    /// The column's type.
    /// </summary>
    [JsonPropertyName("type")]
    public ColumnType Type { get; init; }

    /// <summary>
    /// The ID of an update attached to the status
    /// </summary>
    [JsonPropertyName("update_id")]
    public string? UpdateId { get; init; }

    /// <summary>
    /// The date when column value was last updated.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

    /// <summary>
    /// The column's raw value in JSON format.
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

}
