// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A suggested AI agent based on user activity patterns
/// </summary>
public sealed partial class SuggestedAgent
{
    /// <summary>
    /// The title of the suggested agent
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// A hook/one-liner for the agent
    /// </summary>
    [JsonPropertyName("pitch")]
    public string? Pitch { get; init; }

    /// <summary>
    /// A user-friendly explanation of why this agent is suggested
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// List of 3rd-party connectors this agent uses (e.g., Jira, Google Calendar)
    /// </summary>
    [JsonPropertyName("connectors")]
    public List<string>? Connectors { get; init; }

    /// <summary>
    /// Whether this agent should have web search capabilities
    /// </summary>
    [JsonPropertyName("include_web_search")]
    public bool? IncludeWebSearch { get; init; }

    /// <summary>
    /// Confidence score (0.0–1.0) that the user will benefit from this agent
    /// </summary>
    [JsonPropertyName("confidence")]
    public double? Confidence { get; init; }

    /// <summary>
    /// A ready-to-use prompt for creating this agent via monday-agents
    /// </summary>
    [JsonPropertyName("seed_prompt")]
    public string? SeedPrompt { get; init; }

    /// <summary>
    /// List of triggers that define when this agent should run
    /// </summary>
    [JsonPropertyName("triggers")]
    public List<SuggestedTrigger>? Triggers { get; init; }

}
