// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Status of a template installation async operation.
/// </summary>
public sealed partial class TemplateInstallationStatusResult
{
    /// <summary>
    /// Board IDs are populated incrementally during the metadata phase as each board
    ///   is created, and complete by the time per-board content jobs start. Boards
    ///   exist as empty shells (no items, broken mirror columns, no automations) until
    ///   status is COMPLETE. Safe to store these IDs early, but do not read or write
    ///   board content until COMPLETE.
    /// </summary>
    [JsonPropertyName("board_ids")]
    public List<string> BoardIds { get; init; } = [];

    /// <summary>
    /// Mapping of each source (template) board ID to the newly created board ID.
    /// </summary>
    [JsonPropertyName("board_ids_map")]
    public List<BoardIdMapping> BoardIdsMap { get; init; } = [];

    /// <summary>
    /// True iff status is COMPLETE.
    /// </summary>
    [JsonPropertyName("is_complete")]
    public bool IsComplete { get; init; }

    /// <summary>
    /// True iff status is FAILED.
    /// </summary>
    [JsonPropertyName("is_failed")]
    public bool IsFailed { get; init; }

    /// <summary>
    /// The process_id returned by use_template.
    /// </summary>
    [JsonPropertyName("process_id")]
    public string ProcessId { get; init; } = null!;

    /// <summary>
    /// Lifecycle status (PENDING / IN_PROGRESS / COMPLETE / FAILED).
    /// </summary>
    [JsonPropertyName("status")]
    public TemplateInstallationStatus Status { get; init; }

}
