// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Thread metadata for a root message — present only when the message has at least one reply.
/// </summary>
public sealed partial class ThreadSessionMetadata
{
    /// <summary>
    /// ID of the thread container.
    /// </summary>
    [JsonPropertyName("thread_session_id")]
    public string? ThreadSessionId { get; init; }

    /// <summary>
    /// ID of the root message this thread hangs off.
    /// </summary>
    [JsonPropertyName("root_message_id")]
    public string? RootMessageId { get; init; }

    /// <summary>
    /// Number of non-deleted replies in the thread (≥1 when present).
    /// </summary>
    [JsonPropertyName("reply_count")]
    public int? ReplyCount { get; init; }

    /// <summary>
    /// ISO 8601 timestamp of the most recent reply.
    /// </summary>
    [JsonPropertyName("last_reply_at")]
    public string? LastReplyAt { get; init; }

    /// <summary>
    /// IDs of the first up-to-5 distinct repliers, ordered by their earliest reply.
    /// </summary>
    [JsonPropertyName("participant_user_ids")]
    public List<string>? ParticipantUserIds { get; init; }

}
