// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Header for a time period (label and date range).
/// </summary>
public sealed partial class TimePeriodHeader
{
    /// <summary>
    /// Human-readable label for the period.
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }

    /// <summary>
    /// Start date of the period (ISO 8601).
    /// </summary>
    [JsonPropertyName("start_date")]
    public string? StartDate { get; init; }

    /// <summary>
    /// End date of the period (ISO 8601).
    /// </summary>
    [JsonPropertyName("end_date")]
    public string? EndDate { get; init; }

}
