// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Effort and utilization for a single time bucket.
/// </summary>
public sealed partial class TimeBucket
{
    /// <summary>
    /// Label for this bucket (e.g. week or month).
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }

    /// <summary>
    /// Effort hours in this bucket.
    /// </summary>
    [JsonPropertyName("effort")]
    public Effort? Effort { get; init; }

    /// <summary>
    /// Utilization ratios in this bucket.
    /// </summary>
    [JsonPropertyName("utilization_ratios")]
    public UtilizationRatios? UtilizationRatios { get; init; }

}
