// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class TimeTrackingValue : ColumnValue
{
    /// <summary>
    /// The column that this value belongs to.
    /// </summary>
    [JsonPropertyName("column")]
    public Column Column { get; init; } = null!;

    /// <summary>
    /// Total duration of the time tracker
    /// </summary>
    [JsonPropertyName("duration")]
    public int? Duration { get; init; }

    [JsonPropertyName("history")]
    public List<TimeTrackingHistoryItem> History { get; init; } = [];

    /// <summary>
    /// The column's unique identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Whether this item is a leaf (has no subitems).
    /// </summary>
    [JsonPropertyName("is_leaf")]
    public bool IsLeaf { get; init; }

    /// <summary>
    /// Whether the time tracker is running
    /// </summary>
    [JsonPropertyName("running")]
    public bool? Running { get; init; }

    /// <summary>
    /// The date when the time tracker was started
    /// </summary>
    [JsonPropertyName("started_at")]
    public DateOnly? StartedAt { get; init; }

    [JsonPropertyName("text")]
    public string? Text { get; init; }

    /// <summary>
    /// The column's type.
    /// </summary>
    [JsonPropertyName("type")]
    public ColumnType Type { get; init; }

    /// <summary>
    /// The date when column value was last updated.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

    [JsonPropertyName("value")]
    public string? Value { get; init; }

}
