// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of saving an integration block instance field configuration
/// </summary>
public sealed partial class ToolFieldsConfiguredResult
{
    /// <summary>
    /// The ID of the AI app
    /// </summary>
    [JsonPropertyName("ai_app_id")]
    public string? AiAppId { get; init; }

    /// <summary>
    /// The ID of the configured block instance
    /// </summary>
    [JsonPropertyName("block_instance_id")]
    public string? BlockInstanceId { get; init; }

    /// <summary>
    /// The normalized scopes that were persisted, after dropping unknown fields and capping entries
    /// </summary>
    [JsonPropertyName("field_value_scopes")]
    public string FieldValueScopes { get; init; } = null!;

}
