// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A board and its total action count
/// </summary>
public sealed partial class TopBoardEntry
{
    /// <summary>
    /// The board ID
    /// </summary>
    [JsonPropertyName("board_id")]
    public string? BoardId { get; init; }

    /// <summary>
    /// Number of actions performed on this board
    /// </summary>
    [JsonPropertyName("count")]
    public int? Count { get; init; }

}
