// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of the transfer_agent_ownership mutation.
/// </summary>
public sealed partial class TransferAgentOwnershipResult
{
    /// <summary>
    /// Whether the ownership transfer completed successfully.
    /// </summary>
    [JsonPropertyName("is_successful")]
    public bool? IsSuccessful { get; init; }

    /// <summary>
    /// The failure reason, or null when the transfer succeeded.
    /// </summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }

}
