// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of checking eligibility to transition a vibe app to external mode
/// </summary>
public sealed partial class TransitionToExternalEligibility
{
    /// <summary>
    /// Whether the current user owns all boards connected to this app
    /// </summary>
    [JsonPropertyName("is_eligible")]
    public bool? IsEligible { get; init; }

}
