// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A user that could not be created, returning the original input and failure reason.
/// </summary>
public sealed partial class UncreatedUser
{
    /// <summary>
    /// The kind of user to create.
    /// </summary>
    [JsonPropertyName("kind")]
    public string? Kind { get; init; }

    /// <summary>
    /// The name for the user.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// The email for the user.
    /// </summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>
    /// The title for the user.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The activation status for the user.
    /// </summary>
    [JsonPropertyName("status")]
    public UserStatus? Status { get; init; }

    /// <summary>
    /// Whether the email is confirmed.
    /// </summary>
    [JsonPropertyName("confirmed_email")]
    public bool? ConfirmedEmail { get; init; }

    /// <summary>
    /// Photo URL for the user (HTTPS only).
    /// </summary>
    [JsonPropertyName("photo_url")]
    public string? PhotoUrl { get; init; }

    /// <summary>
    /// The reason the user could not be created.
    /// </summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }

}
