// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of removing an agent from the saved list
/// </summary>
public sealed partial class UnsaveAgentResult
{
    /// <summary>
    /// The agent user id of the agent that was removed from the saved list
    /// </summary>
    [JsonPropertyName("agent_user_id")]
    public string? AgentUserId { get; init; }

}
