// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of the unsubscribe_users_from_agent mutation.
/// </summary>
public sealed partial class UnsubscribeUsersFromAgentResult
{
    /// <summary>
    /// Whether all users were successfully unsubscribed from the agent.
    /// </summary>
    [JsonPropertyName("is_successful")]
    public bool? IsSuccessful { get; init; }

}
