// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Represents the response when adding an object to a list
/// </summary>
public sealed partial class UpdateFavoriteResultType
{
    /// <summary>
    /// The favorite item that its position was updated
    /// </summary>
    [JsonPropertyName("favorite")]
    public GraphqlHierarchyObjectItem? Favorite { get; init; }

}
