// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response indicating whether the directory attribute update succeeded
/// </summary>
public sealed partial class UpdateDirectoryResourceAttributesResponse
{
    /// <summary>
    /// Indicates whether the batch update completed successfully.
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; init; }

}
