// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Paginated updates response with cursor.
/// </summary>
public sealed partial class UpdatesPage
{
    /// <summary>
    /// The list of updates.
    /// </summary>
    [JsonPropertyName("updates")]
    public List<Update> Updates { get; init; } = [];

    /// <summary>
    /// Opaque cursor for the next page. Null when no more data.
    /// </summary>
    [JsonPropertyName("cursor")]
    public string? Cursor { get; init; }

}
