// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A single user permit/action with its permission status
/// </summary>
public sealed partial class UserPermit
{
    /// <summary>
    /// The name/identifier of the permit/action
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// Whether the user has permission for this action
    /// </summary>
    [JsonPropertyName("permitted")]
    public bool Permitted { get; init; }

    /// <summary>
    /// Contextual information about the permit reason
    /// </summary>
    [JsonPropertyName("reason_context")]
    public UserPermitReasonContext? ReasonContext { get; init; }

    /// <summary>
    /// Technical reason code for the permission status
    /// </summary>
    [JsonPropertyName("technical_reason")]
    public int? TechnicalReason { get; init; }

}
