// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Contextual information about the permit reason
/// </summary>
public sealed partial class UserPermitReasonContext
{
    /// <summary>
    /// Name of the permission that determined this permit decision
    /// </summary>
    [JsonPropertyName("permission")]
    public string? Permission { get; init; }

    /// <summary>
    /// Name of the policy that determined this permit decision
    /// </summary>
    [JsonPropertyName("policy")]
    public string? Policy { get; init; }

    /// <summary>
    /// Name of the role that determined this permit decision
    /// </summary>
    [JsonPropertyName("role")]
    public string? Role { get; init; }

    /// <summary>
    /// The type of scope (account, workspace, board, etc.)
    /// </summary>
    [JsonPropertyName("scope_type")]
    public UserPermitScopeKind? ScopeType { get; init; }

}
