// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// User feedback for AI chat messages
/// </summary>
public sealed partial class UserFeedback
{
    /// <summary>
    /// Unique identifier for the feedback
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The account ID associated with the feedback
    /// </summary>
    [JsonPropertyName("accountId")]
    public int? AccountId { get; init; }

    /// <summary>
    /// The user ID who provided the feedback
    /// </summary>
    [JsonPropertyName("userId")]
    public int? UserId { get; init; }

    /// <summary>
    /// The sentiment of the feedback (positive or negative)
    /// </summary>
    [JsonPropertyName("feedbackSentiment")]
    public FeedbackSentiment? FeedbackSentiment { get; init; }

    /// <summary>
    /// The feedback message text content
    /// </summary>
    [JsonPropertyName("feedbackMessage")]
    public string? FeedbackMessage { get; init; }

    /// <summary>
    /// The ID of the chat message this feedback relates to
    /// </summary>
    [JsonPropertyName("messageId")]
    public string? MessageId { get; init; }

    /// <summary>
    /// When the feedback was created
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// When the feedback was last updated
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateOnly? UpdatedAt { get; init; }

}
