// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// User context information.
/// </summary>
public sealed partial class UserContext
{
    /// <summary>
    /// Unique user identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// User display name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// User job title.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// User email address.
    /// </summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>
    /// User type. Values: null (regular), "guest", "view_only", "portal_user".
    /// </summary>
    [JsonPropertyName("kind")]
    public string? Kind { get; init; }

    /// <summary>
    /// User job role. Examples: "project_manager", "marketing_manager", "ceo".
    /// </summary>
    [JsonPropertyName("job_role")]
    public string? JobRole { get; init; }

    /// <summary>
    /// User job department. Examples: "engineering", "marketing", "sales", "hr".
    /// </summary>
    [JsonPropertyName("job_department")]
    public string? JobDepartment { get; init; }

    /// <summary>
    /// Organizational department within the workspace.
    /// </summary>
    [JsonPropertyName("department")]
    public string? Department { get; init; }

    /// <summary>
    /// User time zone. Examples: "America/New_York", "Europe/London".
    /// </summary>
    [JsonPropertyName("time_zone")]
    public string? TimeZone { get; init; }

    /// <summary>
    /// User locale for date and number formatting. Examples: "en-US", "de-DE".
    /// </summary>
    [JsonPropertyName("locale")]
    public string? Locale { get; init; }

    /// <summary>
    /// Number of days since the user became active.
    /// </summary>
    [JsonPropertyName("tenure_days")]
    public int? TenureDays { get; init; }

}
