// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Utilization ratios (e.g. spent/available) per effort kind.
/// </summary>
public sealed partial class UtilizationRatios
{
    /// <summary>
    /// Allocated / denominator ratio.
    /// </summary>
    [JsonPropertyName("allocated")]
    public double? Allocated { get; init; }

    /// <summary>
    /// Planned / denominator ratio.
    /// </summary>
    [JsonPropertyName("planned")]
    public double? Planned { get; init; }

    /// <summary>
    /// Spent / denominator ratio.
    /// </summary>
    [JsonPropertyName("spent")]
    public double? Spent { get; init; }

}
