// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Utilization data for a single resource.
/// </summary>
public sealed partial class UtilizationReportResource
{
    /// <summary>
    /// ID of the resource.
    /// </summary>
    [JsonPropertyName("resource_id")]
    public string? ResourceId { get; init; }

    /// <summary>
    /// Whether this row is a placeholder (e.g. unassigned).
    /// </summary>
    [JsonPropertyName("is_placeholder")]
    public bool? IsPlaceholder { get; init; }

    /// <summary>
    /// Time buckets for this resource.
    /// </summary>
    [JsonPropertyName("time_buckets")]
    public List<TimeBucket>? TimeBuckets { get; init; }

    /// <summary>
    /// Per-project breakdown when requested.
    /// </summary>
    [JsonPropertyName("project_breakdown")]
    public List<UtilizationReportProjectBreakdown>? ProjectBreakdown { get; init; }

}
