// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class Validations
{
    /// <summary>
    /// Array of required column IDs
    /// </summary>
    [JsonPropertyName("required_column_ids")]
    public List<string>? RequiredColumnIds { get; init; }

    /// <summary>
    /// Validation rules
    /// </summary>
    [JsonPropertyName("rules")]
    public string? Rules { get; init; }

}
