// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The UI metadata of the vibe app
/// </summary>
public sealed partial class VibeAppUIMetadata
{
    /// <summary>
    /// The color of the app card
    /// </summary>
    [JsonPropertyName("app_card_color")]
    public string? AppCardColor { get; init; }

    /// <summary>
    /// Custom app icon CDN URL (single 60×60px PNG)
    /// </summary>
    [JsonPropertyName("icon_url")]
    public string? IconUrl { get; init; }

    /// <summary>
    /// The source of the app creation
    /// </summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }

}
