// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An integration the app holds connected credentials for
/// </summary>
public sealed partial class VibeConnectedIntegration
{
    /// <summary>
    /// The block-app-feature reference id of the connected tool
    /// </summary>
    [JsonPropertyName("block_reference_id")]
    public string? BlockReferenceId { get; init; }

    /// <summary>
    /// Human-readable tool name, e.g. "Send Slack message". Null when the block app feature no longer resolves
    /// </summary>
    [JsonPropertyName("tool_name")]
    public string? ToolName { get; init; }

    /// <summary>
    /// What the tool does, as published by the block app feature
    /// </summary>
    [JsonPropertyName("tool_description")]
    public string? ToolDescription { get; init; }

    /// <summary>
    /// Provider/app name the tool belongs to, e.g. "Slack"
    /// </summary>
    [JsonPropertyName("app_name")]
    public string? AppName { get; init; }

    /// <summary>
    /// App icon URL, for rendering the integration chip
    /// </summary>
    [JsonPropertyName("icon_url")]
    public string? IconUrl { get; init; }

}
