// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An image or media asset uploaded to and shared across the account
/// </summary>
public sealed partial class VibeAsset
{
    /// <summary>
    /// Unique identifier for the vibe asset
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Vibe app this asset is scoped to, or null for account-level assets
    /// </summary>
    [JsonPropertyName("app_id")]
    public string? AppId { get; init; }

    /// <summary>
    /// Asset ID in the assets-core platform service
    /// </summary>
    [JsonPropertyName("asset_id")]
    public string? AssetId { get; init; }

    /// <summary>
    /// Original filename of the uploaded asset
    /// </summary>
    [JsonPropertyName("filename")]
    public string? Filename { get; init; }

    /// <summary>
    /// MIME type of the asset (e.g. image/png)
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string? MimeType { get; init; }

    /// <summary>
    /// File size in bytes
    /// </summary>
    [JsonPropertyName("file_size")]
    public int? FileSize { get; init; }

    /// <summary>
    /// Permanent public CDN URL for the asset
    /// </summary>
    [JsonPropertyName("cdn_url")]
    public string? CdnUrl { get; init; }

    /// <summary>
    /// Image width in pixels, populated after captioning
    /// </summary>
    [JsonPropertyName("width")]
    public int? Width { get; init; }

    /// <summary>
    /// Image height in pixels, populated after captioning
    /// </summary>
    [JsonPropertyName("height")]
    public int? Height { get; init; }

    /// <summary>
    /// AI-generated caption describing the asset content
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// AI-generated alt text for accessibility
    /// </summary>
    [JsonPropertyName("alt_text")]
    public string? AltText { get; init; }

    /// <summary>
    /// Current status of the AI captioning process
    /// </summary>
    [JsonPropertyName("caption_status")]
    public AssetCaptionStatus? CaptionStatus { get; init; }

    /// <summary>
    /// Timestamp when the asset was uploaded
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly? CreatedAt { get; init; }

    /// <summary>
    /// Timestamp when the asset was last updated
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly? UpdatedAt { get; init; }

}
