// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Status of a vibe app including existence and publish state
/// </summary>
public sealed partial class VibeAppPublishStatus
{
    /// <summary>
    /// Whether the app exists in the database
    /// </summary>
    [JsonPropertyName("exists")]
    public bool? Exists { get; init; }

    /// <summary>
    /// Whether the app is published (only meaningful if exists is true)
    /// </summary>
    [JsonPropertyName("is_published")]
    public bool? IsPublished { get; init; }

}
