// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Permissions for vibe related actions
/// </summary>
public sealed partial class VibePermissions
{
    /// <summary>
    /// Permission to create open workspaces
    /// </summary>
    [JsonPropertyName("create_open_workspace")]
    public bool? CreateOpenWorkspace { get; init; }

    /// <summary>
    /// Permission to publish vibe apps as trusted apps
    /// </summary>
    [JsonPropertyName("can_publish_trusted_app")]
    public bool? CanPublishTrustedApp { get; init; }

    /// <summary>
    /// Permission to create or edit vibe apps
    /// </summary>
    [JsonPropertyName("can_create_or_edit_vibe_app")]
    public bool? CanCreateOrEditVibeApp { get; init; }

    /// <summary>
    /// Permission to publish vibe apps to the public web
    /// </summary>
    [JsonPropertyName("can_publish_to_public_web")]
    public bool? CanPublishToPublicWeb { get; init; }

    /// <summary>
    /// Permission to generate public vibe template links
    /// </summary>
    [JsonPropertyName("can_generate_public_vibe_templates")]
    public bool? CanGeneratePublicVibeTemplates { get; init; }

    /// <summary>
    /// Permission to create views on the specified boards
    /// </summary>
    [JsonPropertyName("create_board_views")]
    public List<BoardViewPermission>? CreateBoardViews { get; init; }

    /// <summary>
    /// Permission to view the connected boards for an AI app
    /// </summary>
    [JsonPropertyName("connected_boards")]
    public List<ConnectedBoardPermission>? ConnectedBoards { get; init; }

}
