// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A number of currently published apps and the maximum allowed limit
/// </summary>
public sealed partial class VibeSubscription
{
    /// <summary>
    /// Current number of published apps
    /// </summary>
    [JsonPropertyName("publishedApps")]
    public int? PublishedApps { get; init; }

    /// <summary>
    /// Maximum number of published apps
    /// </summary>
    [JsonPropertyName("maxPublishedApps")]
    public int? MaxPublishedApps { get; init; }

}
