// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An inferred field of a collection (from sampling documents).
/// </summary>
public sealed partial class VibeCollectionField
{
    /// <summary>
    /// Dot-path of the field.
    /// </summary>
    [JsonPropertyName("path")]
    public string? Path { get; init; }

    /// <summary>
    /// JSON types observed for this field across the sample.
    /// </summary>
    [JsonPropertyName("types")]
    public List<string>? Types { get; init; }

    /// <summary>
    /// Fraction of sampled docs containing this field (0..1).
    /// </summary>
    [JsonPropertyName("presence")]
    public double? Presence { get; init; }

    /// <summary>
    /// A sample value for this field, if any.
    /// </summary>
    [JsonPropertyName("sample")]
    public string? Sample { get; init; }

}
