// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// List of work schedules
/// </summary>
public sealed partial class WorkSchedules
{
    /// <summary>
    /// Work schedules
    /// </summary>
    [JsonPropertyName("work_schedules")]
    public List<WorkSchedule> WorkSchedulesValue { get; init; } = [];

}
