// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Result of querying trigger entities for a run-once workflow execution
/// </summary>
public sealed partial class WorkflowRunOnceTriggerEntities
{
    /// <summary>
    /// Whether this workflow requires a trigger entity to execute. When false (e.g., for scheduled/cron triggers), you can call 'run_workflow_once' without providing a trigger_payload.
    /// </summary>
    [JsonPropertyName("requires_entity")]
    public bool RequiresEntity { get; init; }

    /// <summary>
    /// List of available trigger entities. Each entity represents a real object in the workspace (e.g., a board item) that the workflow can be executed against. Pass the selected entity's 'value' field to 'run_workflow_once' as 'trigger_payload'.
    /// </summary>
    [JsonPropertyName("entities")]
    public List<WorkflowRunOnceTriggerEntity> Entities { get; init; } = [];

}
