// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A named work schedule with per-weekday working hours
/// </summary>
public sealed partial class WorkSchedule
{
    /// <summary>
    /// Unique identifier of the work schedule
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Display name of the work schedule
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// Whether this is the account-level default work schedule
    /// </summary>
    [JsonPropertyName("is_default")]
    public bool IsDefault { get; init; }

    /// <summary>
    /// ID of the user who created this work schedule, null if system-generated
    /// </summary>
    [JsonPropertyName("created_by")]
    public string? CreatedBy { get; init; }

    /// <summary>
    /// ISO 8601 timestamp when this record was created
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateOnly CreatedAt { get; init; }

    /// <summary>
    /// ISO 8601 timestamp when this record was last updated
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateOnly UpdatedAt { get; init; }

    /// <summary>
    /// Per-weekday working hours for this schedule
    /// </summary>
    [JsonPropertyName("days")]
    public List<WorkScheduleDay> Days { get; init; } = [];

    /// <summary>
    /// Whether any users are currently assigned to this work schedule
    /// </summary>
    [JsonPropertyName("has_assignments")]
    public bool HasAssignments { get; init; }

}
