// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Context data for the workflow builder
/// </summary>
public sealed partial class WorkflowBuilderContextData
{
    /// <summary>
    /// Keys of input fields that should be hidden in the workflow builder
    /// </summary>
    [JsonPropertyName("hidden_input_fields_keys")]
    public List<string>? HiddenInputFieldsKeys { get; init; }

}
