// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Identifiers for a newly created workflow
/// </summary>
public sealed partial class WorkflowBuilderCreateResult
{
    /// <summary>
    /// Stable workflow entity ID
    /// </summary>
    [JsonPropertyName("workflow_object_id")]
    public string? WorkflowObjectId { get; init; }

    /// <summary>
    /// Draft workflow ID
    /// </summary>
    [JsonPropertyName("workflow_draft_id")]
    public string? WorkflowDraftId { get; init; }

}
