// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_object' GraphQL operation.
/// </summary>
public sealed partial class DeleteObjectData
{
    /// <summary>
    /// Permanently deletes an object from the Monday.com Objects Platform. Unlike archiving, deletion is only reversible for 30 days and removes all associated data. This operation works for any object type including boards, docs, dashboards, workflows, and specialized objects (CRM, capacity manager, etc.). WARNING: This operation cannot be undone after 30 days.
    /// </summary>
    [JsonPropertyName("delete_object")]
    public Object? DeleteObject { get; init; }
}
