// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_form_tag' GraphQL operation.
/// </summary>
public sealed partial class UpdateFormTagData
{
    /// <summary>
    /// Update an existing tag in a form
    /// </summary>
    [JsonPropertyName("update_form_tag")]
    public bool? UpdateFormTag { get; init; }
}
