// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'batch' resource.
/// </summary>
public sealed partial class BatchBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public BatchBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'batch_extend_trial_period' mutation.</summary>
    public BatchExtendTrialPeriodRequestBuilder ExtendTrialPeriod => new BatchExtendTrialPeriodRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'batch_update_dependency_column' mutation.</summary>
    public BatchUpdateDependencyColumnRequestBuilder UpdateDependencyColumn => new BatchUpdateDependencyColumnRequestBuilder(_graphQlClient);

}
