// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'delete_teams_from_board' GraphQL operation.
/// </summary>
public sealed class DeleteTeamsFromBoardVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("team_ids")]
    public List<string> TeamIds { get; init; } = [];

}
