// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_group' GraphQL operation.
/// </summary>
public sealed class UpdateGroupVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("group_attribute")]
    public GroupAttributes GroupAttribute { get; init; }

    [JsonPropertyName("group_id")]
    public string GroupId { get; init; } = null!;

    [JsonPropertyName("new_value")]
    public string NewValue { get; init; } = null!;

}
