// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'create_object_relations' GraphQL operation.
/// </summary>
public sealed partial class CreateObjectRelationsData
{
    /// <summary>
    /// Create relations for an object
    /// </summary>
    [JsonPropertyName("create_object_relations")]
    public List<ObjectRelation>? CreateObjectRelations { get; init; }
}
