// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'delete_app_lifecycle_subscription' GraphQL mutation.
/// </summary>
public sealed partial class DeleteAppLifecycleSubscriptionRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DeleteAppLifecycleSubscriptionRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'delete_app_lifecycle_subscription' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DeleteAppLifecycleSubscriptionData>> Execute(DeleteAppLifecycleSubscriptionVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DeleteAppLifecycleSubscription($entity_identifier: ID!, $entity_type: String!) { delete_app_lifecycle_subscription(entity_identifier: $entity_identifier, entity_type: $entity_type) }";
        return _graphQlClient.Execute<DeleteAppLifecycleSubscriptionData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'delete_app_lifecycle_subscription' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<bool?> GetValue(DeleteAppLifecycleSubscriptionVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DeleteAppLifecycleSubscriptionData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.DeleteAppLifecycleSubscription;
    }
}
