// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_form_question' GraphQL operation.
/// </summary>
public sealed class CreateFormQuestionVariables
{
    [JsonPropertyName("formToken")]
    public string FormToken { get; init; } = null!;

    [JsonPropertyName("question")]
    public CreateQuestionInput Question { get; init; } = null!;

}
