// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'delete_webhook' GraphQL mutation.
/// </summary>
public sealed partial class DeleteWebhookRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DeleteWebhookRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'delete_webhook' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DeleteWebhookData>> Execute(DeleteWebhookVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DeleteWebhook($id: ID!) { delete_webhook(id: $id) { board_id config event id } }";
        return _graphQlClient.Execute<DeleteWebhookData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'delete_webhook' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Webhook?> GetValue(DeleteWebhookVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DeleteWebhookData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.DeleteWebhook;
    }
}
