// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'set_board_permission' GraphQL operation.
/// </summary>
public sealed partial class SetBoardPermissionData
{
    /// <summary>
    /// Set or update the board's permission to specified role. This concept is also
    ///   known as default board role, general access or board permission set.
    /// </summary>
    [JsonPropertyName("set_board_permission")]
    public SetBoardPermissionResponse? SetBoardPermission { get; init; }
}
