// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_app' GraphQL operation.
/// </summary>
public sealed class UpdateAppVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("input")]
    public UpdateAppInput Input { get; init; } = null!;

}
