// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_notification_setting' GraphQL operation.
/// </summary>
public sealed partial class UpdateNotificationSettingData
{
    /// <summary>
    /// Updates a notification setting's enabled status.
    /// </summary>
    [JsonPropertyName("update_notification_setting")]
    public List<NotificationSetting>? UpdateNotificationSetting { get; init; }
}
