// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'webhooks' GraphQL operation.
/// </summary>
public sealed partial class GetWebhooksData
{
    /// <summary>
    /// Get a collection of webhooks for the board
    /// </summary>
    [JsonPropertyName("webhooks")]
    public List<Webhook>? Webhooks { get; init; }
}
