// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'convert_board_to_project' GraphQL operation.
/// </summary>
public sealed class ConvertBoardToProjectVariables
{
    [JsonPropertyName("input")]
    public ConvertBoardToProjectInput Input { get; init; } = null!;

}
