// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'timeline' GraphQL query.
/// </summary>
public sealed partial class GetTimelineRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetTimelineRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'timeline' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetTimelineData>> Execute(GetTimelineVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetTimeline($id: ID!, $skipConnectedItems: Boolean) { timeline(id: $id, skipConnectedItems: $skipConnectedItems) { id } }";
        return _graphQlClient.Execute<GetTimelineData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'timeline' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<TimelineResponse?> GetValue(GetTimelineVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetTimelineData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.Timeline;
    }
}
