// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_assets_on_item' GraphQL operation.
/// </summary>
public sealed partial class UpdateAssetsOnItemData
{
    /// <summary>
    /// Update item column value by existing assets
    /// </summary>
    [JsonPropertyName("update_assets_on_item")]
    public Item? UpdateAssetsOnItem { get; init; }
}
