// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'app_subscription' GraphQL query.
/// </summary>
public sealed partial class GetAppSubscriptionRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetAppSubscriptionRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'app_subscription'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetAppSubscriptionData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetAppSubscription { app_subscription { billing_period days_left is_trial max_units plan_id pricing_version renewal_date } }";
        return _graphQlClient.Execute<GetAppSubscriptionData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'app_subscription' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<AppSubscription>?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetAppSubscriptionData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.AppSubscription;
    }
}
