// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'articles' GraphQL operation.
/// </summary>
public sealed partial class GetArticlesData
{
    /// <summary>
    /// Retrieves a list of published articles with their metadata and content blocks that the requesting user has permission to access. Articles without proper permissions will be filtered out. By default, returns the first 25 blocks per article. To retrieve more blocks, use the article_blocks query.
    /// </summary>
    [JsonPropertyName("articles")]
    public List<Article> Articles { get; init; } = [];
}
