// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'deactivate_managed_column' GraphQL mutation.
/// </summary>
public sealed partial class DeactivateManagedColumnRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DeactivateManagedColumnRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'deactivate_managed_column' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DeactivateManagedColumnData>> Execute(DeactivateManagedColumnVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DeactivateManagedColumn($id: String!) { deactivate_managed_column(id: $id) { id title description settings_json created_by updated_by revision state created_at updated_at } }";
        return _graphQlClient.Execute<DeactivateManagedColumnData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'deactivate_managed_column' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ManagedColumn?> GetValue(DeactivateManagedColumnVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DeactivateManagedColumnData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.DeactivateManagedColumn;
    }
}
