// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_webhook' GraphQL operation.
/// </summary>
public sealed partial class DeleteWebhookData
{
    /// <summary>
    /// Delete a new webhook.
    /// </summary>
    [JsonPropertyName("delete_webhook")]
    public Webhook? DeleteWebhook { get; init; }
}
