// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'marketplace_hybrid_search' GraphQL operation.
/// </summary>
public sealed class GetMarketplaceHybridSearchVariables
{
    [JsonPropertyName("input")]
    public MarketplaceSearchInput Input { get; init; } = null!;

}
