// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'connect_board_to_object_schema' GraphQL mutation.
/// </summary>
public sealed partial class ConnectBoardToObjectSchemaRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ConnectBoardToObjectSchemaRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'connect_board_to_object_schema' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ConnectBoardToObjectSchemaData>> Execute(ConnectBoardToObjectSchemaVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ConnectBoardToObjectSchema($board_id: ID!, $object_schema_id: ID, $object_schema_name: String) { connect_board_to_object_schema(board_id: $board_id, object_schema_id: $object_schema_id, object_schema_name: $object_schema_name) { id object_schema_id } }";
        return _graphQlClient.Execute<ConnectBoardToObjectSchemaData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'connect_board_to_object_schema' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<BoardConnection?> GetValue(ConnectBoardToObjectSchemaVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ConnectBoardToObjectSchemaData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.ConnectBoardToObjectSchema;
    }
}
