// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_service_user' GraphQL mutation.
/// </summary>
public sealed partial class CreateServiceUserRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateServiceUserRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_service_user' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateServiceUserData>> Execute(CreateServiceUserVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateServiceUser($name: String!, $title: String) { create_service_user(name: $name, title: $title) { user { id title phone location birthday mobile_phone country_code current_language time_zone_identifier utc_hours_diff url account { active_members_count country_code created_at first_day_of_the_week id logo name show_timeline_weekends sign_up_product_kind slug tier is_during_trial is_trial_expired } account_products { default_workspace_id id kind tier } custom_field_metas { description editable field_type flagged icon id position title } custom_field_values { custom_field_meta_id value } enabled encrypt_api_token is_admin is_guest is_pending is_verified is_view_only join_date last_activity out_of_office { active disable_notifications end_date start_date type } photo_original photo_small photo_thumb photo_thumb_small photo_tiny sign_up_product_kind department { id name reserved_seats assigned_seats } account_id status invitation_method serial_number is_deleted photo_url { original small thumb thumb_small tiny } became_active_at bb_visitor_id is_email_confirmed user_config { kind role_id visibility behaviors group } email name kind created_at } } }";
        return _graphQlClient.Execute<CreateServiceUserData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_service_user' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<CreateServiceUserResult?> GetValue(CreateServiceUserVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateServiceUserData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateServiceUser;
    }
}
