// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_object_schema' GraphQL mutation.
/// </summary>
public sealed partial class CreateObjectSchemaRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateObjectSchemaRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_object_schema' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateObjectSchemaData>> Execute(CreateObjectSchemaVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateObjectSchema($name: String!, $parent_id: ID, $description: String) { create_object_schema(name: $name, parent_id: $parent_id, description: $description) { id account_id created_by revision created_at updated_at columns { id title type description settings policy { can_override cannot_delete read_only messages } tags { deprecated opt_in_by_default inherited } } parent_id name description connected_boards_count } }";
        return _graphQlClient.Execute<CreateObjectSchemaData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_object_schema' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ObjectSchema?> GetValue(CreateObjectSchemaVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateObjectSchemaData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateObjectSchema;
    }
}
