// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'marketplace' resource.
/// </summary>
public sealed partial class MarketplaceBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public MarketplaceBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'marketplace_ai_search' query.</summary>
    public GetMarketplaceAiSearchRequestBuilder AiSearch => new GetMarketplaceAiSearchRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'marketplace_app_discounts' query.</summary>
    public GetMarketplaceAppDiscountsRequestBuilder AppDiscounts => new GetMarketplaceAppDiscountsRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'marketplace_fulltext_search' query.</summary>
    public GetMarketplaceFulltextSearchRequestBuilder FulltextSearch => new GetMarketplaceFulltextSearchRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'marketplace_hybrid_search' query.</summary>
    public GetMarketplaceHybridSearchRequestBuilder HybridSearch => new GetMarketplaceHybridSearchRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'marketplace_vector_search' query.</summary>
    public GetMarketplaceVectorSearchRequestBuilder VectorSearch => new GetMarketplaceVectorSearchRequestBuilder(_graphQlClient);

}
