// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_status_managed_column' GraphQL operation.
/// </summary>
public sealed class UpdateStatusManagedColumnVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("title")]
    public string? Title { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("settings")]
    public UpdateStatusColumnSettingsInput? Settings { get; init; }

    [JsonPropertyName("revision")]
    public int Revision { get; init; }

}
