// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'set_item_description_content' GraphQL operation.
/// </summary>
public sealed class SetItemDescriptionContentVariables
{
    [JsonPropertyName("item_id")]
    public string ItemId { get; init; } = null!;

    [JsonPropertyName("markdown")]
    public string Markdown { get; init; } = null!;

}
