// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'addFileTo' resource.
/// </summary>
public sealed partial class AddFileToBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public AddFileToBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'add_file_to_column' mutation.</summary>
    public AddFileToColumnRequestBuilder Column => new AddFileToColumnRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'add_file_to_update' mutation.</summary>
    public AddFileToUpdateRequestBuilder Update => new AddFileToUpdateRequestBuilder(_graphQlClient);

}
