// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'create_workspace' GraphQL operation.
/// </summary>
public sealed partial class CreateWorkspaceData
{
    /// <summary>
    /// Create a new workspace.
    /// </summary>
    [JsonPropertyName("create_workspace")]
    public Workspace? CreateWorkspace { get; init; }
}
