// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Base interface for all block content types
/// </summary>
public interface DocBaseBlockContent
{
    /// <summary>
    /// The alignment of the block content
    /// </summary>
    BlockAlignment? Alignment { get; }

    /// <summary>
    /// The text direction of the block content
    /// </summary>
    BlockDirection? Direction { get; }

}
