// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'delete_form_tag' GraphQL mutation.
/// </summary>
public sealed partial class DeleteFormTagRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DeleteFormTagRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'delete_form_tag' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DeleteFormTagData>> Execute(DeleteFormTagVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DeleteFormTag($formToken: String!, $tagId: String!, $options: DeleteFormTagInput) { delete_form_tag(formToken: $formToken, tagId: $tagId, options: $options) }";
        return _graphQlClient.Execute<DeleteFormTagData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'delete_form_tag' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<bool?> GetValue(DeleteFormTagVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DeleteFormTagData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.DeleteFormTag;
    }
}
