// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'get_directory_resources' GraphQL query.
/// </summary>
public sealed partial class GetGetDirectoryResourcesRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetGetDirectoryResourcesRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'get_directory_resources' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetGetDirectoryResourcesData>> Execute(GetGetDirectoryResourcesVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetGetDirectoryResources($query_params: ItemsQuery, $cursor: String, $limit: Int) { get_directory_resources(query_params: $query_params, cursor: $cursor, limit: $limit) { id resources { id name email job_role skills location resource_type } cursor } }";
        return _graphQlClient.Execute<GetGetDirectoryResourcesData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'get_directory_resources' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<DirectoryResourcesResponse?> GetValue(GetGetDirectoryResourcesVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetGetDirectoryResourcesData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.GetDirectoryResources;
    }
}
