// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'fetch_job_status' GraphQL operation.
/// </summary>
public sealed class GetFetchJobStatusVariables
{
    [JsonPropertyName("job_id")]
    public string JobId { get; init; } = null!;

}
