// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'custom_activity' GraphQL operation.
/// </summary>
public sealed partial class GetCustomActivityData
{
    [JsonPropertyName("custom_activity")]
    public List<CustomActivity>? CustomActivity { get; init; }
}
