// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'complexity' GraphQL query.
/// </summary>
public sealed partial class GetComplexityRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetComplexityRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'complexity'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetComplexityData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetComplexity { complexity { after before query reset_in_x_seconds } }";
        return _graphQlClient.Execute<GetComplexityData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'complexity' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Complexity?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetComplexityData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.Complexity;
    }
}
