// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'connection_board_ids' GraphQL query.
/// </summary>
public sealed partial class GetConnectionBoardIdsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetConnectionBoardIdsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'connection_board_ids' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetConnectionBoardIdsData>> Execute(GetConnectionBoardIdsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetConnectionBoardIds($connection_id: ID!) { connection_board_ids(connection_id: $connection_id) }";
        return _graphQlClient.Execute<GetConnectionBoardIdsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'connection_board_ids' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<string>?> GetValue(GetConnectionBoardIdsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetConnectionBoardIdsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.ConnectionBoardIds;
    }
}
