// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'delete_doc_block' GraphQL mutation.
/// </summary>
public sealed partial class DeleteDocBlockRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DeleteDocBlockRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'delete_doc_block' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DeleteDocBlockData>> Execute(DeleteDocBlockVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DeleteDocBlock($block_id: String!) { delete_doc_block(block_id: $block_id) { id } }";
        return _graphQlClient.Execute<DeleteDocBlockData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'delete_doc_block' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<DocumentBlockIdOnly?> GetValue(DeleteDocBlockVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DeleteDocBlockData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.DeleteDocBlock;
    }
}
