// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'delete_workspace' GraphQL operation.
/// </summary>
public sealed class DeleteWorkspaceVariables
{
    [JsonPropertyName("workspace_id")]
    public string WorkspaceId { get; init; } = null!;

}
