// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'app_installs' GraphQL query.
/// </summary>
public sealed partial class GetAppInstallsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetAppInstallsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'app_installs' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetAppInstallsData>> Execute(GetAppInstallsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetAppInstalls($account_id: ID, $app_id: ID!, $limit: Int, $page: Int) { app_installs(account_id: $account_id, app_id: $app_id, limit: $limit, page: $page) { app_id app_install_account { id } app_install_user { id } app_version { major minor patch text type } permissions { approved_scopes required_scopes } timestamp } }";
        return _graphQlClient.Execute<GetAppInstallsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'app_installs' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<AppInstall>?> GetValue(GetAppInstallsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetAppInstallsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.AppInstalls;
    }
}
