// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'set_form_password' GraphQL mutation.
/// </summary>
public sealed partial class SetFormPasswordRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public SetFormPasswordRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'set_form_password' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<SetFormPasswordData>> Execute(SetFormPasswordVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation SetFormPassword($formToken: String!, $input: SetFormPasswordInput!) { set_form_password(formToken: $formToken, input: $input) { id token active title ownerId builtWithAI description questions { id type visible title description required settings { prefixAutofilled checkedByDefault defaultCurrentDate includeTime display optionsOrder locationAutofilled limit skipValidation label_limit_count label_limit_count_enabled default_answer } options { label value position visible active } showIfRules page_block_id } isAnonymous type features { isInternal reCaptchaChallenge shortenedLink { enabled url } password { enabled } draftSubmission { enabled } requireLogin { enabled redirectToLogin } responseLimit { enabled limit } closeDate { enabled date } preSubmissionView { enabled title description } afterSubmissionView { title description allowResubmit showSuccessImage allowEditSubmission allowViewSubmission } monday { itemGroupId includeNameQuestion includeUpdateQuestion syncQuestionAndColumnsTitles } ai_translate { enabled } } appearance { hideBranding showProgressBar primaryColor layout { format type alignment direction } background { type value } text { font color size } logo { position url size } submitButton { text } } accessibility { language logoAltText } tags { id name value columnId } } }";
        return _graphQlClient.Execute<SetFormPasswordData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'set_form_password' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ResponseForm?> GetValue(SetFormPasswordVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<SetFormPasswordData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.SetFormPassword;
    }
}
