// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'search' GraphQL query.
/// </summary>
public sealed partial class GetSearchRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetSearchRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'search'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetSearchData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetSearch { search { id } }";
        return _graphQlClient.Execute<GetSearchData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'search' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<SearchNamespace?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetSearchData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.Search;
    }
}
