// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'teams' GraphQL operation.
/// </summary>
public sealed partial class GetTeamsData
{
    /// <summary>
    /// Get a collection of teams.
    /// </summary>
    [JsonPropertyName("teams")]
    public List<Team>? Teams { get; init; }
}
