// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'export_markdown_from_doc' GraphQL operation.
/// </summary>
public sealed class GetExportMarkdownFromDocVariables
{
    [JsonPropertyName("docId")]
    public string DocId { get; init; } = null!;

    [JsonPropertyName("blockIds")]
    public List<string>? BlockIds { get; init; }

}
