// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'archive' resource.
/// </summary>
public sealed partial class ArchiveBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ArchiveBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'archive_board' mutation.</summary>
    public ArchiveBoardRequestBuilder Board => new ArchiveBoardRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'archive_group' mutation.</summary>
    public ArchiveGroupRequestBuilder Group => new ArchiveGroupRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'archive_item' mutation.</summary>
    public ArchiveItemRequestBuilder Item => new ArchiveItemRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'archive_object' mutation.</summary>
    public ArchiveObjectRequestBuilder Object => new ArchiveObjectRequestBuilder(_graphQlClient);

}
