// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_form_question' GraphQL operation.
/// </summary>
public sealed partial class UpdateFormQuestionData
{
    /// <summary>
    /// Update an existing question properties including title, type, or settings. Requires question ID.
    /// </summary>
    [JsonPropertyName("update_form_question")]
    public FormQuestion? UpdateFormQuestion { get; init; }
}
