// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'clear_item_updates' GraphQL operation.
/// </summary>
public sealed partial class ClearItemUpdatesData
{
    /// <summary>
    /// Clear an item's updates.
    /// </summary>
    [JsonPropertyName("clear_item_updates")]
    public Item? ClearItemUpdates { get; init; }
}
