// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'notetaker' GraphQL operation.
/// </summary>
public sealed partial class GetNotetakerData
{
    /// <summary>
    /// Namespace for all notetaker-related queries.
    /// </summary>
    [JsonPropertyName("notetaker")]
    public NotetakerQueries? Notetaker { get; init; }
}
