// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'insights' GraphQL query.
/// </summary>
public sealed partial class GetInsightsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetInsightsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'insights' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetInsightsData>> Execute(GetInsightsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetInsights($limit: Int) { insights(limit: $limit) { id title summary target_audience audience_rationale campaign_worthiness timestamp source raw_context created_at updated_at status type } }";
        return _graphQlClient.Execute<GetInsightsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'insights' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<CampaignsInsight>?> GetValue(GetInsightsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetInsightsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.Insights;
    }
}
