// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_department' GraphQL operation.
/// </summary>
public sealed class UpdateDepartmentVariables
{
    [JsonPropertyName("department_id")]
    public string DepartmentId { get; init; } = null!;

    [JsonPropertyName("data")]
    public UpdateDepartmentOptionsInput? Data { get; init; }

}
