// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_favorite' GraphQL operation.
/// </summary>
public sealed class CreateFavoriteVariables
{
    [JsonPropertyName("input")]
    public CreateFavoriteInput Input { get; init; } = null!;

}
