// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_workspace' GraphQL mutation.
/// </summary>
public sealed partial class CreateWorkspaceRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateWorkspaceRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_workspace' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateWorkspaceData>> Execute(CreateWorkspaceVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateWorkspace($account_product_id: ID, $description: String, $kind: WorkspaceKind!, $name: String!) { create_workspace(account_product_id: $account_product_id, description: $description, kind: $kind, name: $name) { id account_product { default_workspace_id id kind tier } created_at description is_default_workspace kind name settings { icon { color image } } state } }";
        return _graphQlClient.Execute<CreateWorkspaceData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_workspace' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Workspace?> GetValue(CreateWorkspaceVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateWorkspaceData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateWorkspace;
    }
}
