// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_workspace' GraphQL operation.
/// </summary>
public sealed class CreateWorkspaceVariables
{
    [JsonPropertyName("account_product_id")]
    public string? AccountProductId { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("kind")]
    public WorkspaceKind Kind { get; init; }

    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

}
