// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'connections' GraphQL operation.
/// </summary>
public sealed partial class GetConnectionsData
{
    /// <summary>
    /// Returns connections for the authenticated user. Supports filtering, pagination, ordering, and partial-scope options.
    /// </summary>
    [JsonPropertyName("connections")]
    public List<Connection>? Connections { get; init; }
}
