// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'add_users_to_workspace' GraphQL operation.
/// </summary>
public sealed partial class AddUsersToWorkspaceData
{
    /// <summary>
    /// Add users to a workspace.
    /// </summary>
    [JsonPropertyName("add_users_to_workspace")]
    public List<User>? AddUsersToWorkspace { get; init; }
}
