// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_item' GraphQL operation.
/// </summary>
public sealed partial class DeleteItemData
{
    /// <summary>
    /// Delete an item.
    /// </summary>
    [JsonPropertyName("delete_item")]
    public Item? DeleteItem { get; init; }
}
