// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'user' resource.
/// </summary>
public sealed partial class UserBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public UserBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'user_configs' query.</summary>
    public GetUserConfigsRequestBuilder Configs => new GetUserConfigsRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'user_connections' query.</summary>
    public GetUserConnectionsRequestBuilder Connections => new GetUserConnectionsRequestBuilder(_graphQlClient);

}
