// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'batch_extend_trial_period' GraphQL operation.
/// </summary>
public sealed partial class BatchExtendTrialPeriodData
{
    /// <summary>
    /// Extends trial period of an application to selected accounts
    /// </summary>
    [JsonPropertyName("batch_extend_trial_period")]
    public BatchExtendTrialPeriod? BatchExtendTrialPeriod { get; init; }
}
