// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_board_hierarchy' GraphQL operation.
/// </summary>
public sealed class UpdateBoardHierarchyVariables
{
    [JsonPropertyName("attributes")]
    public UpdateBoardHierarchyAttributesInput Attributes { get; init; } = null!;

    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

}
