// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'service_users' GraphQL query.
/// </summary>
public sealed partial class GetServiceUsersRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetServiceUsersRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'service_users'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetServiceUsersData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetServiceUsers { service_users { id name title enabled invited_by_id created_at last_token_activity has_token } }";
        return _graphQlClient.Execute<GetServiceUsersData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'service_users' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<ServiceUser>?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetServiceUsersData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.ServiceUsers;
    }
}
