// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'marketplace_app_discounts' GraphQL query.
/// </summary>
public sealed partial class GetMarketplaceAppDiscountsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetMarketplaceAppDiscountsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'marketplace_app_discounts' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetMarketplaceAppDiscountsData>> Execute(GetMarketplaceAppDiscountsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetMarketplaceAppDiscounts($app_id: ID!) { marketplace_app_discounts(app_id: $app_id) { account_slug account_id discount is_recurring app_plan_ids period valid_until created_at } }";
        return _graphQlClient.Execute<GetMarketplaceAppDiscountsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'marketplace_app_discounts' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<MarketplaceAppDiscount>?> GetValue(GetMarketplaceAppDiscountsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetMarketplaceAppDiscountsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.MarketplaceAppDiscounts;
    }
}
