// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'marketplace_app_discounts' GraphQL operation.
/// </summary>
public sealed partial class GetMarketplaceAppDiscountsData
{
    [JsonPropertyName("marketplace_app_discounts")]
    public List<MarketplaceAppDiscount> MarketplaceAppDiscounts { get; init; } = [];
}
