// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'revoke_service_user_tokens' GraphQL operation.
/// </summary>
public sealed partial class RevokeServiceUserTokensData
{
    /// <summary>
    /// Revokes all API tokens for a service user.
    /// </summary>
    [JsonPropertyName("revoke_service_user_tokens")]
    public bool? RevokeServiceUserTokens { get; init; }
}
