// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'create_doc_block' GraphQL operation.
/// </summary>
public sealed partial class CreateDocBlockData
{
    /// <summary>
    /// Create new document block
    /// </summary>
    [JsonPropertyName("create_doc_block")]
    public DocumentBlock? CreateDocBlock { get; init; }
}
