// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'delete_team' GraphQL mutation.
/// </summary>
public sealed partial class DeleteTeamRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DeleteTeamRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'delete_team' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DeleteTeamData>> Execute(DeleteTeamVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DeleteTeam($team_id: ID!) { delete_team(team_id: $team_id) { id is_guest name created_at picture_url } }";
        return _graphQlClient.Execute<DeleteTeamData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'delete_team' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Team?> GetValue(DeleteTeamVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DeleteTeamData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.DeleteTeam;
    }
}
