// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'attach_status_managed_column' GraphQL operation.
/// </summary>
public sealed class AttachStatusManagedColumnVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("managed_column_id")]
    public string ManagedColumnId { get; init; } = null!;

    [JsonPropertyName("title")]
    public string? Title { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("after_column_id")]
    public string? AfterColumnId { get; init; }

}
