// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_notification_setting' GraphQL operation.
/// </summary>
public sealed class UpdateNotificationSettingVariables
{
    [JsonPropertyName("scope_type")]
    public ScopeType ScopeType { get; init; }

    [JsonPropertyName("scope_id")]
    public int? ScopeId { get; init; }

    [JsonPropertyName("setting_kind")]
    public string SettingKind { get; init; } = null!;

    [JsonPropertyName("channel")]
    public ChannelType Channel { get; init; }

    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

}
