// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'update_notification_setting' GraphQL mutation.
/// </summary>
public sealed partial class UpdateNotificationSettingRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public UpdateNotificationSettingRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'update_notification_setting' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<UpdateNotificationSettingData>> Execute(UpdateNotificationSettingVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation UpdateNotificationSetting($scope_type: ScopeType!, $scope_id: Int, $setting_kind: String!, $channel: ChannelType!, $enabled: Boolean!) { update_notification_setting(scope_type: $scope_type, scope_id: $scope_id, setting_kind: $setting_kind, channel: $channel, enabled: $enabled) { kind description is_for_admins_only is_for_non_guests_only channels { name enabled editable_status } } }";
        return _graphQlClient.Execute<UpdateNotificationSettingData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'update_notification_setting' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<NotificationSetting>?> GetValue(UpdateNotificationSettingVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<UpdateNotificationSettingData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.UpdateNotificationSetting;
    }
}
