// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'create_form_tag' GraphQL operation.
/// </summary>
public sealed partial class CreateFormTagData
{
    /// <summary>
    /// Create a new tag for a form. Tags are used to categorize and track responses. (e.g. UTM tags)
    /// </summary>
    [JsonPropertyName("create_form_tag")]
    public FormTag? CreateFormTag { get; init; }
}
