// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_status_column' GraphQL operation.
/// </summary>
public sealed partial class UpdateStatusColumnData
{
    /// <summary>
    /// Updates a status column's properties including title, description, and status label settings. Status columns allow users to track item progress through customizable labels (e.g., "Working on it", "Done", "Stuck"). This mutation is specifically for status/color columns and provides type-safe updates.
    /// </summary>
    [JsonPropertyName("update_status_column")]
    public Column? UpdateStatusColumn { get; init; }
}
