// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'mute_board_settings' GraphQL operation.
/// </summary>
public sealed partial class GetMuteBoardSettingsData
{
    /// <summary>
    /// Get mute board notification settings for the current user
    /// </summary>
    [JsonPropertyName("mute_board_settings")]
    public List<BoardMuteSettings>? MuteBoardSettings { get; init; }
}
