// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'form' GraphQL operation.
/// </summary>
public sealed class GetFormVariables
{
    [JsonPropertyName("formToken")]
    public string FormToken { get; init; } = null!;

}
