// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'notifications' GraphQL operation.
/// </summary>
public sealed partial class GetNotificationsData
{
    [JsonPropertyName("notifications")]
    public List<NotificationV2>? Notifications { get; init; }
}
