// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'regenerate_service_user_token' GraphQL operation.
/// </summary>
public sealed class RegenerateServiceUserTokenVariables
{
    [JsonPropertyName("service_user_id")]
    public string ServiceUserId { get; init; } = null!;

}
