// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'regenerate_service_user_token' GraphQL mutation.
/// </summary>
public sealed partial class RegenerateServiceUserTokenRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public RegenerateServiceUserTokenRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'regenerate_service_user_token' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<RegenerateServiceUserTokenData>> Execute(RegenerateServiceUserTokenVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation RegenerateServiceUserToken($service_user_id: ID!) { regenerate_service_user_token(service_user_id: $service_user_id) }";
        return _graphQlClient.Execute<RegenerateServiceUserTokenData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'regenerate_service_user_token' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<string?> GetValue(RegenerateServiceUserTokenVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<RegenerateServiceUserTokenData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.RegenerateServiceUserToken;
    }
}
