// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'uninstall_app' GraphQL operation.
/// </summary>
public sealed partial class UninstallAppData
{
    /// <summary>
    /// Uninstalls an app from the current account. Requires account admin permission.
    /// </summary>
    [JsonPropertyName("uninstall_app")]
    public AppDeletionResponse? UninstallApp { get; init; }
}
