// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'connect' resource.
/// </summary>
public sealed partial class ConnectBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ConnectBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'connect_board_to_object_schema' mutation.</summary>
    public ConnectBoardToObjectSchemaRequestBuilder BoardToObjectSchema => new ConnectBoardToObjectSchemaRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'connect_project_to_portfolio' mutation.</summary>
    public ConnectProjectToPortfolioRequestBuilder ProjectToPortfolio => new ConnectProjectToPortfolioRequestBuilder(_graphQlClient);

}
