// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_object' GraphQL operation.
/// </summary>
public sealed partial class UpdateObjectData
{
    /// <summary>
    /// Updates an object.
    /// </summary>
    [JsonPropertyName("update_object")]
    public Object? UpdateObject { get; init; }
}
