// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'archive_group' GraphQL operation.
/// </summary>
public sealed partial class ArchiveGroupData
{
    /// <summary>
    /// Archives a group in a specific board.
    /// </summary>
    [JsonPropertyName("archive_group")]
    public Group? ArchiveGroup { get; init; }
}
