// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'dependency_column_config' GraphQL query.
/// </summary>
public sealed partial class GetDependencyColumnConfigRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetDependencyColumnConfigRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'dependency_column_config' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetDependencyColumnConfigData>> Execute(GetDependencyColumnConfigVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetDependencyColumnConfig($board_id: ID!, $account_id: ID!, $user_id: ID!) { dependency_column_config(board_id: $board_id, account_id: $account_id, user_id: $user_id) { board_id dependency_columns { id account_id board_id data created_at updated_at config_type } } }";
        return _graphQlClient.Execute<GetDependencyColumnConfigData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'dependency_column_config' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<DependencyColumnConfigResult?> GetValue(GetDependencyColumnConfigVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetDependencyColumnConfigData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.DependencyColumnConfig;
    }
}
