// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'pin_to_top' GraphQL operation.
/// </summary>
public sealed class PinToTopVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("item_id")]
    public string? ItemId { get; init; }

}
