// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_status_column' GraphQL operation.
/// </summary>
public sealed class UpdateStatusColumnVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("title")]
    public string? Title { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("width")]
    public int? Width { get; init; }

    [JsonPropertyName("revision")]
    public string Revision { get; init; } = null!;

    [JsonPropertyName("capabilities")]
    public StatusColumnCapabilitiesInput? Capabilities { get; init; }

    [JsonPropertyName("settings")]
    public UpdateStatusColumnSettingsInput? Settings { get; init; }

}
