// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'set_mock_app_subscription' GraphQL operation.
/// </summary>
public sealed class SetMockAppSubscriptionVariables
{
    [JsonPropertyName("app_id")]
    public string AppId { get; init; } = null!;

    [JsonPropertyName("billing_period")]
    public string? BillingPeriod { get; init; }

    [JsonPropertyName("is_trial")]
    public bool? IsTrial { get; init; }

    [JsonPropertyName("max_units")]
    public int? MaxUnits { get; init; }

    [JsonPropertyName("partial_signing_secret")]
    public string PartialSigningSecret { get; init; } = null!;

    [JsonPropertyName("plan_id")]
    public string? PlanId { get; init; }

    [JsonPropertyName("pricing_version")]
    public int? PricingVersion { get; init; }

    [JsonPropertyName("renewal_date")]
    public DateOnly? RenewalDate { get; init; }

}
