// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_doc_name' GraphQL operation.
/// </summary>
public sealed class UpdateDocNameVariables
{
    [JsonPropertyName("docId")]
    public string DocId { get; init; } = null!;

    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

}
