// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'update_doc_name' GraphQL mutation.
/// </summary>
public sealed partial class UpdateDocNameRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public UpdateDocNameRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'update_doc_name' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<UpdateDocNameData>> Execute(UpdateDocNameVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation UpdateDocName($docId: ID!, $name: String!) { update_doc_name(docId: $docId, name: $name) }";
        return _graphQlClient.Execute<UpdateDocNameData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'update_doc_name' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<string?> GetValue(UpdateDocNameVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<UpdateDocNameData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.UpdateDocName;
    }
}
