// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'add_subscribers_to_board' GraphQL operation.
/// </summary>
public sealed partial class AddSubscribersToBoardData
{
    /// <summary>
    /// Add subscribers to a board.
    /// </summary>
    [JsonPropertyName("add_subscribers_to_board")]
    public List<User>? AddSubscribersToBoard { get; init; }
}
