// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'user_configs' GraphQL query.
/// </summary>
public sealed partial class GetUserConfigsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetUserConfigsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'user_configs' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetUserConfigsData>> Execute(GetUserConfigsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetUserConfigs($kinds: [String!], $visibility: String, $behaviors: [String!]) { user_configs(kinds: $kinds, visibility: $visibility, behaviors: $behaviors) { kind role_id visibility behaviors group } }";
        return _graphQlClient.Execute<GetUserConfigsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'user_configs' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<UserConfig>?> GetValue(GetUserConfigsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetUserConfigsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.UserConfigs;
    }
}
