// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'increase_app_subscription_operations' GraphQL operation.
/// </summary>
public sealed partial class IncreaseAppSubscriptionOperationsData
{
    /// <summary>
    /// Increase operations counter
    /// </summary>
    [JsonPropertyName("increase_app_subscription_operations")]
    public AppSubscriptionOperationsCounter? IncreaseAppSubscriptionOperations { get; init; }
}
