// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_project' GraphQL mutation.
/// </summary>
public sealed partial class CreateProjectRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateProjectRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_project' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateProjectData>> Execute(CreateProjectVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateProject($input: CreateProjectInput!) { create_project(input: $input) { success message error process_id } }";
        return _graphQlClient.Execute<CreateProjectData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_project' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<CreateProjectResult?> GetValue(CreateProjectVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateProjectData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateProject;
    }
}
