// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'duplicate_board' GraphQL operation.
/// </summary>
public sealed class DuplicateBoardVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("board_name")]
    public string? BoardName { get; init; }

    [JsonPropertyName("duplicate_type")]
    public DuplicateBoardType DuplicateType { get; init; }

    [JsonPropertyName("folder_id")]
    public string? FolderId { get; init; }

    [JsonPropertyName("keep_subscribers")]
    public bool? KeepSubscribers { get; init; }

    [JsonPropertyName("workspace_id")]
    public string? WorkspaceId { get; init; }

}
