// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'ingest_items' GraphQL mutation.
/// </summary>
public sealed partial class IngestItemsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public IngestItemsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'ingest_items' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<IngestItemsData>> Execute(IngestItemsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation IngestItems($board_id: ID!, $group_id: ID!, $on_match: OnMatchInput) { ingest_items(board_id: $board_id, group_id: $group_id, on_match: $on_match) { job_id upload_url } }";
        return _graphQlClient.Execute<IngestItemsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'ingest_items' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<UploadJobInit?> GetValue(IngestItemsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<IngestItemsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.IngestItems;
    }
}
