// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'ingest_items' GraphQL operation.
/// </summary>
public sealed class IngestItemsVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("group_id")]
    public string GroupId { get; init; } = null!;

    [JsonPropertyName("on_match")]
    public OnMatchInput? OnMatch { get; init; }

}
