// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_custom_activity' GraphQL mutation.
/// </summary>
public sealed partial class CreateCustomActivityRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateCustomActivityRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_custom_activity' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateCustomActivityData>> Execute(CreateCustomActivityVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateCustomActivity($name: String!, $icon_id: CustomActivityIcon!, $color: CustomActivityColor!) { create_custom_activity(name: $name, icon_id: $icon_id, color: $color) { id type name icon_id color } }";
        return _graphQlClient.Execute<CreateCustomActivityData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_custom_activity' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<CustomActivity?> GetValue(CreateCustomActivityVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateCustomActivityData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateCustomActivity;
    }
}
