// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'app_installs' GraphQL operation.
/// </summary>
public sealed partial class GetAppInstallsData
{
    /// <summary>
    /// Get a collection of installs of an app.
    /// </summary>
    [JsonPropertyName("app_installs")]
    public List<AppInstall>? AppInstalls { get; init; }
}
