// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'duplicate_item' GraphQL operation.
/// </summary>
public sealed class DuplicateItemVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("item_id")]
    public string? ItemId { get; init; }

    [JsonPropertyName("with_updates")]
    public bool? WithUpdates { get; init; }

}
