// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'grant_marketplace_app_discount' GraphQL operation.
/// </summary>
public sealed class GrantMarketplaceAppDiscountVariables
{
    [JsonPropertyName("app_id")]
    public string AppId { get; init; } = null!;

    [JsonPropertyName("account_slug")]
    public string AccountSlug { get; init; } = null!;

    [JsonPropertyName("data")]
    public GrantMarketplaceAppDiscountData Data { get; init; } = null!;

}
