// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_group' GraphQL operation.
/// </summary>
public sealed partial class DeleteGroupData
{
    /// <summary>
    /// Deletes a group in a specific board.
    /// </summary>
    [JsonPropertyName("delete_group")]
    public Group? DeleteGroup { get; init; }
}
