// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'activate_managed_column' GraphQL mutation.
/// </summary>
public sealed partial class ActivateManagedColumnRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ActivateManagedColumnRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'activate_managed_column' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ActivateManagedColumnData>> Execute(ActivateManagedColumnVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ActivateManagedColumn($id: String!) { activate_managed_column(id: $id) { id title description settings_json created_by updated_by revision state created_at updated_at } }";
        return _graphQlClient.Execute<ActivateManagedColumnData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'activate_managed_column' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ManagedColumn?> GetValue(ActivateManagedColumnVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ActivateManagedColumnData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.ActivateManagedColumn;
    }
}
