// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'apps_monetization_info' GraphQL query.
/// </summary>
public sealed partial class GetAppsMonetizationInfoRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetAppsMonetizationInfoRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'apps_monetization_info'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetAppsMonetizationInfoData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetAppsMonetizationInfo { apps_monetization_info { seats_count } }";
        return _graphQlClient.Execute<GetAppsMonetizationInfoData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'apps_monetization_info' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<AppsMonetizationInfo?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetAppsMonetizationInfoData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.AppsMonetizationInfo;
    }
}
