// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'updates' GraphQL operation.
/// </summary>
public sealed partial class GetUpdatesData
{
    [JsonPropertyName("updates")]
    public List<Update>? Updates { get; init; }
}
