// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_form_question' GraphQL operation.
/// </summary>
public sealed class UpdateFormQuestionVariables
{
    [JsonPropertyName("formToken")]
    public string FormToken { get; init; } = null!;

    [JsonPropertyName("questionId")]
    public string QuestionId { get; init; } = null!;

    [JsonPropertyName("question")]
    public UpdateQuestionInput Question { get; init; } = null!;

}
