// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'update_form_question' GraphQL mutation.
/// </summary>
public sealed partial class UpdateFormQuestionRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public UpdateFormQuestionRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'update_form_question' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<UpdateFormQuestionData>> Execute(UpdateFormQuestionVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation UpdateFormQuestion($formToken: String!, $questionId: String!, $question: UpdateQuestionInput!) { update_form_question(formToken: $formToken, questionId: $questionId, question: $question) { id type visible title description required settings { prefill { enabled source lookup } prefixAutofilled prefixPredefined { enabled prefix } checkedByDefault defaultCurrentDate includeTime display optionsOrder locationAutofilled limit skipValidation label_limit_count label_limit_count_enabled default_answer } options { label value position visible active } showIfRules page_block_id } }";
        return _graphQlClient.Execute<UpdateFormQuestionData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'update_form_question' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<FormQuestion?> GetValue(UpdateFormQuestionVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<UpdateFormQuestionData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.UpdateFormQuestion;
    }
}
