// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'add_teams_to_workspace' GraphQL mutation.
/// </summary>
public sealed partial class AddTeamsToWorkspaceRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public AddTeamsToWorkspaceRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'add_teams_to_workspace' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<AddTeamsToWorkspaceData>> Execute(AddTeamsToWorkspaceVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation AddTeamsToWorkspace($kind: WorkspaceSubscriberKind, $team_ids: [ID!]!, $workspace_id: ID!) { add_teams_to_workspace(kind: $kind, team_ids: $team_ids, workspace_id: $workspace_id) { id is_guest name created_at picture_url } }";
        return _graphQlClient.Execute<AddTeamsToWorkspaceData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'add_teams_to_workspace' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<Team>?> GetValue(AddTeamsToWorkspaceVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<AddTeamsToWorkspaceData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.AddTeamsToWorkspace;
    }
}
