// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'createDropdown' resource.
/// </summary>
public sealed partial class CreateDropdownBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateDropdownBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'create_dropdown_column' mutation.</summary>
    public CreateDropdownColumnRequestBuilder Column => new CreateDropdownColumnRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'create_dropdown_managed_column' mutation.</summary>
    public CreateDropdownManagedColumnRequestBuilder ManagedColumn => new CreateDropdownManagedColumnRequestBuilder(_graphQlClient);

}
