// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'update_article_block' GraphQL operation.
/// </summary>
public sealed class UpdateArticleBlockVariables
{
    [JsonPropertyName("block_id")]
    public string BlockId { get; init; } = null!;

    [JsonPropertyName("content")]
    public string Content { get; init; } = null!;

}
