// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_widget' GraphQL operation.
/// </summary>
public sealed partial class DeleteWidgetData
{
    /// <summary>
    /// Delete an existing widget.
    /// </summary>
    [JsonPropertyName("delete_widget")]
    public bool? DeleteWidget { get; init; }
}
