// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'account_triggers_statistics_by_entity_id' GraphQL operation.
/// </summary>
public sealed partial class GetAccountTriggersStatisticsByEntityIdData
{
    /// <summary>
    /// Get aggregated automation runs statistics grouped by entity Ids
    /// </summary>
    [JsonPropertyName("account_triggers_statistics_by_entity_id")]
    public AccountTriggersByEntityId? AccountTriggersStatisticsByEntityId { get; init; }
}
