// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'add_teams_to_board' GraphQL operation.
/// </summary>
public sealed class AddTeamsToBoardVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("kind")]
    public BoardSubscriberKind? Kind { get; init; }

    [JsonPropertyName("team_ids")]
    public List<string> TeamIds { get; init; } = [];

}
