// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'update_column' GraphQL mutation.
/// </summary>
public sealed partial class UpdateColumnRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public UpdateColumnRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'update_column' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<UpdateColumnData>> Execute(UpdateColumnVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation UpdateColumn($board_id: ID!, $id: String!, $title: String, $description: String, $width: Int, $revision: String!, $capabilities: ColumnCapabilitiesInput, $settings: JSON, $column_type: ColumnType!) { update_column(board_id: $board_id, id: $id, title: $title, description: $description, width: $width, revision: $revision, capabilities: $capabilities, settings: $settings, column_type: $column_type) { id title description type width archived settings settings_str revision capabilities { calculated { function calculated_type } visibility } } }";
        return _graphQlClient.Execute<UpdateColumnData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'update_column' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Column?> GetValue(UpdateColumnVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<UpdateColumnData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.UpdateColumn;
    }
}
