// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'board_candidates' GraphQL operation.
/// </summary>
public sealed class GetBoardCandidatesVariables
{
    [JsonPropertyName("workspaceId")]
    public string WorkspaceId { get; init; } = null!;

    [JsonPropertyName("usageType")]
    public BoardUsage UsageType { get; init; }

}
