// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_notification' GraphQL operation.
/// </summary>
public sealed class CreateNotificationVariables
{
    [JsonPropertyName("target_id")]
    public string TargetId { get; init; } = null!;

    [JsonPropertyName("target_type")]
    public NotificationTargetType TargetType { get; init; }

    [JsonPropertyName("text")]
    public string Text { get; init; } = null!;

    [JsonPropertyName("user_id")]
    public string UserId { get; init; } = null!;

}
