// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'ask_developer_docs' GraphQL query.
/// </summary>
public sealed partial class GetAskDeveloperDocsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetAskDeveloperDocsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'ask_developer_docs' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetAskDeveloperDocsData>> Execute(GetAskDeveloperDocsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetAskDeveloperDocs($query: String!) { ask_developer_docs(query: $query) { id question answer conversation_id } }";
        return _graphQlClient.Execute<GetAskDeveloperDocsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'ask_developer_docs' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<AppDocumentationAiResponse?> GetValue(GetAskDeveloperDocsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetAskDeveloperDocsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.AskDeveloperDocs;
    }
}
