// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'set' resource.
/// </summary>
public sealed partial class SetBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public SetBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'set_board_permission' mutation.</summary>
    public SetBoardPermissionRequestBuilder BoardPermission => new SetBoardPermissionRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'set_form_password' mutation.</summary>
    public SetFormPasswordRequestBuilder FormPassword => new SetFormPasswordRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'set_item_description_content' mutation.</summary>
    public SetItemDescriptionContentRequestBuilder ItemDescriptionContent => new SetItemDescriptionContentRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'set_mock_app_subscription' mutation.</summary>
    public SetMockAppSubscriptionRequestBuilder MockAppSubscription => new SetMockAppSubscriptionRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'set_object_schema_column_active_state' mutation.</summary>
    public SetObjectSchemaColumnActiveStateRequestBuilder ObjectSchemaColumnActiveState => new SetObjectSchemaColumnActiveStateRequestBuilder(_graphQlClient);

}
