// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'change_column_metadata' GraphQL mutation.
/// </summary>
public sealed partial class ChangeColumnMetadataRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ChangeColumnMetadataRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'change_column_metadata' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ChangeColumnMetadataData>> Execute(ChangeColumnMetadataVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ChangeColumnMetadata($board_id: ID!, $column_id: String!, $column_property: ColumnProperty, $value: String) { change_column_metadata(board_id: $board_id, column_id: $column_id, column_property: $column_property, value: $value) { id title description type width archived settings settings_str revision capabilities { calculated { function calculated_type } visibility } } }";
        return _graphQlClient.Execute<ChangeColumnMetadataData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'change_column_metadata' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Column?> GetValue(ChangeColumnMetadataVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ChangeColumnMetadataData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.ChangeColumnMetadata;
    }
}
