// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_favorite' GraphQL operation.
/// </summary>
public sealed partial class DeleteFavoriteData
{
    /// <summary>
    /// Remove an object from favorites
    /// </summary>
    [JsonPropertyName("delete_favorite")]
    public DeleteFavoriteInputResultType? DeleteFavorite { get; init; }
}
