// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class AggregateSelectFunctionInput
{
    /// <summary>
    /// Function to select. Required if type is FUNCTION
    /// </summary>
    [JsonPropertyName("function")]
    public AggregateSelectFunctionName Function { get; init; }

    [JsonPropertyName("params")]
    public List<AggregateSelectElementInput>? @Params { get; init; }

}
