// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Optional settings controlling backfill behavior when configuring an AI column.
/// </summary>
public sealed partial class AiColumnExtraSettingsInput
{
    /// <summary>
    /// Whether to immediately apply the AI automation to existing items. Defaults to true.
    /// </summary>
    [JsonPropertyName("run_backfill")]
    public bool? RunBackfill { get; init; }

}
