// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for updating an app feature release.
/// </summary>
public sealed partial class AppFeatureReleaseInput
{
    /// <summary>
    /// The hosting type for the release. The app release category will be automatically determined based on this value.
    /// </summary>
    [JsonPropertyName("kind")]
    public AppFeatureReleaseKind? Kind { get; init; }

    /// <summary>
    /// The data of the release.
    /// </summary>
    [JsonPropertyName("data")]
    public AppFeatureReleaseDataInput? Data { get; init; }

}
