// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Boost configuration for search results. Key-value pairs where key is strategy type and value is boost weight.
/// </summary>
public sealed partial class BoostConfigurationInput
{
    /// <summary>
    /// Boost strategies as key-value pairs (strategy: weight). Empty object {} disables all boosts.
    /// </summary>
    [JsonPropertyName("boosts")]
    public string? Boosts { get; init; }

}
