// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for a file attached to a chat message
/// </summary>
public sealed partial class ChatMessageFileInput
{
    /// <summary>
    /// The S3 key where the file is stored
    /// </summary>
    [JsonPropertyName("s3_key")]
    public string S3Key { get; init; } = null!;

    /// <summary>
    /// The original file name
    /// </summary>
    [JsonPropertyName("file_name")]
    public string FileName { get; init; } = null!;

    /// <summary>
    /// The MIME type of the file
    /// </summary>
    [JsonPropertyName("mime_type")]
    public AllowedFileMime MimeType { get; init; }

}
