// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class ConditionalFormattingFormattingInput
{
    /// <summary>
    /// Color name to apply as highlight (e.g. orange, dark_red, done-green)
    /// </summary>
    [JsonPropertyName("highlight_color")]
    public string? HighlightColor { get; init; }

}
