// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A single conditional formatting condition that defines when and how to highlight rows or cells
/// </summary>
public sealed partial class ConditionalFormattingConditionInput
{
    /// <summary>
    /// Unique identifier for the condition (client-generated GUID)
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The formatting to apply when this condition matches
    /// </summary>
    [JsonPropertyName("formatting")]
    public ConditionalFormattingFormattingInput? Formatting { get; init; }

    /// <summary>
    /// Rules that trigger this condition
    /// </summary>
    [JsonPropertyName("rules")]
    public List<ConditionalFormattingRuleBucketInput>? Rules { get; init; }

    /// <summary>
    /// What to highlight when the condition matches
    /// </summary>
    [JsonPropertyName("target")]
    public ConditionalFormattingTargetInput? Target { get; init; }

}
