// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Mapping between source and target columns for a connected board.
/// </summary>
public sealed partial class ConnectedBoardColumnMappingInput
{
    /// <summary>
    /// The unique identifier of the source column in the mapping.
    /// </summary>
    [JsonPropertyName("source_column_id")]
    public string SourceColumnId { get; init; } = null!;

    /// <summary>
    /// The unique identifier of the target column in the mapping.
    /// </summary>
    [JsonPropertyName("target_column_id")]
    public string TargetColumnId { get; init; } = null!;

}
