// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A connected board with optional column mappings.
/// </summary>
public sealed partial class ConnectedBoardInput
{
    /// <summary>
    /// The unique identifier of the connected board.
    /// </summary>
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    /// <summary>
    /// Column mappings between the linked boards.
    /// </summary>
    [JsonPropertyName("mappings")]
    public List<ConnectedBoardColumnMappingInput>? Mappings { get; init; }

}
