// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class CreateFormTagInput
{
    /// <summary>
    /// The name of the tag. Must be unique within the form and not reserved.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The value of the tag
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

}
