// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Choose one specific block type to create.
/// 
/// 💡 TIP: Before using table_block, consider add_content_to_doc_from_markdown for tables with data.
/// 
/// table_block creates empty structure requiring manual cell population.
/// </summary>
public sealed partial class CreateBlockInput
{
    /// <summary>
    /// Create a text block (normal text, titles)
    /// </summary>
    [JsonPropertyName("text_block")]
    public TextBlockInput? TextBlock { get; init; }

    /// <summary>
    /// Create a list block (bulleted, numbered, checklist)
    /// </summary>
    [JsonPropertyName("list_block")]
    public ListBlockInput? ListBlock { get; init; }

    /// <summary>
    /// The notice-box's own ID must be captured.  Every block that should appear inside it must be created with parentBlockId = that ID (and can still use afterBlockId for ordering among siblings).
    /// </summary>
    [JsonPropertyName("notice_box_block")]
    public NoticeBoxBlockInput? NoticeBoxBlock { get; init; }

    /// <summary>
    /// Create an image block
    /// </summary>
    [JsonPropertyName("image_block")]
    public ImageBlockInput? ImageBlock { get; init; }

    /// <summary>
    /// Create a video block
    /// </summary>
    [JsonPropertyName("video_block")]
    public VideoBlockInput? VideoBlock { get; init; }

    /// <summary>
    /// Create a table block. Capture its returned ID; nest child blocks by setting parentBlockId to that ID and use afterBlockId for sibling ordering.
    /// </summary>
    [JsonPropertyName("table_block")]
    public TableBlockInput? TableBlock { get; init; }

    /// <summary>
    /// Create a layout block. Capture its returned ID; nest child blocks by setting parentBlockId to that ID and use afterBlockId for sibling ordering.
    /// </summary>
    [JsonPropertyName("layout_block")]
    public LayoutBlockInput? LayoutBlock { get; init; }

    /// <summary>
    /// Create a divider block
    /// </summary>
    [JsonPropertyName("divider_block")]
    public DividerBlockInput? DividerBlock { get; init; }

    /// <summary>
    /// Create a page break block
    /// </summary>
    [JsonPropertyName("page_break_block")]
    public PageBreakBlockInput? PageBreakBlock { get; init; }

}
