// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class CreateStatusLabelInput
{
    [JsonPropertyName("label")]
    public string Label { get; init; } = null!;

    [JsonPropertyName("color")]
    public StatusColumnColors Color { get; init; }

    [JsonPropertyName("index")]
    public int Index { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("is_done")]
    public bool? IsDone { get; init; }

}
