// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for creating a new task
/// </summary>
public sealed partial class CreateTaskInput
{
    /// <summary>
    /// The task title
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = null!;

    /// <summary>
    /// The task description (default: empty string)
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// The initial status (default: TODO)
    /// </summary>
    [JsonPropertyName("status")]
    public CreateTaskStatus? Status { get; init; }

    /// <summary>
    /// The task priority (default: 0)
    /// </summary>
    [JsonPropertyName("priority")]
    public int? Priority { get; init; }

    /// <summary>
    /// The task due date, if any
    /// </summary>
    [JsonPropertyName("due_date")]
    public string? DueDate { get; init; }

}
