// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input type for adding an object to a hierarchy list
/// </summary>
public sealed partial class CreateFavoriteInput
{
    /// <summary>
    /// The object to add to the list
    /// </summary>
    [JsonPropertyName("object")]
    public HierarchyObjectIDInputType @Object { get; init; } = null!;

    /// <summary>
    /// The name of the object
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// The position where to add the object
    /// </summary>
    [JsonPropertyName("newPosition")]
    public ObjectDynamicPositionInput? NewPosition { get; init; }

}
