// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for creating a new time off schedule
/// </summary>
public sealed partial class CreateTimeOffInput
{
    /// <summary>
    /// Display name for the new time off schedule
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// Non-working date entries to create alongside the schedule. Subsequent additions/updates use the dedicated time off entry mutations.
    /// </summary>
    [JsonPropertyName("entries")]
    public List<TimeOffEntryInput>? Entries { get; init; }

}
