// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for creating a new column on an object schema
/// </summary>
public sealed partial class CreateObjectSchemaColumnInput
{
    /// <summary>
    /// The column type (e.g., "status", "dropdown", "text", "date")
    /// </summary>
    [JsonPropertyName("type")]
    public ColumnType Type { get; init; }

    /// <summary>
    /// The column title
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = null!;

    /// <summary>
    /// Optional column description
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Type-specific configuration object containing column defaults and settings. Use get_column_type_schema query to see available properties and validation rules. Examples: status column labels, dropdown options, number formatting rules, date display preferences.
    /// </summary>
    [JsonPropertyName("defaults")]
    public string? Defaults { get; init; }

    /// <summary>
    /// Whether this column should be opted-out by default on boards. If false or not provided, the column will be automatically included on all boards using this object schema (opt-in by default).
    /// </summary>
    [JsonPropertyName("opt_out_by_default")]
    public bool? OptOutByDefault { get; init; }

    /// <summary>
    /// Policy rules controlling what can be done with the column
    /// </summary>
    [JsonPropertyName("policy")]
    public ColumnPolicyInput Policy { get; init; } = null!;

}
