// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The editable properties of an existing data view target column.
/// </summary>
public sealed partial class DataViewTargetColumnChangesInput
{
    /// <summary>
    /// The new display title.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The new description. Pass null to clear it.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

}
