// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The authorization object that gates access to the data view.
/// </summary>
public sealed partial class DataViewAuthorizationObjectInput
{
    /// <summary>
    /// The identifier of the authorization object.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The type of the authorization object.
    /// </summary>
    [JsonPropertyName("type")]
    public DataViewAuthorizationKind Type { get; init; }

}
