// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A source to include in a data view.
/// </summary>
public sealed partial class DataViewSourceInput
{
    /// <summary>
    /// The source identifier.
    /// </summary>
    [JsonPropertyName("source_id")]
    public DataViewSourceIdInput SourceId { get; init; } = null!;

    /// <summary>
    /// The column mappings for this source. If omitted, mappings are auto-calculated by the server.
    /// </summary>
    [JsonPropertyName("mappings")]
    public List<DataViewColumnMappingInput>? Mappings { get; init; }

}
