// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for specifying a data source for a multi-board vibe app
/// </summary>
public sealed partial class DataSourceInput
{
    /// <summary>
    /// The ID of the data source (e.g. board ID)
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The type of data source
    /// </summary>
    [JsonPropertyName("type")]
    public MondayDataSourceType Type { get; init; }

}
