// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class DeleteFormTagInput
{
    /// <summary>
    /// Options for deleting the tag
    /// </summary>
    [JsonPropertyName("deleteAssociatedColumn")]
    public bool? DeleteAssociatedColumn { get; init; }

}
