// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Disjunction-max query — scores by the best-matching child clause
/// </summary>
public sealed partial class DisMaxInput
{
    /// <summary>
    /// Boost factor for non-best-matching clauses (0–1)
    /// </summary>
    [JsonPropertyName("tie_breaker")]
    public double? TieBreaker { get; init; }

    /// <summary>
    /// Child clauses
    /// </summary>
    [JsonPropertyName("clauses")]
    public List<ClauseInput> Clauses { get; init; } = [];

}
