// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class DynamicPosition
{
    /// <summary>
    /// A boolean flag indicating the desired position of the target item: set to true
    ///   to place the item after the reference object, or false to place it before.
    /// </summary>
    [JsonPropertyName("is_after")]
    public bool? IsAfter { get; init; }

    /// <summary>
    /// The unique identifier of the reference object relative to which the target item will be positioned.
    /// </summary>
    [JsonPropertyName("object_id")]
    public string ObjectId { get; init; } = null!;

    /// <summary>
    /// The type or category of the reference object, used to determine how the target
    ///   item should be positioned in relation to it.
    /// </summary>
    [JsonPropertyName("object_type")]
    public ObjectType ObjectType { get; init; }

}
