// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input type for entity ID mapping.
/// </summary>
public sealed partial class EntityIdMappingInput
{
    /// <summary>
    /// The old ID of the entity.
    /// </summary>
    [JsonPropertyName("oldId")]
    public string OldId { get; init; } = null!;

    /// <summary>
    /// The new ID of the entity.
    /// </summary>
    [JsonPropertyName("newId")]
    public string NewId { get; init; } = null!;

}
