// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A field+value pair for term/phrase/regex style leaf queries
/// </summary>
public sealed partial class FieldTextInput
{
    /// <summary>
    /// The indexed field to match against
    /// </summary>
    [JsonPropertyName("field")]
    public SearchField Field { get; init; }

    /// <summary>
    /// The value to match
    /// </summary>
    [JsonPropertyName("value")]
    public string Value { get; init; } = null!;

}
