// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Checks that a field has at least one indexed value (exists query)
/// </summary>
public sealed partial class FieldInput
{
    /// <summary>
    /// The indexed field that must have a value
    /// </summary>
    [JsonPropertyName("field")]
    public SearchField Field { get; init; }

}
