// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A single uploaded file answer.
/// </summary>
public sealed partial class FileAnswerInput
{
    /// <summary>
    /// The file ID returned by the workforms upload endpoint.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Original file name (e.g. "image.png").
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// File extension (e.g. "pdf").
    /// </summary>
    [JsonPropertyName("extension")]
    public string? Extension { get; init; }

    /// <summary>
    /// Whether the file is an image.
    /// </summary>
    [JsonPropertyName("is_image")]
    public bool? IsImage { get; init; }

}
