// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Accessibility configuration including language and reading direction.
/// </summary>
public sealed partial class FormAccessibilityInput
{
    /// <summary>
    /// Language code for form localization and interface text (e.g., "en", "es", "fr").
    /// </summary>
    [JsonPropertyName("language")]
    public string? Language { get; init; }

    /// <summary>
    /// Alternative text description for the logo image for accessibility.
    /// </summary>
    [JsonPropertyName("logoAltText")]
    public string? LogoAltText { get; init; }

}
