// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Object containing start button configuration for the welcome screen.
/// </summary>
public sealed partial class FormStartButtonInput
{
    /// <summary>
    /// Custom text for the button that begins the form experience.
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; }

}
