// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// An answer to a single form question. Set question_id and exactly one answer field matching the question type.
/// </summary>
public sealed partial class FormAnswerInput
{
    /// <summary>
    /// The ID of the question being answered.
    /// </summary>
    [JsonPropertyName("question_id")]
    public string QuestionId { get; init; } = null!;

    /// <summary>
    /// Answer for name questions.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Answer for email questions.
    /// </summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>
    /// Answer for short text questions.
    /// </summary>
    [JsonPropertyName("short_text")]
    public string? ShortText { get; init; }

    /// <summary>
    /// Answer for long text questions.
    /// </summary>
    [JsonPropertyName("long_text")]
    public string? LongText { get; init; }

    /// <summary>
    /// Answer for link questions.
    /// </summary>
    [JsonPropertyName("link")]
    public string? Link { get; init; }

    /// <summary>
    /// Answer for updates questions.
    /// </summary>
    [JsonPropertyName("updates")]
    public string? Updates { get; init; }

    /// <summary>
    /// Answer for boolean questions.
    /// </summary>
    [JsonPropertyName("boolean")]
    public bool? Boolean { get; init; }

    /// <summary>
    /// Answer for number questions.
    /// </summary>
    [JsonPropertyName("number")]
    public double? Number { get; init; }

    /// <summary>
    /// Answer for rating questions.
    /// </summary>
    [JsonPropertyName("rating")]
    public double? Rating { get; init; }

    /// <summary>
    /// Answer for single-select questions — the selected option ID.
    /// </summary>
    [JsonPropertyName("single_select")]
    public string? SingleSelect { get; init; }

    /// <summary>
    /// Answer for multi-select questions — list of selected option IDs.
    /// </summary>
    [JsonPropertyName("multi_select")]
    public List<int>? MultiSelect { get; init; }

    /// <summary>
    /// Answer for phone questions.
    /// </summary>
    [JsonPropertyName("phone")]
    public PhoneAnswerInput? Phone { get; init; }

    /// <summary>
    /// Answer for country questions.
    /// </summary>
    [JsonPropertyName("country")]
    public CountryAnswerInput? Country { get; init; }

    /// <summary>
    /// Answer for date questions.
    /// </summary>
    [JsonPropertyName("date")]
    public DateAnswerInput? Date { get; init; }

    /// <summary>
    /// Answer for date range questions.
    /// </summary>
    [JsonPropertyName("date_range")]
    public DateRangeAnswerInput? DateRange { get; init; }

    /// <summary>
    /// Answer for hour questions.
    /// </summary>
    [JsonPropertyName("hour")]
    public HourAnswerInput? Hour { get; init; }

    /// <summary>
    /// Answer for location questions.
    /// </summary>
    [JsonPropertyName("location")]
    public LocationAnswerInput? Location { get; init; }

    /// <summary>
    /// Answer for file questions — list of uploaded files.
    /// </summary>
    [JsonPropertyName("file")]
    public List<FileAnswerInput>? File { get; init; }

    /// <summary>
    /// Answer for signature questions — a single uploaded file.
    /// </summary>
    [JsonPropertyName("signature")]
    public FileAnswerInput? Signature { get; init; }

    /// <summary>
    /// Answer for people questions — list of user IDs.
    /// </summary>
    [JsonPropertyName("people")]
    public List<string>? People { get; init; }

    /// <summary>
    /// Answer for connected boards questions — list of connected item IDs.
    /// </summary>
    [JsonPropertyName("connected_boards")]
    public List<string>? ConnectedBoards { get; init; }

    /// <summary>
    /// Answer for subitems questions — each subitem is its own set of answers.
    /// </summary>
    [JsonPropertyName("subitems")]
    public List<SubitemAnswerInput>? Subitems { get; init; }

}
