// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class GrantMarketplaceAppDiscountData
{
    /// <summary>
    /// Number of days a discount will be valid
    /// </summary>
    [JsonPropertyName("days_valid")]
    public int DaysValid { get; init; }

    /// <summary>
    /// Percentage value of a discount
    /// </summary>
    [JsonPropertyName("discount")]
    public int Discount { get; init; }

    /// <summary>
    /// Is discount recurring
    /// </summary>
    [JsonPropertyName("is_recurring")]
    public bool IsRecurring { get; init; }

    /// <summary>
    /// The period of a discount
    /// </summary>
    [JsonPropertyName("period")]
    public DiscountPeriod? Period { get; init; }

    /// <summary>
    /// List of app plan ids
    /// </summary>
    [JsonPropertyName("app_plan_ids")]
    public List<string> AppPlanIds { get; init; } = [];

}
