// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Answer for an hour question.
/// </summary>
public sealed partial class HourAnswerInput
{
    /// <summary>
    /// Hour of day (0-23).
    /// </summary>
    [JsonPropertyName("hour")]
    public int Hour { get; init; }

    /// <summary>
    /// Minute of hour (0-59).
    /// </summary>
    [JsonPropertyName("minute")]
    public int Minute { get; init; }

}
