// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for creating image blocks
/// </summary>
public sealed partial class ImageBlockInput
{
    /// <summary>
    /// The parent block id to append the created block under.
    /// </summary>
    [JsonPropertyName("parent_block_id")]
    public string? ParentBlockId { get; init; }

    /// <summary>
    /// The monday.com asset ID of the image
    /// </summary>
    [JsonPropertyName("asset_id")]
    public string? AssetId { get; init; }

    /// <summary>
    /// The public URL of the image
    /// </summary>
    [JsonPropertyName("public_url")]
    public string? PublicUrl { get; init; }

    /// <summary>
    /// The width of the image
    /// </summary>
    [JsonPropertyName("width")]
    public int? Width { get; init; }

}
