// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A group of rules or rule groups
/// </summary>
public sealed partial class ItemsQueryGroup
{
    /// <summary>
    /// A list of rules
    /// </summary>
    [JsonPropertyName("rules")]
    public List<ItemsQueryRule>? Rules { get; init; }

    /// <summary>
    /// A list of rule groups
    /// </summary>
    [JsonPropertyName("groups")]
    public List<ItemsQueryGroup>? Groups { get; init; }

    /// <summary>
    /// The operator to use for the query rules or rule groups. Default: AND
    /// </summary>
    [JsonPropertyName("operator")]
    public ItemsQueryOperator? @Operator { get; init; }

}
