// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Street name components for a location answer.
/// </summary>
public sealed partial class LocationStreetInput
{
    /// <summary>
    /// Full street name.
    /// </summary>
    [JsonPropertyName("long_name")]
    public string LongName { get; init; } = null!;

    /// <summary>
    /// Abbreviated street name.
    /// </summary>
    [JsonPropertyName("short_name")]
    public string ShortName { get; init; } = null!;

}
