// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Street number components for a location answer.
/// </summary>
public sealed partial class LocationStreetNumberInput
{
    /// <summary>
    /// Full street number.
    /// </summary>
    [JsonPropertyName("long_name")]
    public string LongName { get; init; } = null!;

    /// <summary>
    /// Abbreviated street number.
    /// </summary>
    [JsonPropertyName("short_name")]
    public string ShortName { get; init; } = null!;

}
