// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class MarketplaceAiSearchInput
{
    /// <summary>
    /// The search query term
    /// </summary>
    [JsonPropertyName("query")]
    public string Query { get; init; } = null!;

    /// <summary>
    /// Maximum number of search results to return
    /// </summary>
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

}
