// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Mention object for user or document references
/// </summary>
public sealed partial class MentionInput
{
    /// <summary>
    /// The ID of the mentioned user or document
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The type of mention: user, doc, or board
    /// </summary>
    [JsonPropertyName("type")]
    public DocsMention Type { get; init; }

}
