// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for creating object relations
/// </summary>
public sealed partial class ObjectRelationInput
{
    /// <summary>
    /// Kind of the relation
    /// </summary>
    [JsonPropertyName("kind")]
    public RelationKind Kind { get; init; }

    /// <summary>
    /// ID of the target object
    /// </summary>
    [JsonPropertyName("target_id")]
    public string TargetId { get; init; } = null!;

    /// <summary>
    /// Type of the target object (defaults to "board")
    /// </summary>
    [JsonPropertyName("target_object_type")]
    public TargetObject? TargetObjectType { get; init; }

}
