// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Configuration for automatically populating question values from various data sources such as user account information or URL query parameters.
/// </summary>
public sealed partial class PrefillSettingsInput
{
    /// <summary>
    /// Whether prefill functionality is enabled for this question. When true, the question will attempt to auto-populate values from the specified source.
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

    /// <summary>
    /// The data source to use for prefilling the question value. Check the PrefillSources for available options.
    /// </summary>
    [JsonPropertyName("source")]
    public FormQuestionPrefillSources? Source { get; init; }

    /// <summary>
    /// The specific field or parameter name to lookup from the prefill source. For account sources, this would be a user property like "name" or "email". For query parameters, this would be the parameter name that would be set in the URL.
    /// </summary>
    [JsonPropertyName("lookup")]
    public string? Lookup { get; init; }

}
