// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class QuestionOptionInput
{
    /// <summary>
    /// The display text for the option shown to respondents. Must be at least 1 character long.
    /// </summary>
    [JsonPropertyName("label")]
    public string Label { get; init; } = null!;

    /// <summary>
    /// The internal unique identifier for the option. Used as the option ID in update and delete operations.
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// Whether this option is visible to respondents. Defaults to true.
    /// </summary>
    [JsonPropertyName("visible")]
    public bool? Visible { get; init; }

}
