// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for removing integration tool instances
/// </summary>
public sealed partial class RemoveIntegrationToolsInput
{
    /// <summary>
    /// The ID of the AI app
    /// </summary>
    [JsonPropertyName("ai_app_id")]
    public string AiAppId { get; init; } = null!;

    /// <summary>
    /// Block reference IDs of tools to remove
    /// </summary>
    [JsonPropertyName("block_reference_ids")]
    public List<string> BlockReferenceIds { get; init; } = [];

    /// <summary>
    /// When true, also nulls the credentials variable for the removed tools (full disconnect)
    /// </summary>
    [JsonPropertyName("null_credentials")]
    public bool? NullCredentials { get; init; }

}
