// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Full ThemeDefinition (used for extracted/custom themes). The radii/light/dark fields are JSON-encoded — radii must contain sm/md/lg/xl/2xl, and light/dark must contain the full ThemeColorTokens map. Validated server-side via resolveTheme.
/// </summary>
public sealed partial class ThemeDefinitionInput
{
    /// <summary>
    /// The theme identifier (e.g. extracted_&lt;8-char-hash&gt;)
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Theme display name
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// Base border radius CSS length (e.g. "12px")
    /// </summary>
    [JsonPropertyName("radius")]
    public string Radius { get; init; } = null!;

    /// <summary>
    /// Primary font family name
    /// </summary>
    [JsonPropertyName("font_family")]
    public string FontFamily { get; init; } = null!;

    /// <summary>
    /// Secondary font family name
    /// </summary>
    [JsonPropertyName("font_family_secondary")]
    public string FontFamilySecondary { get; init; } = null!;

    /// <summary>
    /// Border radius scale as a JSON object with sm/md/lg/xl/2xl CSS length values
    /// </summary>
    [JsonPropertyName("radii")]
    public string Radii { get; init; } = null!;

    /// <summary>
    /// Light mode CSS token values (HSL strings keyed by CSS variable name)
    /// </summary>
    [JsonPropertyName("light")]
    public string Light { get; init; } = null!;

    /// <summary>
    /// Dark mode CSS token values (HSL strings keyed by CSS variable name)
    /// </summary>
    [JsonPropertyName("dark")]
    public string Dark { get; init; } = null!;

}
