// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Filters for querying trigger events
/// </summary>
public sealed partial class TriggerEventsFiltersInput
{
    /// <summary>
    /// Date range filter
    /// </summary>
    [JsonPropertyName("dateRange")]
    public DateRangeInput? DateRange { get; init; }

    /// <summary>
    /// Filter by entity kind
    /// </summary>
    [JsonPropertyName("entityKind")]
    public string? EntityKind { get; init; }

    /// <summary>
    /// Filter by automation IDs
    /// </summary>
    [JsonPropertyName("automationIds")]
    public List<int>? AutomationIds { get; init; }

    /// <summary>
    /// Filter by workflow entity IDs
    /// </summary>
    [JsonPropertyName("workflowEntityIds")]
    public List<int>? WorkflowEntityIds { get; init; }

    /// <summary>
    /// Filter by event state
    /// </summary>
    [JsonPropertyName("stateFilter")]
    public List<string>? StateFilter { get; init; }

    /// <summary>
    /// Filter by item identifier
    /// </summary>
    [JsonPropertyName("itemId")]
    public string? ItemId { get; init; }

    /// <summary>
    /// Whether to filter only monday automations
    /// </summary>
    [JsonPropertyName("filterByEntity")]
    public bool? FilterByEntity { get; init; }

    /// <summary>
    /// True if entity is automation
    /// </summary>
    [JsonPropertyName("isAutomationsEntity")]
    public bool? IsAutomationsEntity { get; init; }

    /// <summary>
    /// Filter by app names
    /// </summary>
    [JsonPropertyName("appFilter")]
    public List<string>? AppFilter { get; init; }

    /// <summary>
    /// Filter by host type
    /// </summary>
    [JsonPropertyName("hostType")]
    public string? HostType { get; init; }

    /// <summary>
    /// Filter by host instance identifier
    /// </summary>
    [JsonPropertyName("hostInstanceId")]
    public string? HostInstanceId { get; init; }

    /// <summary>
    /// Filter by creator app feature reference ID
    /// </summary>
    [JsonPropertyName("creatorAppFeatureReferenceId")]
    public int? CreatorAppFeatureReferenceId { get; init; }

    /// <summary>
    /// Billing action count field to filter by
    /// </summary>
    [JsonPropertyName("billingActionCountField")]
    public string? BillingActionCountField { get; init; }

    /// <summary>
    /// Whether workflow filter is applied
    /// </summary>
    [JsonPropertyName("isWorkflowFilter")]
    public bool? IsWorkflowFilter { get; init; }

    /// <summary>
    /// Filter by board identifier
    /// </summary>
    [JsonPropertyName("boardId")]
    public string? BoardId { get; init; }

    /// <summary>
    /// Filter by status
    /// </summary>
    [JsonPropertyName("statusFilter")]
    public List<string>? StatusFilter { get; init; }

}
