// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for updating an app feature with its associated data and release information.
/// </summary>
public sealed partial class UpdateAppFeatureInput
{
    /// <summary>
    /// The app feature data to update. Structure is dynamic per feature type. Any iconUrl/logoUrl/thumbnailUrl (including nested under headerConfig) must be an HTTPS URL or Vibe icon name.
    /// </summary>
    [JsonPropertyName("data")]
    public string? Data { get; init; }

    /// <summary>
    /// The deployment data to update. https://developer.monday.com/apps/docs/deploy-your-app
    /// </summary>
    [JsonPropertyName("deployment")]
    public AppFeatureReleaseInput? Deployment { get; init; }

}
