// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Partial input for updating an existing task
/// </summary>
public sealed partial class UpdateTaskInput
{
    /// <summary>
    /// The task title
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The task description
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// The task status
    /// </summary>
    [JsonPropertyName("status")]
    public TaskStatus? Status { get; init; }

    /// <summary>
    /// The task priority (higher is more important)
    /// </summary>
    [JsonPropertyName("priority")]
    public int? Priority { get; init; }

    /// <summary>
    /// The task due date
    /// </summary>
    [JsonPropertyName("due_date")]
    public string? DueDate { get; init; }

}
