// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class UpdateFormInput
{
    /// <summary>
    /// The title text for the form. Must be at least 1 character long.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// Optional description text providing context about the form purpose.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Ordered array of dehydrated questions, object only including each question ID, for reordering. Must include all existing question IDs.
    /// </summary>
    [JsonPropertyName("questions")]
    public List<QuestionOrderInput>? Questions { get; init; }

}
