// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for updating an existing PTO entry
/// </summary>
public sealed partial class UpdatePtoEntryInput
{
    /// <summary>
    /// ID of the PTO entry to update
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// New start date in YYYY-MM-DD format; must be within 1 year in the past and 20 years in the future
    /// </summary>
    [JsonPropertyName("start")]
    public string? Start { get; init; }

    /// <summary>
    /// New end date in YYYY-MM-DD format; must be within 1 year in the past and 20 years in the future
    /// </summary>
    [JsonPropertyName("end")]
    public string? End { get; init; }

}
