// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for updating an existing widgets surface via LLM regeneration.
/// </summary>
public sealed partial class UpdateWidgetsSurfaceInput
{
    /// <summary>
    /// Natural-language instruction describing the desired changes to the widgets surface.
    /// </summary>
    [JsonPropertyName("prompt")]
    public string Prompt { get; init; } = null!;

    /// <summary>
    /// Metadata associated with the update request.
    /// </summary>
    [JsonPropertyName("metadata")]
    public string? Metadata { get; init; }

    /// <summary>
    /// JSON Schema (JSONSchema7 format) used as the data structure source for widget generation. If omitted, the previously persisted data_structure is used.
    /// </summary>
    [JsonPropertyName("data_structure")]
    public string? DataStructure { get; init; }

    /// <summary>
    /// Optional sample data for the data source, used to guide generation.
    /// </summary>
    [JsonPropertyName("data_sample")]
    public string? DataSample { get; init; }

}
