// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class UpdateWorkflowMetadataInput
{
    /// <summary>
    /// ID of the workflow to update
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// New title for the workflow
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// New description for the workflow
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Importance level of the workflow
    /// </summary>
    [JsonPropertyName("importance")]
    public int? Importance { get; init; }

}
