// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class UserUpdateInput
{
    [JsonPropertyName("user_id")]
    public string UserId { get; init; } = null!;

    [JsonPropertyName("user_attribute_updates")]
    public UserAttributesInput UserAttributeUpdates { get; init; } = null!;

}
