// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Filter input for code versions
/// </summary>
public sealed partial class VibeCodeVersionWhereInput
{
    /// <summary>
    /// Filter by version status (DRAFT, LIVE, RETIRED)
    /// </summary>
    [JsonPropertyName("status")]
    public VibeAppVersionStatus? Status { get; init; }

}
