// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Input for sorting vibe apps
/// </summary>
public sealed partial class VibeAppSortInput
{
    /// <summary>
    /// Field to sort by
    /// </summary>
    [JsonPropertyName("field")]
    public VibeAppSortField? Field { get; init; }

    /// <summary>
    /// Sort order
    /// </summary>
    [JsonPropertyName("order")]
    public SortOrder? Order { get; init; }

}
