// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Configuration for enabling web search in AI requests
/// </summary>
public sealed partial class WebSearchConfigInput
{
    /// <summary>
    /// Whether web search is enabled for this request
    /// </summary>
    [JsonPropertyName("allowed")]
    public bool Allowed { get; init; }

    /// <summary>
    /// Optional configuration for web search behavior
    /// </summary>
    [JsonPropertyName("options")]
    public WebSearchOptionsInput? Options { get; init; }

}
