// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Host data for the workflow. Both id and type must be provided together. If omitted, defaults to account-level with the current account ID.
/// </summary>
public sealed partial class WorkflowHostDataInput
{
    /// <summary>
    /// Instance ID of the host
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Type of host for this workflow
    /// </summary>
    [JsonPropertyName("type")]
    public HostType? Type { get; init; }

}
