// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Customization settings for the workflow
/// </summary>
public sealed partial class WorkflowCustomizationInput
{
    /// <summary>
    /// The access level for CRUD operations on an account-level workflow. Only applicable for ACCOUNT_LEVEL host type. Defaults to USER (only the creator can modify).
    /// </summary>
    [JsonPropertyName("crud_access_level")]
    public CrudAccessLevel? CrudAccessLevel { get; init; }

}
