// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

public sealed partial class WorkflowBlockFieldInput
{
    /// <summary>
    /// The block's field key
    /// </summary>
    [JsonPropertyName("fieldKey")]
    public string FieldKey { get; init; } = null!;

    /// <summary>
    /// Key of the workflow variable defining the configuration for the field key. Always a positive number
    /// </summary>
    [JsonPropertyName("workflowVariableKey")]
    public int WorkflowVariableKey { get; init; }

}
