// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_validation_rule' GraphQL operation.
/// </summary>
public sealed partial class DeleteValidationRuleData
{
    /// <summary>
    /// Delete a validation rule
    /// </summary>
    [JsonPropertyName("delete_validation_rule")]
    public ValidationRule? DeleteValidationRule { get; init; }
}
