// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'deactivate' resource.
/// </summary>
public sealed partial class DeactivateBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DeactivateBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'deactivate_form' mutation.</summary>
    public DeactivateFormRequestBuilder Form => new DeactivateFormRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'deactivate_managed_column' mutation.</summary>
    public DeactivateManagedColumnRequestBuilder ManagedColumn => new DeactivateManagedColumnRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'deactivate_users' mutation.</summary>
    public DeactivateUsersRequestBuilder Users => new DeactivateUsersRequestBuilder(_graphQlClient);

}
