// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Error codes for activating users.
/// </summary>
public enum ActivateUsersErrorCode
{
    EXCEEDSBATCHLIMIT,

    INVALIDINPUT,

    USERNOTFOUND,

    CANNOTUPDATESELF,

    FAILED

}
