// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Target language for translation.
/// </summary>
public enum AiColumnLanguage
{
    English,

    Spanish,

    French,

    German,

    Hebrew,

    Chinese,

    Korean,

    Arabic,

    Bengali,

    Danish,

    Dutch,

    Hindi,

    Indonesian,

    Italian,

    Japanese,

    Norwegian,

    Polish,

    Portuguese,

    Russian,

    Swedish,

    Thai,

    Turkish,

    Vietnamese

}
