// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Available AI model tiers.
/// </summary>
public enum AiModel
{
    MONDAYFAST,

    MONDAYSTANDARD,

    MONDAYPOWERFUL

}
