// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Allowed MIME types for file uploads
/// </summary>
public enum AllowedFileMime
{
    IMAGEPNG,

    IMAGEJPEG,

    IMAGEGIF,

    IMAGEWEBP,

    IMAGEAVIF,

    IMAGEHEIC,

    IMAGESVG,

    VIDEOMP4,

    VIDEOWEBM,

    VIDEOQUICKTIME,

    VIDEOOGG,

    APPLICATIONPDF,

    TEXTCSV,

    APPLICATIONXLSX,

    TEXTMARKDOWN,

    TEXTPLAIN

}
