// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The hosting type for the app feature release
/// </summary>
public enum AppFeatureReleaseKind
{
    SERVERSIDECODE,

    CLIENTSIDECODE,

    EXTERNALHOSTING

}
