// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The kind of the app feature relation.
/// </summary>
public enum AppFeatureRelationKind
{
    DEPENDENCY,

    HOSTING

}
