// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Permitted OAuth scopes for apps
/// </summary>
public enum AppPermission
{
    MEREAD,

    BOARDSREAD,

    BOARDSWRITE,

    WORKSPACESREAD,

    WORKSPACESWRITE,

    USERSREAD,

    USERSWRITE,

    ACCOUNTREAD,

    UPDATESREAD,

    UPDATESWRITE,

    TAGSREAD,

    ASSETSREAD,

    TEAMSREAD,

    TEAMSWRITE,

    DEPARTMENTSREAD,

    DEPARTMENTSWRITE,

    NOTIFICATIONSWRITE,

    WEBHOOKSWRITE,

    WEBHOOKSREAD,

    DOCSREAD,

    DOCSWRITE

}
