// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The type of entity that a reaction is attributed to.
/// </summary>
public enum AttributionEntity
{
    AGENT

}
