// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The role of the user.
/// </summary>
public enum BaseRoleName
{
    GUEST,

    VIEWONLY,

    MEMBER,

    ADMIN

}
