// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Alignment options for blocks
/// </summary>
public enum BlockAlignment
{
    LEFT,

    RIGHT,

    CENTER

}
