// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The board object types.
/// </summary>
public enum BoardObjectType
{
    Board,

    CustomObject,

    Document,

    SubItemsBoard

}
