// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Enum representing different usage types for board operations
/// </summary>
public enum BoardUsage
{
    CONVERTTOPROJECT,

    CONNECTTOPORTFOLIO

}
