// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The board hierarchy type
/// </summary>
public enum BoardHierarchy
{
    Classic,

    MultiLevel

}
