// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A board-scope permission that can be required in addition to regular board read access.
/// </summary>
public enum BoardPermission
{
    BOARDREPORTABILITY

}
