// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The board subscriber kind.
/// </summary>
public enum BoardSubscriberKind
{
    Owner,

    Subscriber

}
