// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Current state of the import process
/// </summary>
public enum BulkImportState
{
    UPLOADPENDING,

    REJECTED,

    PROCESSING,

    COMPLETED,

    FAILED

}
