// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Status of a brand image
/// </summary>
public enum CampaignsBrandImageStatus
{
    PENDING,

    CONFIRMED

}
