// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Types of analytics events for campaigns
/// </summary>
public enum CampaignsAnalyticsEventKind
{
    EMAILBOUNCED,

    EMAILDELIVERED,

    EMAILSENT,

    EMAILRECIPIENTCOMPLAINT,

    EMAILRECIPIENTUNSUBSCRIBED,

    EMAILRECIPIENTGROUPUNSUBSCRIBED,

    EMAILRECIPIENTGROUPRESUBSCRIBED,

    EMAILDROPPED,

    EMAILOPENED,

    EMAILCLICKED

}
