// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Types of brand images
/// </summary>
public enum CampaignsBrandImageKind
{
    PRIMARYLOGO,

    SECONDARYLOGO,

    ATTACHMENT

}
