// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Types of brand colors
/// </summary>
public enum CampaignsBrandColorKind
{
    PRIMARY,

    SECONDARY,

    ACCENT,

    TEXT,

    OTHER

}
