// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Capabilities supported by the API
/// </summary>
public enum ColumnCapability
{
    CALCULATED,

    VISIBILITY

}
