// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Mode for creating a new vibe app
/// </summary>
public enum CreateAppModeInput
{
    BUILD,

    ASK

}
