// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The type of a directory resource
/// </summary>
public enum DirectoryResourceKind
{
    USER,

    VIEWER,

    GUEST

}
