// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The kind/type of document access level
/// </summary>
public enum DocKind
{
    @Private,

    @Public,

    Share

}
