// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The type of relation between a field and its type
/// </summary>
public enum FieldTypeRelationType
{
    PRIMITIVE,

    INTERFACE,

    CUSTOM

}
