// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// One value out of a list of valid folder font weights
/// </summary>
public enum FolderFontWeight
{
    FONTWEIGHTBOLD,

    FONTWEIGHTLIGHT,

    FONTWEIGHTNORMAL,

    FONTWEIGHTVERYLIGHT,

    NULL

}
