// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The type of the question (ex. text, number, MultiSelect etc.)
/// </summary>
public enum FormQuestionType
{
    Boolean,

    ConnectedBoards,

    Country,

    Date,

    DateRange,

    Email,

    File,

    HOUR,

    Link,

    Location,

    LongText,

    MultiSelect,

    Name,

    Number,

    People,

    Phone,

    Rating,

    ShortText,

    Signature,

    SingleSelect,

    Subitems,

    Updates,

    DISPLAYTEXT,

    PAGEBLOCK

}
