// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The method by which a user was added to the account.
/// </summary>
public enum InvitationMethod
{
    USER,

    SCIM,

    SSO,

    AUTHDOMAIN,

    FIRSTUSER,

    CONSOLIDATION,

    INTERNALCREATION,

    UNKNOWN,

    SERVICEPORTALAUTHDOMAIN,

    SERVICEPORTALUSERINVITATION,

    APIUSERCREATION,

    AGENTUSERCREATION,

    SYSTEMCREATION

}
