// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The operator to use for the value comparison
/// </summary>
public enum ItemsQueryRuleOperator
{
    AnyOf,

    NotAnyOf,

    IsEmpty,

    IsNotEmpty,

    WithinTheLast,

    WithinTheNext,

    GreaterThan,

    GreaterThanOrEquals,

    LowerThan,

    LowerThanOrEqual,

    Between,

    StartsWith,

    EndsWith,

    ContainsText,

    ContainsTerms,

    NotContainsText

}
