// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Specific types of list blocks
/// </summary>
public enum ListBlock
{
    BULLETEDLIST,

    NUMBEREDLIST,

    CHECKLIST

}
