// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Available LLM models for code generation
/// </summary>
public enum LLMModelInput
{
    CLAUDE45SONNET,

    CLAUDE46SONNET,

    CLAUDE5SONNET,

    CLAUDEHAIKU45,

    CLAUDEOPUS46,

    GEMINI31PRO,

    GEMINI35FLASH,

    GEMINI36FLASH,

    GEMINI31FLASHLITE,

    GEMINI35FLASHLITE,

    GPT5NANO,

    GPT5,

    GPT5MINI,

    GPT51,

    GPT52

}
