// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The type of access the current user has to a meeting.
/// </summary>
public enum MeetingAccess
{
    OWN,

    SHAREDWITHME,

    SHAREDWITHACCOUNT

}
