// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Indicates where the unit symbol should be placed in a number value
/// </summary>
public enum NumberValueUnitDirection
{
    Left,

    Right

}
