// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A publishable operation or informational difference between a board and the object schema it follows.
/// </summary>
public enum ObjectSchemaColumnChangeType
{
    CREATE,

    UPDATE,

    MISSINGFROMBOARD

}
