// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Strategy for handling matching items during import
/// </summary>
public enum OnMatchBehaviour
{
    UPSERT,

    SKIP

}
