// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Defines the sorting order for returned objects in the objects query.
/// </summary>
public enum OrderBy
{
    CREATEDAT,

    USEDAT

}
