// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Type of resource in the planner
/// </summary>
public enum PlannerResourceKind
{
    USER,

    PLACEHOLDER

}
