// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The position relative method.
/// </summary>
public enum PositionRelative
{
    AfterAt,

    BeforeAt

}
