// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The primitive types supported by the system
/// </summary>
public enum PrimitiveTypes
{
    STRING,

    NUMBER,

    FLOAT,

    BOOLEAN,

    DATE,

    HOUR

}
