// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Defines the visibility and access control settings for objects in the Monday.com Objects Platform.
/// </summary>
public enum PrivacyKind
{
    PRIVATE,

    PUBLIC

}
