// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The direction of the relation from the object perspective
/// </summary>
public enum RelationDirection
{
    OUTGOING,

    INCOMING

}
