// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Algorithms for reranking results.
/// </summary>
public enum RerankingStrategy
{
    CROSSENCODER

}
