// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// A route-condition operator, identified by its operator id.
/// </summary>
public enum RouteConditionOperator
{
    IsEmpty,

    IsNotEmpty,

    @Is,

    IsNot,

    Contains,

    NotContains,

    Equals,

    NotEquals,

    LessThan,

    LessThanEquals,

    GreaterThan,

    GreaterThanEquals,

    Includes,

    NotIncludes

}
