// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Which workflow revision to use for a run-once execution
/// </summary>
public enum RunOnceSource
{
    LIVE,

    DRAFT

}
