// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The kind of sprint snapshot.
/// </summary>
public enum SprintSnapshotKind
{
    START,

    COMPLETE

}
