// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The status of the subscription. Possible values: active, inactive.
/// </summary>
public enum SubscriptionStatus
{
    Active,

    Inactive

}
