// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The type of target object for a relation
/// </summary>
public enum TargetObject
{
    BOARD,

    DASHBOARD

}
