// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Activation status values that can be set via mutations.
/// </summary>
public enum UpdatableUserStatus
{
    ACTIVE,

    INACTIVE

}
