// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// All possible API version types
/// </summary>
public enum VersionKind
{
    Maintenance,

    Current,

    ReleaseCandidate,

    Dev,

    Deprecated,

    OldMaintenance,

    OldPreviousMaintenance,

    PreviousMaintenance

}
