// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// All possible API version types
/// </summary>
public enum VersionKind
{
    Current,

    Deprecated,

    Dev,

    Maintenance,

    OldMaintenance,

    OldPreviousMaintenance,

    PreviousMaintenance,

    ReleaseCandidate

}
