// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Sort direction for an order-by clause.
/// </summary>
public enum VibeSortDir
{
    ASC,

    DESC

}
