// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The variant/platform target for vibe apps
/// </summary>
public enum VibeVariant
{
    BOARDVIEW,

    ITEMVIEW,

    VIBEITEMVIEW,

    OBJECT,

    OBJECTFULLSTACK

}
