// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The type of visit when a user opens a Vibe app
/// </summary>
public enum VibeAppVisitKind
{
    VIEW,

    BUILD

}
