// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Specifies the entity scope for the created view
/// </summary>
public enum ViewContext
{
    BOARD

}
