// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The webhook's target type.
/// </summary>
public enum WebhookEventType
{
    ChangeColumnValue,

    ChangeName,

    ChangeSpecificColumnValue,

    ChangeStatusColumnValue,

    ChangeSubitemColumnValue,

    ChangeSubitemName,

    CreateColumn,

    CreateItem,

    CreateSubitem,

    CreateSubitemUpdate,

    CreateUpdate,

    DeleteUpdate,

    EditUpdate,

    ItemArchived,

    ItemDeleted,

    ItemMovedToAnyGroup,

    ItemMovedToSpecificGroup,

    ItemRestored,

    MoveSubitem,

    SubitemArchived,

    SubitemDeleted

}
