// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The context where a workflow template can be accessed
/// </summary>
public enum WorkflowTemplateContext
{
    LITEBUILDER

}
