// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The kind of workflow block. This is the type of the block that is used in the UI
/// </summary>
public enum WorkflowBlockKind
{
    WAIT

}
