// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// The membership kind of the user in the workspace.
/// </summary>
public enum WorkspaceMembershipKind
{
    All,

    Member

}
