// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_marketplace_app_discount' GraphQL mutation.
/// </summary>
public sealed partial class CreateMarketplaceAppDiscountRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateMarketplaceAppDiscountRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_marketplace_app_discount' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateMarketplaceAppDiscountData>> Execute(CreateMarketplaceAppDiscountVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateMarketplaceAppDiscount($app_id: ID!, $account_slug: String!, $discount_data: CreateMarketplaceAppDiscountInput!) { create_marketplace_app_discount(app_id: $app_id, account_slug: $account_slug, discount_data: $discount_data) { granted_discount { days_valid discount is_recurring period app_plan_ids app_id } } }";
        return _graphQlClient.Execute<CreateMarketplaceAppDiscountData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_marketplace_app_discount' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<CreateMarketplaceAppDiscountResult?> GetValue(CreateMarketplaceAppDiscountVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateMarketplaceAppDiscountData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateMarketplaceAppDiscount;
    }
}
