// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'get_view_schema_by_type' GraphQL operation.
/// </summary>
public sealed class GetGetViewSchemaByTypeVariables
{
    [JsonPropertyName("type")]
    public ViewKind Type { get; init; }

    [JsonPropertyName("mutationType")]
    public ViewMutationKind MutationType { get; init; }

}
