// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'board_dependencies' GraphQL operation.
/// </summary>
public sealed class GetBoardDependenciesVariables
{
    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    [JsonPropertyName("page")]
    public int? Page { get; init; }

    [JsonPropertyName("include_items_without_predecessors")]
    public bool? IncludeItemsWithoutPredecessors { get; init; }

}
