// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'account' GraphQL query.
/// </summary>
public sealed partial class GetAccountRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetAccountRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'account'.
    /// </summary>
    public ValueTask<GraphQlResponse<GetAccountData>> Execute(CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetAccount { account { active_members_count country_code created_at first_day_of_the_week id logo name plan { max_users period tier version } products { default_workspace_id id kind tier } show_timeline_weekends sign_up_product_kind slug tier is_during_trial is_trial_expired } }";
        return _graphQlClient.Execute<GetAccountData>(gqlQuery, null, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'account' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Account?> GetValue(CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetAccountData> response = await Execute(cancellationToken).ConfigureAwait(false);
        return response.Data?.Account;
    }
}
