// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'form' GraphQL operation.
/// </summary>
public sealed partial class GetFormData
{
    /// <summary>
    /// Fetch a form by its token. The returned form includes all the details of the form such as its settings, questions, title, etc. Use this endpoint when you need to retrieve complete form data for display or processing. Requires that the requesting user has read access to the associated board.
    /// </summary>
    [JsonPropertyName("form")]
    public ResponseForm? Form { get; init; }
}
