// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_validation_rule' GraphQL operation.
/// </summary>
public sealed class CreateValidationRuleVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("type")]
    public ValidationsEntityType? Type { get; init; }

    [JsonPropertyName("rule")]
    public ValidationRuleInput Rule { get; init; } = null!;

}
