// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'activate' resource.
/// </summary>
public sealed partial class ActivateBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ActivateBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'activate_form' mutation.</summary>
    public ActivateFormRequestBuilder Form => new ActivateFormRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'activate_managed_column' mutation.</summary>
    public ActivateManagedColumnRequestBuilder ManagedColumn => new ActivateManagedColumnRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'activate_users' mutation.</summary>
    public ActivateUsersRequestBuilder Users => new ActivateUsersRequestBuilder(_graphQlClient);

}
