// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'publish_object' GraphQL operation.
/// </summary>
public sealed partial class PublishObjectData
{
    /// <summary>
    /// Publishes object out of draft state. Returns {success: true} on success, {success: false} on failure.
    /// </summary>
    [JsonPropertyName("publish_object")]
    public ObjectOperationResponse? PublishObject { get; init; }
}
