// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'knowledge_base_search' GraphQL operation.
/// </summary>
public sealed class GetKnowledgeBaseSearchVariables
{
    [JsonPropertyName("query")]
    public string Query { get; init; } = null!;

    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

}
