// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_column' GraphQL mutation.
/// </summary>
public sealed partial class CreateColumnRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateColumnRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_column' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateColumnData>> Execute(CreateColumnVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateColumn($board_id: ID!, $id: String, $title: String!, $description: String, $after_column_id: ID, $capabilities: ColumnCapabilitiesInput, $defaults: JSON, $column_type: ColumnType!) { create_column(board_id: $board_id, id: $id, title: $title, description: $description, after_column_id: $after_column_id, capabilities: $capabilities, defaults: $defaults, column_type: $column_type) { id title description type width archived settings settings_str revision capabilities { calculated { function calculated_type } visibility } } }";
        return _graphQlClient.Execute<CreateColumnData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_column' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<Column?> GetValue(CreateColumnVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateColumnData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateColumn;
    }
}
