// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'enroll_items_to_sequence' GraphQL operation.
/// </summary>
public sealed class EnrollItemsToSequenceVariables
{
    [JsonPropertyName("input")]
    public EnrollToSequenceInput Input { get; init; } = null!;

}
