// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'segments' GraphQL operation.
/// </summary>
public sealed partial class GetSegmentsData
{
    /// <summary>
    /// List audience segments for the current account
    /// </summary>
    [JsonPropertyName("segments")]
    public List<CampaignsSegment>? Segments { get; init; }
}
