// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'delete_teams_from_workspace' GraphQL operation.
/// </summary>
public sealed class DeleteTeamsFromWorkspaceVariables
{
    [JsonPropertyName("team_ids")]
    public List<string> TeamIds { get; init; } = [];

    [JsonPropertyName("workspace_id")]
    public string WorkspaceId { get; init; } = null!;

}
