// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'install_app' GraphQL operation.
/// </summary>
public sealed class InstallAppVariables
{
    [JsonPropertyName("input")]
    public InstallAppInput Input { get; init; } = null!;

}
