// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'install_app' GraphQL mutation.
/// </summary>
public sealed partial class InstallAppRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public InstallAppRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'install_app' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<InstallAppData>> Execute(InstallAppVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation InstallApp($input: InstallAppInput!) { install_app(input: $input) { app_id created } }";
        return _graphQlClient.Execute<InstallAppData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'install_app' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<InstallAppResponse?> GetValue(InstallAppVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<InstallAppData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.InstallApp;
    }
}
