// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_dropdown_managed_column' GraphQL operation.
/// </summary>
public sealed partial class UpdateDropdownManagedColumnData
{
    /// <summary>
    /// Update managed column of type dropdown mutation.
    /// </summary>
    [JsonPropertyName("update_dropdown_managed_column")]
    public DropdownManagedColumn? UpdateDropdownManagedColumn { get; init; }
}
