// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'moveItemTo' resource.
/// </summary>
public sealed partial class MoveItemToBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public MoveItemToBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'move_item_to_board' mutation.</summary>
    public MoveItemToBoardRequestBuilder Board => new MoveItemToBoardRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'move_item_to_group' mutation.</summary>
    public MoveItemToGroupRequestBuilder Group => new MoveItemToGroupRequestBuilder(_graphQlClient);

}
