// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'docs' GraphQL operation.
/// </summary>
public sealed class GetDocsVariables
{
    [JsonPropertyName("ids")]
    public List<string>? Ids { get; init; }

    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    [JsonPropertyName("object_ids")]
    public List<string>? ObjectIds { get; init; }

    [JsonPropertyName("order_by")]
    public DocsOrderBy? OrderBy { get; init; }

    [JsonPropertyName("page")]
    public int? Page { get; init; }

    [JsonPropertyName("workspace_ids")]
    public List<string>? WorkspaceIds { get; init; }

}
