// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'pin_to_top' GraphQL operation.
/// </summary>
public sealed partial class PinToTopData
{
    [JsonPropertyName("pin_to_top")]
    public Update PinToTop { get; init; } = null!;
}
