// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'create_object_relations' GraphQL mutation.
/// </summary>
public sealed partial class CreateObjectRelationsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CreateObjectRelationsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'create_object_relations' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CreateObjectRelationsData>> Execute(CreateObjectRelationsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CreateObjectRelations($source_object_id: ID!, $relations: [ObjectRelationInput!]!) { create_object_relations(source_object_id: $source_object_id, relations: $relations) { id source_object_id target_id target_object_type kind } }";
        return _graphQlClient.Execute<CreateObjectRelationsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'create_object_relations' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<ObjectRelation>?> GetValue(CreateObjectRelationsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CreateObjectRelationsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.CreateObjectRelations;
    }
}
