// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'platform_api' GraphQL operation.
/// </summary>
public sealed partial class GetPlatformApiData
{
    /// <summary>
    /// Platform API data.
    /// </summary>
    [JsonPropertyName("platform_api")]
    public PlatformApi? PlatformApi { get; init; }
}
