// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'duplicate_group' GraphQL operation.
/// </summary>
public sealed class DuplicateGroupVariables
{
    [JsonPropertyName("add_to_top")]
    public bool? AddToTop { get; init; }

    [JsonPropertyName("board_id")]
    public string BoardId { get; init; } = null!;

    [JsonPropertyName("group_id")]
    public string GroupId { get; init; } = null!;

    [JsonPropertyName("group_title")]
    public string? GroupTitle { get; init; }

}
