// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_group' GraphQL operation.
/// </summary>
public sealed partial class UpdateGroupData
{
    /// <summary>
    /// Update an existing group.
    /// </summary>
    [JsonPropertyName("update_group")]
    public Group? UpdateGroup { get; init; }
}
