// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'batch_extend_trial_period' GraphQL operation.
/// </summary>
public sealed class BatchExtendTrialPeriodVariables
{
    [JsonPropertyName("account_slugs")]
    public List<string> AccountSlugs { get; init; } = [];

    [JsonPropertyName("app_id")]
    public string AppId { get; init; } = null!;

    [JsonPropertyName("duration_in_days")]
    public int DurationInDays { get; init; }

    [JsonPropertyName("plan_id")]
    public string PlanId { get; init; } = null!;

}
