// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'regenerate_service_user_token' GraphQL operation.
/// </summary>
public sealed partial class RegenerateServiceUserTokenData
{
    /// <summary>
    /// Revokes all existing tokens and generates a new API token for a service user.
    /// </summary>
    [JsonPropertyName("regenerate_service_user_token")]
    public string? RegenerateServiceUserToken { get; init; }
}
