// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'create_update' GraphQL operation.
/// </summary>
public sealed partial class CreateUpdateData
{
    [JsonPropertyName("create_update")]
    public Update? CreateUpdate { get; init; }
}
