// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_doc_block' GraphQL operation.
/// </summary>
public sealed class CreateDocBlockVariables
{
    [JsonPropertyName("after_block_id")]
    public string? AfterBlockId { get; init; }

    [JsonPropertyName("content")]
    public string Content { get; init; } = null!;

    [JsonPropertyName("doc_id")]
    public string DocId { get; init; } = null!;

    [JsonPropertyName("parent_block_id")]
    public string? ParentBlockId { get; init; }

    [JsonPropertyName("type")]
    public DocBlockContentType Type { get; init; }

}
