// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delete_question' GraphQL operation.
/// </summary>
public sealed partial class DeleteQuestionData
{
    /// <summary>
    /// Permanently remove a question from a form. This action cannot be undone.
    /// </summary>
    [JsonPropertyName("delete_question")]
    public bool? DeleteQuestion { get; init; }
}
