// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'export_markdown_from_doc' GraphQL operation.
/// </summary>
public sealed partial class GetExportMarkdownFromDocData
{
    /// <summary>
    /// Converts document content into standard markdown format for external use, backup, or processing. Exports the entire document by default, or specific blocks if block IDs are provided. Use this to extract content for integration with other systems, create backups, generate reports, or process document content with external tools. The output is clean, portable markdown that preserves formatting and structure.
    /// </summary>
    [JsonPropertyName("export_markdown_from_doc")]
    public ExportMarkdownResult? ExportMarkdownFromDoc { get; init; }
}
