// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'update_form' GraphQL operation.
/// </summary>
public sealed partial class UpdateFormData
{
    /// <summary>
    /// Update form properties including title, description, or question order.
    /// </summary>
    [JsonPropertyName("update_form")]
    public ResponseForm? UpdateForm { get; init; }
}
