// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_update' GraphQL operation.
/// </summary>
public sealed class CreateUpdateVariables
{
    [JsonPropertyName("body")]
    public string Body { get; init; } = null!;

    [JsonPropertyName("original_creation_date")]
    public string? OriginalCreationDate { get; init; }

    [JsonPropertyName("mentions_list")]
    public List<UpdateMention>? MentionsList { get; init; }

    [JsonPropertyName("item_id")]
    public string? ItemId { get; init; }

    [JsonPropertyName("parent_id")]
    public string? ParentId { get; init; }

    [JsonPropertyName("use_app_info")]
    public bool? UseAppInfo { get; init; }

}
