// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'export_graph' GraphQL query.
/// </summary>
public sealed partial class GetExportGraphRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetExportGraphRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'export_graph' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetExportGraphData>> Execute(GetExportGraphVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetExportGraph($boardId: String!) { export_graph(boardId: $boardId) { boardId graphData exportedAt nodeCount edgeCount graphAttributes cycles } }";
        return _graphQlClient.Execute<GetExportGraphData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'export_graph' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<BoardGraphExport?> GetValue(GetExportGraphVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetExportGraphData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.ExportGraph;
    }
}
