// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'export_graph' GraphQL operation.
/// </summary>
public sealed class GetExportGraphVariables
{
    [JsonPropertyName("boardId")]
    public string BoardId { get; init; } = null!;

}
