// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'create_department' GraphQL operation.
/// </summary>
public sealed class CreateDepartmentVariables
{
    [JsonPropertyName("data")]
    public CreateDepartmentDataInput Data { get; init; } = null!;

}
