// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'delete_widget' GraphQL operation.
/// </summary>
public sealed class DeleteWidgetVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

}
