// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'duplicate' resource.
/// </summary>
public sealed partial class DuplicateBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DuplicateBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'duplicate_board' mutation.</summary>
    public DuplicateBoardRequestBuilder Board => new DuplicateBoardRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'duplicate_doc' mutation.</summary>
    public DuplicateDocRequestBuilder Doc => new DuplicateDocRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'duplicate_group' mutation.</summary>
    public DuplicateGroupRequestBuilder Group => new DuplicateGroupRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'duplicate_item' mutation.</summary>
    public DuplicateItemRequestBuilder Item => new DuplicateItemRequestBuilder(_graphQlClient);

}
