// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'backfill_items' GraphQL operation.
/// </summary>
public sealed partial class BackfillItemsData
{
    /// <summary>
    /// Initialize a backfill job for a board and group. Designed for data migrations with no side effects and a 20k row limit. Returns job ID and upload URL to begin the process.
    /// </summary>
    [JsonPropertyName("backfill_items")]
    public UploadJobInit? BackfillItems { get; init; }
}
