// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'complexity' GraphQL operation.
/// </summary>
public sealed partial class GetComplexityData
{
    /// <summary>
    /// Get the complexity data of your queries.
    /// </summary>
    [JsonPropertyName("complexity")]
    public Complexity? Complexity { get; init; }
}
