// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'attach' resource.
/// </summary>
public sealed partial class AttachBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public AttachBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'attach_dropdown_managed_column' mutation.</summary>
    public AttachDropdownManagedColumnRequestBuilder DropdownManagedColumn => new AttachDropdownManagedColumnRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'attach_status_managed_column' mutation.</summary>
    public AttachStatusManagedColumnRequestBuilder StatusManagedColumn => new AttachStatusManagedColumnRequestBuilder(_graphQlClient);

}
