// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'move_item_to_group' GraphQL operation.
/// </summary>
public sealed class MoveItemToGroupVariables
{
    [JsonPropertyName("group_id")]
    public string GroupId { get; init; } = null!;

    [JsonPropertyName("item_id")]
    public string? ItemId { get; init; }

}
