// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'version' GraphQL operation.
/// </summary>
public sealed partial class GetVersionData
{
    /// <summary>
    /// Get the API version in use
    /// </summary>
    [JsonPropertyName("version")]
    public Version Version { get; init; } = null!;
}
