// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'analytics_events' GraphQL operation.
/// </summary>
public sealed class GetAnalyticsEventsVariables
{
    [JsonPropertyName("identifier")]
    public string Identifier { get; init; } = null!;

    [JsonPropertyName("campaign_id")]
    public string? CampaignId { get; init; }

    [JsonPropertyName("event_type")]
    public CampaignsAnalyticsEventKind? EventType { get; init; }

    [JsonPropertyName("limit")]
    public int Limit { get; init; }

    [JsonPropertyName("next_token")]
    public string? NextToken { get; init; }

}
