// <auto-generated />
#nullable enable
namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'export' resource.
/// </summary>
public sealed partial class ExportBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ExportBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'export_events' query.</summary>
    public GetExportEventsRequestBuilder Events => new GetExportEventsRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'export_graph' query.</summary>
    public GetExportGraphRequestBuilder Graph => new GetExportGraphRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'export_markdown_from_doc' query.</summary>
    public GetExportMarkdownFromDocRequestBuilder MarkdownFromDoc => new GetExportMarkdownFromDocRequestBuilder(_graphQlClient);

}
