// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'update_dependency_column' GraphQL mutation.
/// </summary>
public sealed partial class UpdateDependencyColumnRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public UpdateDependencyColumnRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'update_dependency_column' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<UpdateDependencyColumnData>> Execute(UpdateDependencyColumnVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation UpdateDependencyColumn($boardId: String!, $pulseId: String!, $value: DependencyValueInput!, $columnId: String!, $successor_new_date: TimelineDateInput) { update_dependency_column(boardId: $boardId, pulseId: $pulseId, value: $value, columnId: $columnId, successor_new_date: $successor_new_date) }";
        return _graphQlClient.Execute<UpdateDependencyColumnData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'update_dependency_column' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<string?> GetValue(UpdateDependencyColumnVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<UpdateDependencyColumnData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.UpdateDependencyColumn;
    }
}
