// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Request parameters for the 'campaigns' GraphQL operation.
/// </summary>
public sealed class GetCampaignsVariables
{
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    [JsonPropertyName("status")]
    public List<CampaignsStatusKind>? Status { get; init; }

    [JsonPropertyName("name")]
    public string? Name { get; init; }

    [JsonPropertyName("sent_after")]
    public DateOnly? SentAfter { get; init; }

    [JsonPropertyName("sent_before")]
    public DateOnly? SentBefore { get; init; }

    [JsonPropertyName("sort_field")]
    public CampaignsSortField? SortField { get; init; }

    [JsonPropertyName("sort_order")]
    public CampaignsSortOrder? SortOrder { get; init; }

}
