// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'campaigns' GraphQL query.
/// </summary>
public sealed partial class GetCampaignsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GetCampaignsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL query 'campaigns' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GetCampaignsData>> Execute(GetCampaignsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"query GetCampaigns($limit: Int, $status: [CampaignsStatusKind!], $name: String, $sent_after: Date, $sent_before: Date, $sort_field: CampaignsSortField, $sort_order: CampaignsSortOrder) { campaigns(limit: $limit, status: $status, name: $name, sent_after: $sent_after, sent_before: $sent_before, sort_field: $sort_field, sort_order: $sort_order) { id name status sent_on created_at updated_at summary { total_sent total_delivered total_opens unique_opens total_clicks unique_clicks total_unsubscribes unique_unsubscribes total_undelivered unique_undelivered total_spam_reports unique_spam_reports } created_by { id title phone location birthday mobile_phone country_code current_language time_zone_identifier utc_hours_diff url account { active_members_count country_code created_at first_day_of_the_week id logo name show_timeline_weekends sign_up_product_kind slug tier is_during_trial is_trial_expired } account_products { default_workspace_id id kind tier } custom_field_metas { description editable field_type flagged icon id position title } custom_field_values { custom_field_meta_id value } enabled encrypt_api_token is_admin is_guest is_pending is_verified is_view_only join_date last_activity out_of_office { active disable_notifications end_date start_date type } photo_original photo_small photo_thumb photo_thumb_small photo_tiny sign_up_product_kind department { id name reserved_seats assigned_seats } account_id status invitation_method serial_number is_deleted photo_url { original small thumb thumb_small tiny } became_active_at bb_visitor_id is_email_confirmed user_config { kind role_id visibility behaviors group } email name kind created_at } subject preview_text schedule_type scheduled_time segment_ids preview_image template_html } }";
        return _graphQlClient.Execute<GetCampaignsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'campaigns' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<List<CampaignsEmailCampaign>?> GetValue(GetCampaignsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GetCampaignsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.Campaigns;
    }
}
