// <auto-generated />
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Monday.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'backfill_items' GraphQL mutation.
/// </summary>
public sealed partial class BackfillItemsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public BackfillItemsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'backfill_items' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<BackfillItemsData>> Execute(BackfillItemsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation BackfillItems($board_id: ID!, $group_id: ID!) { backfill_items(board_id: $board_id, group_id: $group_id) { job_id upload_url } }";
        return _graphQlClient.Execute<BackfillItemsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'backfill_items' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<UploadJobInit?> GetValue(BackfillItemsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<BackfillItemsData> response = await Execute(request, cancellationToken).ConfigureAwait(false);
        return response.Data?.BackfillItems;
    }
}
